	/**
	 * Локализация
	 */
	tinymce.util.I18n.add('ru', {
		// Табы
		"Emoji": "Эмодзи (Emoji)",
		"Smiles": "Смайлики",
		"Emotics": "Эмоции",
		"People": "Люди",
		"Animals": "Животные",
		"Nature": "Природа",
		"Food and Drinks": "Еда и Напитки",
		"Places and Travels": "Места и Путешествия",
		"Events and Celebrations": "Мероприятия и Праздники",
		"Objects and Things": "Объекты и Вещи",
		"Symbols": "Символы",
		"Flags": "Флаги",
		// Иконки
		// Смайлмки
		"The grinning face": "Ухмыляющееся лицо",
		"A smiling face with an open mouth": "Улыбающееся лицо\nс открытым ртом",
		"A smiling face with an open mouth and smiling eyes": "Улыбающееся лицо\nс открытым ртом\nи улыбающимися глазами",
		"A grinning face with smiling eyes": "Ухмыляющееся лицо\nс улыбающимися глазами",
		"A smiling face with an open mouth and tightly closed eyes": "Улыбающееся лицо\nс открытым ртом\nи плотно закрытыми глазами",
		"A smiling face with an open mouth and cold sweat": "Улыбающееся лицо\nс открытым ртом\nи холодным потом",
		"Rolling on the floor laughing": "Катаюсь по полу от смеха",
		"A face with tears of joy": "Лицо со слезами радости",
		"A slightly smiling face": "Слегка улыбающееся лицо",
		"The inverted face": "Перевернутое лицо",
		"The winking face": "Подмигивающее лицо",
		"A smiling face with smiling eyes": "Улыбающееся лицо\nс улыбающимися глазами",
		"A smiling face with a halo": "Улыбающееся лицо\nс нимбом",
		"A smiling face with smiling eyes and three hearts": "Улыбающееся лицо\nс улыбающимися глазами\nи тремя сердцами",
		"A smiling face with heart-shaped eyes": "Улыбающееся лицо\nс глазами в форме сердечек",
		"A grinning face with starry eyes": "Ухмыляющееся лицо\nсо звездными глазами",
		"The person sending the kiss": "Лицо, посылающее поцелуй",
		"The kissing face": "Целующее лицо",
		"A white smiling face": "Белое улыбающееся лицо",
		"Kissing a face with closed eyes": "Целующее лицо\nс закрытыми глазами",
		"A kissing face with smiling eyes": "Целующее лицо\nс улыбающимися глазами",
		"A person enjoying a delicious meal": "Лицо, наслаждающееся вкусной едой",
		"A face with a protruding tongue": "Лицо с высунутым языком",
		"A face with a protruding tongue and a winking eye": "Лицо с высунутым языком\nи подмигивающим глазом",
		"A grinning face with one big and one small eye": "Ухмыляющееся лицо\nс одним большим\nи одним маленьким глазом",
		"A face with a protruding tongue and tightly closed eyes": "Лицо с высунутым языком\nи плотно закрытыми глазами",
		"The face with the money mouth": "Лицо с денежным ртом",
		"The hugging face": "Обнимающее лицо",
		"A smiling face with smiling eyes and a hand covering his mouth": "Улыбающееся лицо\nс улыбающимися глазами\nи рукой, закрывающей рот",
		"A face with closed lips, covered with a finger": "Лицо с закрытыми губами,\nприкрытыми пальцем",
		"The thinking face": "Думающее лицо",
		"A face with a zipper": "Лицо с застежкой-молнией",
		"A face with a raised eyebrow": "Лицо с поднятой бровью",
		"A neutral person": "Нейтральное лицо",
		"A face without expression": "Лицо без выражения",
		"A face without a mouth": "Лицо без рта",
		"A sad face": "Невеселое лицо",
		"A face with rolled eyes": "Лицо с закатанными глазами",
		"The grimacing face": "Гримасничающее лицо",
		"A lying face": "Лживое лицо",
		"A relieved face": "Лицо с облегчением",
		"A thoughtful face": "Задумчивое лицо",
		"Sleepy face": "Сонное лицо",
		"Slobbery face": "Слюнявое лицо",
		"The sleeping face": "Спящее лицо",
		"A face with a medical mask": "Лицо с медицинской маской",
		"A face with a thermometer": "Лицо с термометром",
		"A face with a headband": "Лицо с повязкой на голове",
		"Sickening face": "Тошнотворное лицо",
		"Face with open mouth, vomiting": "Лицо с открытым ртом, рвота",
		"Sneezing face": "Чихающее лицо",
		"Overheated face": "Перегретое лицо",
		"The freezing face": "Замораживающее лицо",
		"A face with uneven eyes and a wavy mouth": "Лицо с неровными глазами\nи волнистым ртом",
		"The dizzying face": "Головокружительное лицо",
		"A shocked face with an exploding head": "Шокированное лицо\nсо взрывающейся головой",
		"The face in the cowboy hat": "Лицо в ковбойской шляпе",
		"A face with a festive horn and a festive hat": "Лицо с праздничным рожком\nи праздничной шляпой",
		"Smiling face in sunglasses": "Улыбающееся лицо\nв солнцезащитных очках",
		"Nerd's face": "Лицо задрота",
		"Face with a monocle": "Лицо с моноклем",
		"A confused face": "Смущенное лицо",
		"A worried face": "Обеспокоенное лицо",
		"A slightly frowning face": "Слегка нахмуренное лицо",
		"A frowning face": "Хмурое лицо",
		"A face with an open mouth": "Лицо с открытым ртом",
		"The silent face": "Молчаливое лицо",
		"The surprised face": "Удивленное лицо",
		"Reddened face": "Покрасневшее лицо",
		"A face with pleading eyes": "Лицо с умоляющими глазами",
		"A frowning face with an open mouth": "Нахмуренное лицо с открытым ртом",
		"The suffering face": "Страдающее лицо",
		"A scared face": "Испуганное лицо",
		"A face with an open mouth and cold sweat": "Лицо с открытым ртом и холодным потом",
		"A disappointed but relieved face": "Разочарованное, но облегченное лицо",
		"The crying face": "Плачущее лицо",
		"A crying face": "Громко плачущее лицо",
		"The face screams with fear": "Лицо кричит от страха",
		"An insistent face": "Настойчивое лицо",
		"The disappointed face": "Разочарованное лицо",
		"My face is covered in cold sweat": "Лицо в холодном поту",
		"Tired face": "Усталое лицо",
		"A face with an expression of triumph": "Лицо с выражением триумфа",
		"Pouty face": "Надутое лицо",
		"Angry face": "Сердитое лицо",
		"A serious face with symbols covering its mouth": "Серьёзное лицо с символами\nзакрывающими рот",
		"A smiling face with horns": "Улыбающееся лицо с рогами",
		"The little devil": "Чертенок",
		"Skull": "Череп",
		"Skull and Crossbones": "Череп и скрещенные кости",
		"A bunch of poop": "Куча какашек",
		"The clown's face": "Лицо клоуна",
		"The Japanese Ogre": "Японский огр",
		"The Japanese Goblin": "Японский гоблин",
		"Ghost": "Призрак",
		"The extraterrestrial alien": "Внеземной пришелец",
		"The alien monster": "Чужой монстр",
		"The robot's face": "Лицо робота",
		"Smiling cat face with open mouth": "Улыбающееся кошачье лицо\nс открытым ртом",
		"The grinning face of a cat with smiling eyes": "Ухмыляющаяся морда кошки\nс улыбающимися глазами",
		"A cat's face with tears of joy": "Кошачья морда\nсо слезами радости",
		"Smiling cat face with heart-shaped eyes": "Улыбающаяся мордашка кота\nс глазами в форме сердечек",
		"A cat's face with a crooked smile": "Кошачья морда\nс кривой улыбкой",
		"Kissing a cat's face with its eyes closed": "Целующая мордашка кошки\nс закрытыми глазами",
		"Tired cat face": "Усталое кошачье лицо",
		"The crying face of a cat": "Плачущая морда кошки",
		"The pouting face of a cat": "Надутая морда кошки",
		"The monkey who sees no evil": "Обезьяна, не видящая зла",
		"The monkey who hears no evil": "Обезьяна, не слышащая зла",
		"A monkey who doesn't speak evil": "Обезьяна, не говорящая зла",
		// Эмоции
		"A kiss": "Поцелуй",
		"A love letter": "Любовное письмо",
		"A heart with an arrow": "Сердце со стрелой",
		"Heart with ribbon": "Сердце с лентой",
		"The Sparkling Heart": "Сверкающее Сердце",
		"The growing heart": "Растущее сердце",
		"A Beating Heart": "Бьющееся Сердце",
		"Spinning Hearts": "Вращающиеся сердца",
		"Two Hearts": "Два Сердца",
		"Heart-shaped decoration": "Украшение в виде сердца",
		"A heart with an exclamation mark": "Cердце с восклицательным знаком",
		"A Broken Heart": "Разбитое Сердце",
		"Heart": "Сердце",
		"The Orange Heart": "Оранжевое Сердце",
		"The Yellow Heart": "Жёлтое Сердце",
		"The Green Heart": "Зелёное Сердце",
		"The Blue Heart": "Синее Сердце",
		"Purple Heart": "Фиолетовое Сердце",
		"The Black Heart": "Чёрное Сердце",
		"The symbol is 100 points": "Символ 100 очков",
		"The symbol of anger": "Символ гнева",
		"Collision symbol": "Символ столкновения",
		"The symbol of vertigo": "Символ головокружения",
		"The sweat spray symbol": "Символ брызг пота",
		"The Wind symbol": "Символ Ветер",
		"Hole": "Дыра",
		"Bomb": "Бомба",
		"A callout with a speech": "Выноска с речью",
		"The left speech bubble": "Левый речевой пузырь",
		"The right anger bubble": "Правильный пузырь гнева",
		"The Thought ball": "Мыслительный шар",
		"The Sleeping Symbol": "Спящий Символ",
		// Люди
		"Waving hand": "Машущая рука",
		"The raised back of the hand": "Поднятая тыльная сторона руки",
		"A raised hand with outstretched fingers": "Поднятая рука с растопыренными пальцами",
		"Raised hand": "Поднятая рука",
		"A raised hand with a parting between the middle and ring fingers": "Поднятая рука с пробором между средним\nи безымянным пальцами",
		"The \"OK\" hand sign": "Знак рукой «ОК»",
		"\"Victory\" hand sign": "Знак рукой «Победа»",
		"The hand with the index and middle fingers crossed": "Рука со скрещенными указательным\nи средним пальцами",
		"I love you hand gesture": "Я люблю тебя жест рукой",
		"The Sign of Horns": "Знак Рогов",
		"Hand sign \"Call me\"": "Знак рукой «Позвони мне»",
		"Back of the hand Index finger to the left": "Тыльная сторона руки\nУказательный палец влево",
		"Back of the hand Index finger to the right": "Тыльная сторона руки\nУказательный палец вправо",
		"Back of the hand Index finger up": "Тыльная сторона руки\nУказательный палец вверх",
		"The back of the hand with the middle finger extended": "Тыльная сторона руки\nс вытянутым средним пальцем",
		"Back of the hand, index finger down": "Тыльная сторона руки\nУказательный палец вниз",
		"Index finger up": "Указательный палец вверх",
		"Thumbs up": "Большой палец вверх",
		"Thumbs down": "Большой палец вниз",
		"Raised fist": "Поднятый кулак",
		"The sign of a clenched fist": "Знак сжатой в кулак руки",
		"Left-facing fist": "Кулак, обращенный влево",
		"Fist facing right": "Кулак, обращенный вправо",
		"The sign of clapping hands": "Знак хлопающих рук",
		"A man who raised both hands in celebration": "Человек, поднявший обе руки в знак празднования",
		"The \"Open Hands\" sign": "Знак «Открытые руки»",
		"Palms up together": "Ладони вверх вместе",
		"Handshake": "Рукопожатие",
		"A man with folded arms": "Человек со сложенными руками",
		"The writing hand": "Пишущая рука",
		"Manicure, Nail polish": "Маникюр, Лак для ногтей",
		"Selfie": "Селфи",
		"Bent biceps": "Согнутые бицепсы",
		"Leg": "Нога",
		"Foot": "Ступня",
		"Ear": "Ухо",
		"Nose": "Нос",
		"Brain": "Мозг",
		"Tooth": "Зуб",
		"Bone": "Кость",
		"Eyes": "Глаза",
		"Eye": "Глаз",
		"Tongue": "Язык",
		"Mouth": "Рот",
		"Baby": "Младенец",
		"Child": "Ребёнок",
		"Boy": "Мальчик",
		"Girl": "Девочка",
		"Adult": "Взрослый",
		"The man with the blond hair": "Человек со светлыми волосами",
		"Man": "Мужчина",
		"The Bearded Man": "Бородатый Человек",
		"Woman": "Женщина",
		"An older adult": "Пожилой взрослый",
		"An elderly man": "Пожилой мужчина",
		"An elderly woman": "Пожилая женщина",
		"The man frowns": "Человек хмурится",
		"The man with the pouty face": "Человек с надутым лицом",
		"A face without a good gesture": "Лицо без хорошего жеста",
		"The face with the \"OK\" gesture": "Лицо с жестом «ОК»",
		"Information Bureau employee": "Сотрудник информационного бюро",
		"The lucky man who raised one hand": "Счастливый человек, поднявший одну руку",
		"A man bowing low": "Человек, низко кланяющийся",
		"Face Palm": "Лицо Ладонь",
		"The shrug of the shoulders": "Пожимание плечами",
		"Policeman": "Полицейский",
		"Detective or spy": "Детектив или шпион",
		"The Guardsman": "Гвардеец",
		"Construction worker": "Строительный рабочий",
		"Prince": "Принц",
		"Princess": "Принцесса",
		"The man in the turban": "Мужчина в тюрбане",
		"The man with Gua Pi Mao": "Мужчина с Гуа Пи Мао",
		"The man in the headscarf": "Человек в платке",
		"The man in the tuxedo": "Мужчина в смокинге",
		"The bride with a veil": "Невеста с вуалью",
		"Pregnant Woman": "Беременная Женщина",
		"Breastfeeding": "Кормление грудью",
		"Baby angel": "Малыш-ангелочек",
		"Father Christmas": "Дед Мороз",
		"Mother Christmas": "Мать Рождество",
		"The Super hero": "Супер-герой",
		"The Super villain": "Супер-злодей",
		"The Magician": "Маг",
		"Fairy": "Фея",
		"A vampire": "Вампир",
		"Merperson. Mermaid": "Мерперсон. Русалка",
		"Elf": "Эльф",
		"Gin": "Джин",
		"Zombie": "Зомби",
		"Facial massage": "Массаж лица",
		"A haircut": "Стрижка",
		"Pedestrian": "Пешеход",
		"Runner": "Бегун",
		"Dancer": "Танцор",
		"The man is dancing": "Мужчина танцует",
		"A man in a business suit levitates": "Мужчина в деловом костюме левитирует",
		"The woman with the rabbit ears": "Женщина с кроличьими ушками",
		"The man in the steam room": "Человек в парной",
		"The rising Man": "Человек поднимающийся",
		"The Swordsman": "Фехтовальщик",
		"Horse racing": "Скачки",
		"Skier": "Лыжник",
		"The snowboarder": "Сноубордист",
		"The golfer": "Игрок в гольф",
		"The Surfer": "Серфер",
		"Rowing boat": "Весельная лодка",
		"Swimmer": "Пловец",
		"The man with the ball": "Человек с мячом",
		"Weightlifter": "Тяжелоатлет",
		"Bicyclist": "Велосипедист",
		"Mountain biker": "Горный велосипедист",
		"The man making the wheel": "Человек, делающий колесо",
		"The wrestlers": "Борцы",
		"Water polo": "Водное поло",
		"Handball": "Гандбол",
		"Juggling": "Жонглирование",
		"The man in the lotus position": "Человек в позе лотоса",
		"Bath": "Ванна",
		"Accommodation in sleeping places": "Размещение в спальных местах",
		"Two women holding hands": "Две женщины держатся за руки",
		"A man and a woman holding hands": "Мужчина и женщина держатся за руки",
		"Two men holding hands": "Двое мужчин держатся за руки",
		"Kisses": "Поцелуи",
		"A couple with a heart": "Пара с сердцем",
		"Family": "Семья",
		"Talking head in silhouette": "Говорящая голова в силуэте",
		"Bust in silhouette": "Бюст в силуэте",
		// Животные
		"Monkey face": "Обезьянье лицо",
		"A monkey": "Обезьяна",
		"Gorilla": "Горилла",
		"The dog's face": "Лицо собаки",
		"Dog": "Собака",
		"The poodle": "Пудель",
		"The face of the wolf": "Лицо волка",
		"The fox's face": "Лицо лисы",
		"Raccoon's face": "Лицо енота",
		"The cat's face": "Лицо кота",
		"Cat": "Кот",
		"The Lion's Face": "Лицо льва",
		"Tiger's Face": "Лицо тигра",
		"Tiger": "Тигр",
		"Leopard": "Леопард",
		"The horse's face": "Лицо лошади",
		"Horse": "Лошадь",
		"The Unicorn's Face": "Лицо единорога",
		"Zebra's face": "Лицо зебры",
		"Deer": "Олень",
		"Cow's face": "Лицо коровы",
		"Bull": "Бык",
		"Water buffalo": "Водяной буйвол",
		"Cow": "Корова",
		"Piglet's face": "Лицо поросёнка",
		"The piglet": "Поросёнок",
		"The boar's face": "Лицо кабана",
		"Piglet's Nickel": "Пятак поросёнка",
		"Ram": "Баран",
		"Sheep": "Овца",
		"Goat": "Козел",
		"The one-humped camel": "Одногорбный верблюд",
		"The double-humped camel": "Двугорбый верблюд",
		"Lama": "Лама",
		"Giraffe's face": "Лицо жирафа",
		"Elephant": "Слон",
		"Rhinoceros": "Носорог",
		"Hippopotamus": "Бегемот",
		"The mouse's face": "Лицо мыши",
		"Mouse": "Мышь",
		"Rat": "Крыса",
		"Hamster's face": "Лицо хомяка",
		"The face of the hare": "Лицо зайца",
		"Hare": "Заяц",
		"The Chipmunk": "Бурундук",
		"The Hedgehog": "Ёж",
		"Bat": "Летучая мышь",
		"The face of the bear": "Лицо медведя",
		"Koala's face": "Лицо коалы",
		"Panda's Face": "Лицо панды",
		"Kangaroo": "Кенгуру",
		"Badger": "Барсук",
		"Paw prints": "Отпечатки лап",
		"Turkey": "Индейка",
		"Chicken": "Цыпленок",
		"Cock": "Петух",
		"The hatching chick": "Вылупляющийся цыпленок",
		"The chicken looking forward": "Цыпленок, смотрящий вперед",
		"Bird": "Птица",
		"Penguin": "Пингвин",
		"The Dove of Peace": "Голубь мира",
		"Eagle": "Орел",
		"Duck": "Утка",
		"Swan": "Лебедь",
		"Owl": "Сова",
		"Peacock": "Павлин",
		"Parrot": "Попугай",
		"The frog's face": "Лицо лягушки",
		"Crocodile": "Крокодил",
		"Turtle": "Черепаха",
		"Lizard": "Ящерица",
		"Snake": "Змея",
		"The Dragon's Face": "Лицо дракона",
		"Dragon": "Дракон",
		"Sauropod": "Завропод",
		"T-Rex": "Ти-Рекс",
		"The Splashing Whale": "Брызгающий кит",
		"Whale": "Кит",
		"Dolphin": "Дельфин",
		"Fish": "Рыба",
		"Tropical fish": "Тропическая рыба",
		"Needle Fish": "Игольчатая рыба",
		"Shark": "Акула",
		"Octopus": "Осьминог",
		"Spiral Shell": "Спиральная ракушка",
		"Snail": "Улитка",
		"Butterfly": "Бабочка",
		"Caterpillar": "Гусеница",
		"Ant": "Муравей",
		"The honey bee": "Медоносная пчела",
		"Ladybug": "Божья коровка",
		"The cricket": "Сверчёк",
		"Spider": "Паук",
		"Web": "Паутина",
		"Scorpio": "Скорпион",
		"Mosquito": "Комар",
		"The microbe": "Микроб",
		// Природа
		"Bouquet": "Букет",
		"Cherry blossoms": "Цветущая вишня",
		"The White Flower": "Белый Цветок",
		"Rosette of leaves": "Розетка листьев",
		"Rose": "Роза",
		"A faded flower": "Увядший цветок",
		"Hibiscus": "Гибискус",
		"Sunflower": "Подсолнух",
		"Tulip": "Тюльпан",
		"Seedlings": "Рассада",
		"The evergreen tree": "Вечнозеленое дерево",
		"Deciduous tree": "Лиственное дерево",
		"Palm tree": "Пальма",
		"Cactus": "Кактус",
		"Rice": "Рис",
		"Grass": "Трава",
		"The Shamrock": "Трилистник",
		"Four-leaf clover": "Четырехлистный клевер",
		"Maple Leaf": "Кленовый лист",
		"The fallen leaf": "Опавший лист",
		"A leaf flutters in the wind": "Лист трепещет на ветру",
		// Еда и Напитки
		"Grape": "Виноград",
		"Melon": "Дыня",
		"Watermelon": "Арбуз",
		"Mandarin": "Мандарин",
		"Lemon": "Лимон",
		"Banana": "Банан",
		"Pineapple": "Ананас",
		"Mango": "Манго",
		"Red Apple": "Красное яблоко",
		"The green Apple": "Зелёное яблоко",
		"Pear": "Груша",
		"Peach": "Персик",
		"Cherry": "Вишня",
		"Strawberry": "Клубника",
		"Kiwi": "Киви",
		"Tomato": "Помидор",
		"Kakos": "Какос",
		"Avocado": "Авокадо",
		"Eggplant": "Баклажан",
		"Potato": "Картофель",
		"Markovka": "Марковка",
		"Corn": "Кукуруза",
		"Hot pepper": "Острый перец",
		"Cucumber": "Огурец",
		"Leafy greens": "Листовая зелень",
		"Broccoli": "Брокколи",
		"Fly agaric": "Мухомор",
		"Peanut": "Арахис",
		"Chestnut": "Каштан",
		"Bread": "Хлеб",
		"Croissant": "Круассан",
		"Baguette bread": "Багетный хлеб",
		"Pretzel": "Крендель",
		"Bagel": "Бублик",
		"Pancakes": "Блины",
		"Cheese wedge": "Сырный клин",
		"Meat on the bone": "Мясо на кости",
		"Bird's foot": "Ножка птицы",
		"A piece of meat": "Кусок мяса",
		"Bacon": "Бекон",
		"Hamburger": "Гамбургер",
		"French fries": "Картофель фри",
		"A slice of pizza": "Кусок пиццы",
		"Hot dog": "Хот-дог",
		"Sandwich": "Сэндвич",
		"Tacos": "Тако",
		"Burrito": "Буррито",
		"Tortilla with filling": "Лепешка с начинкой",
		"Egg": "Яйцо",
		"Scrambled eggs": "Яишница",
		"A shallow pot of food": "Неглубокая кастрюля с едой",
		"A pot of food": "Горшок с едой",
		"A bowl with a spoon": "Миска с ложкой",
		"Green salad": "Зеленый салат",
		"Popcorn": "Попкорн",
		"The salt shaker": "Солонка",
		"Preserves": "Консервы",
		"Container": "Контейнер",
		"Rice Cracker": "Рисовый крекер",
		"Rice ball": "Рисовый шарик",
		"Boiled rice": "Вареный рис",
		"Curry and rice": "Карри и рис",
		"Steaming bowl": "Миска для варки на пару",
		"Spaghetti": "Спагетти",
		"Fried sweet potatoes": "Жареный батат",
		"Dressed": "Оден",
		"Sushi": "Суши",
		"Fried shrimp": "Жареные креветки",
		"Fish pie with curls": "Рыбный пирог с завитками",
		"Mooncake": "Лунный пирог",
		"Dango": "Данго",
		"Cheburek": "Чебурек",
		"Fortune Cookies": "Печенье с предсказанием",
		"Takeaway Food Box": "Коробка для еды на вынос",
		"The crab": "Краб",
		"Lobster": "Лобстер",
		"Shrimp": "Креветка",
		"Squid": "Кальмар",
		"Soft ice cream": "Мягкое мороженое",
		"Planed ice": "Строганный лед",
		"Ice cream": "Мороженое",
		"Donut": "Пончик",
		"Cookie": "Печенье",
		"Birthday cake": "Торт на день рождения",
		"Shortbread cookies": "Песочное печенье",
		"Cupcake": "Кекс",
		"Pie": "Пирог",
		"Chocolate bar": "Плитка шоколада",
		"Candies": "Конфеты",
		"Candy": "Леденец",
		"Custard cream": "Заварной крем",
		"Honey": "Мед",
		"Baby bottle": "Детская бутылочка",
		"A Glass of Milk": "Стакан Молока",
		"Hot drink": "Горячий напиток",
		"Cup without handle": "Чашка без ручки",
		"Sake bottle and cup": "Бутылка и чашка для сакэ",
		"Champagne": "Шампанское",
		"A glass of wine": "Бокал вина",
		"A glass of cocktail": "Бокал коктейля",
		"Tropical drink": "Тропический напиток",
		"A mug of beer": "Кружка пива",
		"The clink of beer mugs": "Звон пивных кружек",
		"The clink of glasses": "Звон бокалов",
		"Glass": "Стакан",
		"A cup with a straw": "Чашка с соломинкой",
		"Chopsticks": "Палочки для еды",
		"Fork and knife with plate": "Вилка и нож с тарелкой",
		"Fork and knife": "Вилка и нож",
		"Spoon": "Ложка",
		"Knife": "Нож",
		"The Amphora": "Амфора",
		// Места и Путешествия
		"Globe Europe-Africa": "Земной шар Европа-Африка",
		"The Globe of America": "Земной шар Америка",
		"Globe Asia-Australia": "Земной шар Азия-Австралия",
		"A globe with meridians": "Глобус с меридианами",
		"World map": "Карта мира",
		"Japanese Islands": "Японские острова",
		"Compass": "Компас",
		"The snow-capped mountain": "Заснеженная гора",
		"Mountain": "Гора",
		"Volcano": "Вулкан",
		"Mount Fuji": "Гора Фудзи",
		"Camping": "Кемпинг",
		"Beach with an umbrella": "Пляж с зонтиком",
		"Desert": "Пустыня",
		"An uninhabited island": "Необитаемый остров",
		"National Park": "Национальный парк",
		"Stadium": "Стадион",
		"A classic building": "Классическое здание",
		"Building construction": "Строительство зданий",
		"Bricks": "Кирпичи",
		"Home buildings": "Домашние постройки",
		"The abandoned building of the house": "Заброшенное здание дома",
		"Building a house": "Строительство дома",
		"House with garden": "Дом с садом",
		"Office building": "Офисное здание",
		"Japan Post": "Почта Японии",
		"European Post": "Европейская почта",
		"Hospital": "Больница",
		"Bank": "Банк",
		"Hotel": "Отель",
		"The Hotel of Love": "Отель Любви",
		"Shop near the house": "Магазин у дома",
		"School": "Школа",
		"Department Store": "Универмаг",
		"Factory": "Фабрика",
		"Japanese Castle": "Японский замок",
		"European Castle": "Европейский замок",
		"Registry office": "Загс",
		"Tokyo Tower": "Токийская башня",
		"statue of liberty": "Статуя Свободы",
		"Church": "Церковь",
		"Mosque": "Мечеть",
		"The Synagogue": "Синагога",
		"Shinto Shrine": "Синтоистское святилище",
		"The Kaaba": "Кааба",
		"Fountain": "Фонтан",
		"Tent": "Палатка",
		"Foggy": "Туманно",
		"A night with stars": "Ночь со звездами",
		"Urban landscape": "Городской пейзаж",
		"Sunrise over the mountains": "Восход солнца над горами",
		"Sunrise over the water": "Восход солнца над водой",
		"Urban landscape at dusk": "Городской пейзаж в сумерках",
		"Sunset over buildings": "Закат над зданиями",
		"The bridge at night": "Мост ночью",
		"Hot springs": "Горячие источники",
		"The Milky Way": "Млечный Путь",
		"The Carousel Horse": "Карусельная Лошадь",
		"Ferris wheel": "Колесо обозрения",
		"Roller Coaster": "Roller Coaster",
		"Barbershop": "Парикмахерская",
		"Circus tent": "Цирковой шатер",
		"Steam train": "Паровоз",
		"Railway carriage": "Железнодорожный вагон",
		"High-speed train": "Скоростной поезд",
		"Bullet-nosed Bullet Train": "Скоростной поезд с пулевидным носом",
		"Railway": "Железная дорога",
		"Metro": "Метро",
		"High-speed tram": "Скоростной трамвай",
		"Station": "Станция",
		"Tram": "Трамвай",
		"Monorail": "Монорельс",
		"Mountain Railway": "Горная железная дорога",
		"Tram car": "Трамвайный вагон",
		"Bus": "Автобус",
		"An approaching bus": "Приближающийся автобус",
		"Trolleybus": "Троллейбус",
		"Minibus": "Микроавтобус",
		"Ambulance": "Скорая помощь",
		"Fire truck": "Пожарная машина",
		"Police car": "Полицейская машина",
		"An approaching police car": "Приближающаяся полицейская машина",
		"Taxi": "Такси",
		"An approaching taxi": "Приближающееся такси",
		"Car": "Автомобиль",
		"An approaching car": "Приближающийся автомобиль",
		"A recreational vehicle": "Автомобиль для отдыха",
		"Delivery Truck": "Грузовик для доставки",
		"Articulated truck": "Сочлененный грузовик",
		"Tractor": "Трактор",
		"Racing car": "Гоночный автомобиль",
		"Racing Motorcycle": "Гоночный мотоцикл",
		"Scooter": "Самокат",
		"Bicycle": "Велосипед",
		"Skateboard": "Скейтборд",
		"Bus stop": "Автобусная остановка",
		"Motorway": "Автомагистраль",
		"Railway track": "Железнодорожный путь",
		"Oil barrel": "Бочка для масла",
		"Refill": "Заправка",
		"Police Car Beacons": "Маячёк Полицейской машины",
		"Horizontal traffic light": "Горизонтальный светофор",
		"Vertical traffic light": "Вертикальный светофор",
		"The octagonal sign": "Восьмиугольный знак",
		"Building sign": "Строительный знак",
		"Anchor": "Якорь",
		"Sailboat": "Парусник",
		"Kanoya": "Каноя",
		"High-speed boat": "Быстроходный катер",
		"Passenger ship": "Пассажирское судно",
		"Ferryboat": "Паром",
		"Motor boat": "Моторная лодка",
		"Ship": "Корабль",
		"Airplane": "Самолет",
		"A small plane": "Маленький самолет",
		"Flight departure": "Вылет самолета",
		"Arrival of the plane": "Прибытие самолета",
		"The seat": "Сиденье",
		"Helicopter": "Вертолет",
		"Overhead railway": "Подвесная железная дорога",
		"Mountain Cable Car": "Горная канатная дорога",
		"Cable car": "Канатная дорога",
		"Satellite": "Спутник",
		"Rocket": "Ракета",
		"Flying saucer": "Летающая тарелка",
		"Call": "Звонок",
		"Luggage": "Багаж",
		"The Hourglass": "Песочные часы",
		"Hourglass with loose sand": "Песочные часы с сыпучим песком",
		"Watch": "Наручные часы",
		"Alarm": "Будильник",
		"Stopwatch": "Секундомер",
		"Timer": "Таймер",
		"The clock on the mantelpiece": "Часы на каминной полке",
		"The dial is twelve o'clock": "Циферблат Двенадцать часов",
		"The dial is half past one": "Циферблат Половина второго",
		"The dial is One emergency": "Циферблат Один чс",
		"The dial is two o'clock": "Циферблат Два часа",
		"The dial is half past two": "Циферблат Половина третьего",
		"The dial is three o'clock": "Циферблат Три часа",
		"The dial is half past three": "Циферблат Половина четвёртого",
		"The dial is four o'clock": "Циферблат Четыре часа",
		"The dial is half past four": "Циферблат Половина пятого",
		"The dial is five o'clock": "Циферблат Пять часов",
		"The dial is half past five": "Циферблат Половина шестого",
		"The dial is six o'clock": "Циферблат Шесть часов",
		"The dial is half past six": "Циферблат Половина седьмого",
		"The dial is Seven o'clock": "Циферблат Семь часов",
		"The dial is half past seven": "Циферблат Половина восьмого",
		"The Dial Is Eight O'clock": "Циферблат Восемь Часов",
		"The dial is half past eight": "Циферблат Половина девятого",
		"The dial is Nine o'clock": "Циферблат Девять часов",
		"The dial is half past nine": "Циферблат Половина десятого",
		"The dial is Ten o'clock": "Циферблат Десять часов",
		"The dial is half past ten": "Циферблат Половина двеннадцатого",
		"The dial is eleven o'clock": "Циферблат Одиннадцать часов",
		"The symbol of the new moon": "Символ новолуния",
		"The symbol of the growing crescent moon": "Символ растущей полумесяца",
		"The symbol of the first quarter of the Moon": "Символ первой четверти Луны",
		"The symbol of the waxing Moon": "Символ растущей Луны",
		"The Symbol of the Full Moon": "Символ Полной Луны",
		"The symbol of the waning Moon": "Символ убывающей Луны",
		"The symbol of the last quarter of the moon": "Символ последней четверти Луны",
		"The symbol of the waning crescent": "Символ убывающей полумесяца",
		"The Crescent Moon": "Полумесяц",
		"A new moon with a face": "Новолуние с лицом",
		"The first quarter of the moon with a face": "Первая четверть Луны с лицом",
		"The last quarter of the Moon with a face": "Последняя четверть Луны с лицом",
		"Thermometer": "Термометр",
		"The Sun With Rays": "Солнце С Лучами",
		"Full Moon With A Face": "Полная Луна С Лицом",
		"The sun with a face": "Солнце с лицом",
		"The white middle Star": "Белая средняя звезда",
		"A Glowing Star": "Светящаяся Звезда",
		"Shooting Star": "Падающая звезда",
		"Cloud": "Облако",
		"The sun behind the cloud": "Солнце за облаком",
		"Thundercloud and rain": "Грозовая туча и дождь",
		"A White Sun with a Small Cloud": "Белое Солнце с Маленьким Облаком",
		"White Sun Behind A Cloud": "Белое Солнце За Облаком",
		"White sun behind a cloud with rain": "Белое солнце за облаком с дождем",
		"A cloud with rain": "Облако с дождем",
		"A cloud with snow": "Облако со снегом",
		"A cloud with lightning": "Облако с молнией",
		"Tornado cloud": "Облако с торнадо",
		"Fog": "Туман",
		"A face blown by the wind": "Лицо, обдуваемое ветром",
		"Cyclone": "Циклон",
		"Rainbow": "Радуга",
		"Closed umbrella": "Закрытый зонт",
		"Umbrella": "Зонтик",
		"Umbrella with raindrops": "Зонт с каплями дождя",
		"An umbrella on the ground": "Зонт на земле",
		"The high voltage sign": "Знак высокого напряжения",
		"Snowflake": "Снежинка",
		"Snowman": "Снеговик",
		"A snowman without snow": "Снеговик без снега",
		"The Comet": "Комета",
		"Fire": "Огонь",
		"A drop": "Капля",
		"Water wave": "Водяная волна",
		// Мероприятия и Праздники
		"Jack-o'-lanterns": "Джек-фонарь",
		"Christmas tree": "Новогодняя ёлка",
		"Fireworks display": "Феерверк",
		"Bengal fire": "Бенгальский огонь",
		"Firecracker": "Петарда",
		"Sparks": "Искры",
		"Air balloon": "Воздушный шар",
		"A party cracker": "Хлопушка для вечеринок",
		"A ball of confetti": "Шар конфетти",
		"The Tanabata Tree": "Дерево Танабата",
		"Pine ornaments": "Сосновые украшения",
		"Japanese dolls": "Японские куклы",
		"Carp Streamer": "Карповый стример",
		"Wind Music": "Музыка Ветра",
		"Moon Viewing Ceremony": "Церемония любования луной",
		"Red gift Envelope": "Красный подарочный конверт",
		"Tape": "Лента",
		"A packaged gift": "Упакованный подарок",
		"Reminder Feed": "Лента напоминаний",
		"Entrance fees": "Входные билеты",
		"Ticket": "Билет",
		"Military Medal": "Военная медаль",
		"Cup": "Кубок",
		"Sports medal": "Спортивная медаль",
		"Medal for the first place": "Медаль за первое место",
		"Medal for the second place": "Медаль за второе место",
		"Medal for the third place": "Медаль за третье место",
		"football": "Футбольный Мяч",
		"Baseball ball": "Бейсбольный мяч",
		"Softball ball": "Софтбольный мяч",
		"Basketball ball": "Баскетбольный мяч",
		"A volleyball ball": "Волейбольный мяч",
		"An American football ball": "Мяч для Американского футбола",
		"A Rugby ball": "Мяч для Регби",
		"Tennis racket and ball": "Тенисная ракетка и мяч",
		"The Flying Disc": "Летающий Диск",
		"Bowling": "Боулинг",
		"Cricket bat and ball": "Бита и мяч для крикета",
		"Field hockey stick and ball": "Клюшка и мяч для хоккея на траве",
		"Hockey stick and puck": "Хоккейная клюшка и шайба",
		"A club and a lacrosse ball": "Клюшка и мяч для лакросса",
		"Table tennis racket and ball": "Ракетка и мяч для настольного тенниса",
		"Badminton racket and shuttlecock": "Бадминтонная ракетка и волан",
		"Boxing glove": "Боксерская перчатка",
		"Martial Arts Uniforms": "Униформа для боевых искусств",
		"Paved gates": "Хоккеные ворота",
		"Golf Flags": "Флажёк в Гольфе",
		"Skates": "Коньки",
		"Fishing rod and fish": "Удочка и рыба",
		"Running T-shirt": "Футболка для бега",
		"Skis and ski boots": "Лыжи и лыжные ботинки",
		"Sleigh": "Сани",
		"Stone for curling": "Камень для керлинга",
		"Direct hit": "Прямое попадание",
		"Billiard": "Бильярд",
		"The Crystal Ball": "Хрустальный шар",
		"Nazar's Amulet": "Амулет Назара",
		"Video game": "Видеоигра",
		"The joystick": "Джойстик",
		"Slot machine": "Игровой автомат",
		"The game cube": "Игровой кубик",
		"A piece of the puzzle": "Кусочек пазла",
		"Teddy bear": "Плюшевый мишка",
		"The Suit of Spades": "Масть Пики",
		"Suit of Hearts": "Масть Черви",
		"The Bubi Suit": "Масть Буби",
		"The suit of the Cross": "Масть Крести",
		"The Black pawn": "Чёрная пешка",
		"The Joker Playing card": "Игральная карта Джокер",
		"Mahjong Tile Red Dragon": "Плитка маджонга Красный дракон",
		"Floral Playing Cards": "Цветочные игральные карты",
		"Theatrical masks": "Театральные маски",
		"Framed painting": "Картина в рамке",
		"The artist's palette": "Палитра художника",
		"A Spool of Thread": "Катушка Ниток",
		"A ball of yarn": "Клубок пряжи",
		"Uh-huh": "Ё-ё",
		"Kite": "Воздушный змей",
		"Skydiver": "Парашутист",
		"The Boomerang": "Бумеранг",
		"The magic wand": "Волшебная палочка",
		"Pinata": "Пиньята",
		"Matryoshka dolls": "Матрешки",
		// Объекты и Вещи
		"Glasses": "Очки",
		"Black glasses": "Чёрные очки",
		"Scuba Diver's Mask": "Маска аквалангиста",
		"Laboratory (doctor's) coat": "Лабораторный (докторский) халат",
		"Tie": "Галстук",
		"T-shirt": "Футболка",
		"Jeans": "Джинсы",
		"Scarf": "Шарф",
		"Gloves": "Перчатки",
		"Coat": "Пальто",
		"Socks": "Носки",
		"Dress": "Платье",
		"Kimano": "Кимано",
		"Bikini (swimsuit)": "Бикини (купальник)",
		"Women's bathrobe": "Женский халат",
		"Wallet": "Кошелёк",
		"Handbag": "Сумочка",
		"The pouch": "Мешочек",
		"Shopping Bags": "Пакеты для покупок",
		"School backpack": "Школтный рюкзак",
		"Men's shoes": "Мужская обувь",
		"Sports shoes": "Спортивная обувь",
		"Hiking boots": "Походные ботинки",
		"Women's Flat Shoes": "Женская обувь\nна плоской подошве",
		"High-heeled shoes": "Туфли\nна высоком каблуке",
		"Women's Sandals": "Женские сандалии",
		"Women's boots": "Женские сапоги",
		"Crown": "Корона",
		"Women's Panama": "Женская панама",
		"Top hat (male)": "Цилиндр (мужской)",
		"Graduate's hat": "Шапочка выпускника",
		"Baseball cap": "Бейсболка",
		"Helmet with a white cross": "Шлем с белым крестом",
		"Prayer beads": "Четки для молитвы",
		"Lipstick (sponge)": "Помада (губнушка)",
		"Ring": "Кольцо",
		"A precious stone": "Драгоценный камень",
		"Sound is prohibited": "Звук запрещён",
		"The speaker is off": "Динамик выключен",
		"Speaker at minimum volume": "Динамик на минимальной громкости",
		"Speaker at maximum volume": "Динамик на максимальной громкости",
		"Speaker for notification": "Громкоговоритель для оповещения",
		"Megafon": "Мегафон",
		"Postal Horn": "Почтовый Рог",
		"Bell": "Колокол",
		"The bell is forbidden": "Колокол запрещён",
		"Musical score": "Музыкальная партитура",
		"Musical note": "Музыкальная нота",
		"Musical notes": "Музыкальные ноты",
		"Studio Microphone": "Студийный микрофон",
		"Slider control": "Регулятор слайдер",
		"Control knobs": "Ручки управления",
		"Microphone": "Микрофон",
		"Headphones": "Наушники",
		"Radio": "Радио",
		"The saxophone": "Саксафон",
		"Guitar": "Гитара",
		"Musical keyboard": "Музыкальная клавиатура",
		"Musical Trumpet": "Музыкальная Труба",
		"Violin": "Скрипка",
		"A drum with drumsticks": "Барабан с барабанными палочками",
		"Mobile phone": "Мобильный телефон",
		"Mobile phone receiving a call": "Мобильный телефон приём звонка",
		"Disk Phone Number": "Дисковый Телефон",
		"The handset": "Телефонная трубка",
		"The pager": "Пейджер",
		"Fax number": "Факс",
		"Battery": "Батарейка",
		"Electric plug": "Электрическая вилка",
		"A laptop": "Ноутбук",
		"Computer": "Компьютер",
		"Printer": "Принтер",
		"Keyboard": "Клавиатура",
		"Three-button mouse": "Трехкнопочная мышь",
		"Trackball": "Трекбол",
		"Minidisc": "Минидиск",
		"3.5\" Floppy Disk 1.44Mb": "Дискета 3.5\" 1,44Мб",
		"Optical Disc CD": "Оптический Диск CD",
		"Optical Disc DVD": "Оптический Диск DVD",
		"Accounts": "Счеты",
		"Movie Camera": "Кинокамера",
		"The movie": "Кинолента",
		"Filmoscope (projector)": "Фильмоскоп (проектор)",
		"The movie Cracker": "Кинохлопушка",
		"TV": "Телевизор",
		"The camera": "Фотокамера",
		"Camera with flash light": "Фотокамера с фотовспышкой",
		"Video camera": "Видео камера",
		"Video tape": "Видеокассета",
		"Healing glass with a stream on the left": "Увелечительное стекло\nс ручеой слева",
		"Healing glass with a stream on the right": "Увелечительное стекло\nс ручеой справа",
		"A Burning Candle": "Горящая Свеча",
		"Electric light bulb": "Электрическая лампочка",
		"Electric flashlight": "Электрический фонарик",
		"The red lantern": "Крассный фонарь",
		"A notebook with a decorative cover": "Блокнот с декоративной обложкой",
		"The Closed book": "Закрытая книга",
		"An open book": "Открытая книга",
		"The Green Book": "Зелёная Книга",
		"The Blue Book": "Синяя книга",
		"The Orange Book": "Оранжевая книга",
		"Books": "Книги",
		"Notepad": "Блокнот",
		"Accounting Book": "Бухгалтерская книга",
		"The Curl page": "Страница с завитком",
		"A page with swirls at the top and bottom": "Страница с завитками сверху и снизу",
		"The page is face up": "Страница лицевой стороной вверх",
		"Newspaper": "Газета",
		"A rolled-up newspaper": "Свернутая в трубочку газета",
		"Bookmarks Tabs": "Закладки Вкладки",
		"Bookmark": "Закладка",
		"Label": "Этикетка",
		"The money Bag": "Денежный мешок",
		"A banknote with a yen sign": "Банкнота со знаком иены",
		"A banknote with a dollar sign": "Банкнота со знаком доллара",
		"Banknote with the euro sign": "Банкнота со знаком евро",
		"A banknote with a pound sign": "Банкнота со знаком фунта",
		"Money with wings": "Деньги с крыльями",
		"Credit card": "Кредитная карта",
		"Receipt": "Квитанция",
		"Chart with an uptrend and a yen sign": "График с восходящим трендом и знаком иены",
		"Currency exchange": "Обмен валюты",
		"Heavy Dollar sign": "Тяжелый знак доллара",
		"The envelope": "Конверт",
		"The email symbol": "Символ электронной почты",
		"Incoming envelope": "Входящий конверт",
		"An envelope with a downward arrow on top": "Конверт со стрелкой вниз сверху",
		"Outgoing Mail tray": "Лоток для исходящих писем",
		"Incoming Message tray": "Лоток для входящих сообщений",
		"Packaging": "Упаковка",
		"A closed mailbox with a raised flag": "Закрытый почтовый ящик с поднятым флагом",
		"A closed mailbox with a lowered flag": "Закрытый почтовый ящик с опущенным флагом",
		"An open mailbox with a raised flag": "Открытый почтовый ящик с поднятым флагом",
		"An open mailbox with the flag down": "Открытый почтовый ящик с опущенным флагом",
		"Mailbox": "Почтовый ящик",
		"The ballot box": "Урна для голосования с бюллетенем",
		"Pencil": "Карандаш",
		"Fountain Pen": "Перьевая ручка",
		"Lower left fountain pen": "Нижняя левая перьевая ручка",
		"Lower left ballpoint pen": "Нижняя левая шариковая ручка",
		"Lower left hand": "Нижняя левая кисть",
		"Lower left pencil": "Нижний левый карандаш",
		"The memo": "Памятка",
		"Briefcase": "Портфель",
		"Folder with files": "Папка с файлами",
		"An open folder with files": "Открытая Папка с файлами",
		"File dividers": "Разделители для картотеки",
		"Calendar": "Календарь",
		"Tear-off calendar": "Отрывной календарь",
		"Spiral Notebook": "Блокнот со спиралью",
		"Notepad calendar with spiral": "Блокнот-календарь со спиралью",
		"File cabinet": "Картотека",
		"An uptrend chart": "График с восходящим трендом",
		"A chart with a downtrend": "График с нисходящим трендом",
		"Bar chart": "Столбчатая диаграмма",
		"Clipboard": "Буфер обмена",
		"Button": "Кнопка",
		"Round button": "Круглая кнопка",
		"Paper clip": "Скрепка для бумаг",
		"Bound Paper Clips": "Связанные скрепки",
		"Ruler": "Линейка",
		"Triangular ruler": "Треугольная линейка",
		"Scissors": "Ножницы",
		"The filing cabinet box": "Коробка для картотеки",
		"File Cabinet": "Файловый шкаф",
		"The wastebasket": "Мусорная корзина",
		"Castle": "Замок",
		"An open castle": "Открытый замок",
		"Lock with ink pen": "Замок с чернильной ручкой",
		"A closed lock with a key": "Закрытый замок с ключом",
		"Key": "Ключ",
		"The old key": "Старый ключ",
		"A hammer": "Молоток",
		"Pickaxe": "Кирка",
		"Hammer and pickaxe": "Молоток и кирка",
		"Hammer and wrench": "Молоток и гаечный ключ",
		"Dagger-knife": "Кинжал-нож",
		"Crossed swords": "Скрещенные мечи",
		"Gun": "Пистолет",
		"Bow and arrows": "Лук и стрелы",
		"Shield": "Щит",
		"Wrench": "Гаечный ключ",
		"A bolt with a spike": "Болт с кайкой",
		"Mechanism": "Механизм",
		"Compression": "Сжатие",
		"Scales": "Весы",
		"The link symbol": "Символ ссылки",
		"Chains": "Цепи",
		"The toolbox": "Ящик для инструментов",
		"Magnet": "Магнит",
		"The alembic": "Перегонный куб",
		"Test tube": "Пробирка",
		"Petri Dish": "Чашка Петри",
		"The double helix of DNA": "Двойная спираль ДНК",
		"The microscope": "Микроскоп",
		"The telescope": "Телескоп",
		"Satellite dish": "Спутниковая антенна",
		"Syringe": "Шприц",
		"The pill": "Пилюля",
		"Door": "Дверь",
		"Bed": "Кровать",
		"Sofa and lamp": "Диван и лампа",
		"Toilet": "Унитаз",
		"Shower": "Душ",
		"Bath": "Ванна",
		"A bottle of lotion": "Флакон лосьона",
		"Safety Pin": "Английская булавка",
		"Broomstick": "Метла",
		"Basket": "Корзина",
		"A roll of paper": "Рулон бумаги",
		"A bar of soap": "Кусок мыла",
		"Sponge": "Губка",
		"Fire extinguisher": "Огнетушитель",
		"Shopping cart": "Тележка для покупок",
		"The symbol of smoking": "Символ курения",
		"Coffin": "Гроб",
		"Funeral urn": "Погребальная урна",
		"Moyai statue": "Мояи",
		// Символы
		"ATM machine": "Банкомат",
		"Remove the trash": "Уберите мусор",
		"Drinking water": "Питьевая вода",
		"Wheelchair": "Инвалидная коляска",
		"Symbol: Male": "Символ: Мужчина",
		"Symbol: A woman": "Символ: Женщина",
		"Toilet": "Туалет",
		"Symbol: Child": "Символ: Ребёнок",
		"The lavatory": "Уборная",
		"Passport control": "Паспортный контроль",
		"Customs": "Таможня",
		"Baggage claim": "Выдача багажа",
		"Luggage storage": "Камера хранения багажа",
		"The warning sign": "Предупреждающий знак",
		"Children's crossing": "Детский переход",
		"The forbidding sign": "Запрещающий знак",
		"No entry sign": "Знак «Вход воспрещен»",
		"Bicycles are prohibited": "Велосипеды запрещены",
		"Smoking is prohibited": "Курить запрещено",
		"Don't litter": "Не мусорить",
		"Non-potable water": "Непитьевая вода",
		"Pedestrian traffic is prohibited": "Движение пешеходов запрещено",
		"No cell phones": "Никаких мобильных телефонов",
		"Prohibited Under the age of eighteen": "Запрещено Младше восемнадцати",
		"Radiation hazard": "Радиационная опастность",
		"Biological hazards": "Биологичевкая опастность",
		"Black Arrow Up": "Черная Стрелка Вверх",
		"Northeast Arrow": "Северо-Восточная Стрелка",
		"Black arrow to the right": "Черная стрелка вправо",
		"Southeastern Arrow": "Юго-Восточная Стрелка",
		"The black arrow is down": "Черная стрелка вниз",
		"Southwest Arrow": "Юго-Западная Стрелка",
		"Black arrow to the left": "Черная стрелка влево",
		"North-Western Arrow": "Северо-Западная Стрелка",
		"Up-down arrow": "Стрелка вверх-вниз",
		"Left-right arrow": "Стрелка влево-вправо",
		"Left arrow with hook": "Стрелка влево с крючком",
		"Right arrow with hook": "Стрелка вправо с крючком",
		"An arrow pointing to the right, then curving upward": "Стрелка, направленная вправо,\nзатем изгибающаяся вверх",
		"An arrow pointing to the right, then curving downwards": "Стрелка, направленная вправо,\nзатем изгибающаяся вниз",
		"Open circular arrows pointing up and down clockwise": "Открытые круговые стрелки,\nнаправленные вверх и вниз\nпо часовой стрелке",
		"Open circular arrows pointing up and down counterclockwise": "Открытые круговые стрелки,\nнаправленные вверх и вниз\nпротив часовой стрелке",
		"Back with the left arrow on top": "Назад со стрелкой влево сверху",
		"Finish with the left arrow on top": "Завершить со стрелкой влево сверху",
		"With an exclamation mark and a left-right arrow on top": "С восклицательным знаком\nи стрелкой влево-вправо сверху",
		"Soon with the arrow to the right at the top": "Скоро\nсо стрелкой вправо вверху",
		"Up with the up arrow at the top": "Вверх\nсо стрелкой вверх вверху",
		"A place of worship": "Место поклонения",
		"The symbol of the Atom": "Символ Атома",
		"The Om symbol": "Символ Ом",
		"The Star of David": "Звезда Давида",
		"The Wheel of Dharma": "Колесо Дхармы",
		"Yin Yang": "Инь Ян",
		"The Latin Cross": "Латинский крест",
		"The Orthodox Cross": "Православный крест",
		"The star and the crescent moon": "Звезда и полумесяц",
		"A symbol of peace": "Символ мира",
		"Menorah with nine branches": "Менора с девятью ветвями",
		"A six-pointed star with a dot in the middle": "Шестиконечная звезда с точкой посередине",
		"Aries": "Овен",
		"Taurus": "Телец",
		"Twins": "Близнецы",
		"Cancer": "Рак",
		"Leo": "Лев",
		"Maid": "Дева",
		"Scales": "Весы",
		"Scorpio": "Скорпион",
		"Sagittarius": "Стрелец",
		"Capricorn": "Козерог",
		"Aquarius": "Водолей",
		"Fish": "Рыбы",
		"The Ophiuchus": "Змееносец",
		"Twisted arrows pointing to the right": "Скрученные стрелки,\nнаправленные вправо",
		"Round arrows pointing clockwise to the right and left": "Круглые стрелки,\nнаправленные вправо и влево по часовой стрелке",
		"Round arrows pointing clockwise to the right and left, with a unit superimposed in a circle": "Круглые стрелки,\nнаправленные по часовой стрелке вправо и влево,\nс наложением еденицы в кружке",
		"A triangle pointing to the right": "Треугольник,\nнаправленный вправо",
		"A double triangle pointing to the right": "Двойной треугольник,\nнаправленный вправо",
		"A double triangle pointing to the right, with a vertical line": "Двойной треугольник,\nнаправленный вправо,\nс вертикальной чертой",
		"A triangle pointing to the right with a double vertical line": "Треугольник,\nнаправленный вправо,\nс двойной вертикальной чертой",
		"A triangle pointing to the left": "Треугольник,\nнаправленный влево",
		"A double triangle pointing to the left": "Двойной треугольник,\nнаправленный влево",
		"A double triangle pointing to the left, with a vertical line": "Двойной треугольник,\nнаправленный влево,\nс вертикальной чертой",
		"The triangle is upside down": "Треугольник вершиной вниз",
		"Double triangle with the top facing up": "Двойной треугольник вершиной вверх",
		"Double triangle with the top facing down": "Двойной треугольник вершиной вниз",
		"Double vertical stripe": "Двойная вертикальная полоса",
		"The stop square": "Квадрат остановки",
		"The recording circle": "Круг записи",
		"Extraction symbol": "Символ извлечения",
		"Movie": "Кино",
		"Low brightness symbol": "Символ низкой яркости",
		"High brightness symbol": "Символ высокой яркости",
		"Antenna with a grid": "Антенна с решеткой",
		"Vibration mode": "Режим вибрации",
		"The mobile phone is turned off": "Мобильный телефон выключен",
		"Female sign": "Женский знак",
		"The male sign": "Мужской знак",
		"The staff of Aesculapius": "Посох Эскулапа",
		"Permanent paper sign": "Постоянный бумажный знак",
		"Symbol of recycling": "Символ переработки",
		"Lily Flower": "Цветок лилии",
		"The Trident Emblem": "Эмблема трезубца",
		"Name badge": "Бейдж с именем",
		"Japanese symbol for beginners": "Японский символ для начинающих",
		"Heavy big circle": "Тяжелый большой круг",
		"White bold checkmark": "Белая жирная галочка",
		"Ballot box with verification": "Урна для голосования с проверкой",
		"Heavy check mark": "Тяжелая галочка",
		"Heavy X multiplication": "Тяжелое умножение X",
		"Mark the Cross": "Крест Марк",
		"Negative square cross": "Отрицательный квадратный крестик",
		"Heavy plus sign": "Тяжелый знак плюса",
		"Heavy minus sign": "Тяжелый знак минус",
		"The sign of heavy division": "Знак тяжелого деления",
		"The Winding Loop": "Вьющаяся петля",
		"Double Curly loop": "Двойная вьющаяся петля",
		"The sign of alternating parts": "Знак чередования частей",
		"The eight-pointed star": "Восьмиконечная звездочка",
		"Eight-pointed black star": "Восьмиконечная черная звезда",
		"Spark": "Искра",
		"Double exclamation mark": "Двойной восклицательный знак",
		"The exclamation mark of the question": "Восклицательный знак вопроса",
		"Black question mark": "Черный вопросительный знак",
		"A white question mark": "Белый вопросительный знак",
		"White exclamation mark": "Белый восклицательный знак",
		"The bold exclamation mark symbol": "Символ жирного восклицательного знака",
		"The wavy line": "Волнистая черта",
		"Copyright mark": "Знак авторского права",
		"Registered mark": "Зарегистрированный знак",
		"Trademark": "Товарный знак",
		"The grid sign": "Знак решётки",
		"The footnote": "Сноска",
		"The zero sign": "Нулевой знак",
		"The unity sign": "Знак еденица",
		"The deuce sign": "Знак двойка",
		"The troika sign": "Знак тройка",
		"The four sign": "Знак четвёрка",
		"The five sign": "Знак пятёрка",
		"The sign of the six": "Знак шестёрка",
		"The sign of the seven": "Знак семёрка",
		"The figure eight sign": "Знак восьмёрка",
		"The sign of the nine": "Знак девятка",
		"The sign of the ten": "Знак десятка",
		"The ABCD sign": "Знак ABCD",
		"The abcd sign": "Знак abcd",
		"Sign 1234": "Знак 1234",
		"Character input symbol": "Символ ввода символов",
		"The letter input symbol": "Символ ввода букв",
		"Latin capital letter A in a negative square": "Латинская заглавная буква A\nв отрицательном квадрате",
		"Negative square Ab": "Отрицательный квадрат Ab",
		"Latin capital letter B in a negative square": "Латинская заглавная буква B\nв отрицательном квадрате",
		"Square Cl": "Квадратный Cl",
		"Square Cool": "Квадратный Крутой",
		"Squared for free": "В квадрате бесплатно",
		"Information Symbol": "Символ Информации",
		"Square ID": "Квадратный ID",
		"Latin capital letter M in a circle": "Латинская заглавная буква M\nв круге",
		"Square New": "Квадратный Новый",
		"Square NG": "Квадратный NG",
		"Negative square Latin capital letter O": "Отрицательная квадратная\nлатинская заглавная буква O",
		"Square OK": "Квадратный OK",
		"Negative square Latin capital letter P": "Отрицательная квадратная\nлатинская заглавная буква P",
		"SOS squared": "SOS в квадрате",
		"Squared Up with an exclamation mark": "В квадрате Вверх\nс восклицательным знаком",
		"Squared VS": "В квадрате VS",
		"Coco's Square Katakana": "Квадратная катакана Коко",
		"Square Katakana Sa": "Квадратная катакана Sa",
		"Square Cjk Unified Ideograph-6708": "Квадратный Cjk\nунифицированный идеограф-6708",
		"Square Cjk Unified Ideograph-6709": "Квадратный Cjk\nунифицированный идеограф-6709",
		"Square Cjk Unified Ideograph-6307": "Квадратный Cjk\nунифицированный идеограф-6307",
		"The advantage of an ideogram in a circle": "Преимущество идеограммы в круге",
		"Square Cjk Unified Ideograph-5272": "Квадратный Cjk\nунифицированный идеограф-5272",
		"Square Cjk Unified Ideograph-7121": "Квадратный Cjk\nунифицированный идеограф-7121",
		"Square Cjk Unified Ideograph-7981": "Квадратный Cjk\nунифицированный идеограф-7981",
		"A round ideogram To accept": "Круглая идеограмма Принять",
		"Square Cjk Unified Ideograph-7533": "Квадратный Cjk\nунифицированный идеограф-7533",
		"Square Cjk Unified Ideograph-6408": "Квадратный Cjk\nунифицированный идеограф-6408",
		"Square Cjk Unified Ideograph-7A7A": "Квадратный Cjk\nунифицированный идеограф-7A7A",
		"Round ideogram Congratulations": "Круглая идеограмма Поздравление",
		"The round ideogram is a secret": "Круглая идеограмма Секрет",
		"Square Cjk Unified Ideograph-55B6": "Квадратный Cjk\nунифицированный идеограф-55B6",
		"Square Cjk Unified Ideograph-6E80": "Квадратный Cjk\nунифицированный идеограф-6E80",
		"The big red circle": "Большой красный круг",
		"The big blue circle": "Большой синий круг",
		"The middle white circle": "Средний белый круг",
		"The middle black circle": "Средний черный круг",
		"A large white square": "Белый большой квадрат",
		"A large black square": "Черный большой квадрат",
		"The black middle square": "Черный средний квадрат",
		"The white middle square": "Белый средний квадрат",
		"White Medium Small Square": "Белый Средний Маленький Квадрат",
		"Black Medium Small Square": "Черный Средний Маленький Квадрат",
		"A small white square": "Белый маленький квадрат",
		"A small black square": "Черный маленький квадрат",
		"A large orange diamond": "Большой оранжевый бриллиант",
		"The big blue diamond": "Большой голубой бриллиант",
		"A small orange diamond": "Маленький оранжевый бриллиант",
		"A small blue diamond": "Маленький голубой бриллиант",
		"The red triangle is upside down": "Красный треугольник вершиной вниз",
		"The shape of a diamond with a dot inside": "Форма ромба с точкой внутри",
		"Radio Button": "Радиокнопка",
		"Black square button": "Черная квадратная кнопка",
		"White square button": "Белая квадратная кнопка",
		// Флаги
		"The Checkered Flag": "Клетчатый флаг",
		"Triangular flag": "Треугольный флаг",
		"Crossed flags": "Скрещенные флаги",
		"The Black Flag": "Черный флаг",
		"The White flag": "Белый флаг",
		"Rainbow Flag": "Радужный флаг",
		"The Flag of the Transgender Community": "Флаг Трансгендерного Сообщества",
		"The Pirate Flag": "Пиратский флаг",
		"Flag: Ascension Island": "Флаг: О-В Вознесения",
		"Flag: Andorra": "Флаг: Андорра",
		"Flag: UAE": "Флаг: Оаэ",
		"Flag: Afghanistan": "Флаг: Афганистан",
		"Flag: Antigua and Barbuda": "Флаг: Антигуа и Барбуда",
		"Flag: Anguilla": "Флаг: Ангилья",
		"Flag: Albania": "Флаг: Албания",
		"Flag: Armenia": "Флаг: Армения",
		"Flag: Angola": "Флаг: Ангола",
		"Flag: Antarctica": "Флаг: Антарктида",
		"Flag: Argentina": "Флаг: Аргентина",
		"Flag: American Samoa": "Флаг: Американское Самоа",
		"Flag: Austria": "Флаг: Австрия",
		"Flag: Australia": "Флаг: Австралия",
		"Flag: Aruba": "Флаг: Аруба",
		"Flag: Aland Islands": "Флаг: Аландские О-Ва",
		"Flag: Azerbaijan": "Флаг: Азербайджан",
		"Flag: Bosnia and Herzegovina": "Флаг: Босния и Герцеговина",
		"Flag: Barbados": "Флаг: Барбадос",
		"Flag: Bangladesh": "Флаг: Бангладеш",
		"Flag: Belgium": "Флаг: Бельгия",
		"Flag: Burkina Faso": "Флаг: Буркина-Фасо",
		"Flag: Bulgaria": "Флаг: Болгария",
		"Flag: Bahrain": "Флаг: Бахрейн",
		"Flag: Burundi": "Флаг: Бурунди",
		"Flag: Benin": "Флаг: Бенин",
		"Flag: Saint Barthélémy": "Флаг: Сен-Бартелеми",
		"Flag: Bermuda": "Флаг: Бермудские О-Ва",
		"Flag: Brunei": "Флаг: Бруней",
		"Flag: Bolivia": "Флаг: Боливия",
		"Flag: Bonaire, Sint Eustatius and Saba": "Флаг: Бонэйр, Синт-Эстатиус и Саба",
		"Flag: Brazil": "Флаг: Бразилия",
		"Flag: Bahamas": "Флаг: Багамы",
		"Flag: Bhutan": "Флаг: Бутан",
		"Flag: O-In Bouvet": "Флаг: О-В Буве",
		"Flag: Botswana": "Флаг: Ботсвана",
		"Flag: Belarus": "Флаг: Беларусь",
		"Flag: Belize": "Флаг: Белиз",
		"Flag: Canada": "Флаг: Канада",
		"Flag: Coconut Islands": "Флаг: Кокосовые О-Ва",
		"Flag: Congo - Kinshasa": "Флаг: Конго - Киншаса",
		"Flag: Central African Republic": "Флаг: Центрально-Африканская Республика",
		"Flag: Congo - Brazzaville": "Флаг: Конго - Браззавиль",
		"Flag: Switzerland": "Флаг: Швейцария",
		"Flag: Ivory Coast": "Флаг: Кот-Д’ивуар",
		"Flag: Cook Island": "Флаг: О-Ва Кука",
		"Flag: Chile": "Флаг: Чили",
		"Flag: Cameroon": "Флаг: Камерун",
		"Flag: China": "Флаг: Китай",
		"Flag: Colombia-": "Флаг: Колумбия-",
		"Flag: Clipperton Island": "Флаг: О-В Клиппертон",
		"Flag: Costa Rica": "Флаг: Коста-Рика",
		"Flag: Cuba": "Флаг: Куба",
		"Flag: Cape Verde": "Флаг: Кабо-Верде",
		"Flag: Curacao": "Флаг: Кюрасао",
		"Flag: Christmas Island": "Флаг: О-В Рождества",
		"Flag: Cyprus": "Флаг: Кипр",
		"Flag: Czech Republic": "Флаг: Чехия",
		"Flag: Germany": "Флаг: Германия",
		"Flag: Diego Garcia": "Флаг: Диего-Гарсия",
		"Flag: Djibouti": "Флаг: Джибути",
		"Flag: Denmark": "Флаг: Дания",
		"Flag: Dominica": "Флаг: Доминика",
		"Flag: Dominican Republic": "Флаг: Доминиканская Республика",
		"Flag: Algeria": "Флаг: Алжир",
		"Flag: Ceuta and Melilla": "Флаг: Сеута и Мелилья",
		"Flag: Ecuador": "Флаг: Эквадор",
		"Flag: Estonia": "Флаг: Эстония",
		"Flag: Egypt": "Флаг: Египет",
		"Flag: Western Sahara": "Флаг: Западная Сахара",
		"Flag: Eritrea": "Флаг: Эритрея",
		"Flag: Spain": "Флаг: Испания",
		"Flag: Ethiopia": "Флаг: Эфиопия",
		"Flag: European Union": "Флаг: Европейский Союз",
		"Flag: Finland": "Флаг: Финляндия",
		"Flag: Fiji": "Флаг: Фиджи",
		"Flag: Falkland Islands": "Флаг: Фолклендские О-Ва",
		"Flag: Federated States of Micronesia": "Флаг: Федеративные Штаты Микронезии",
		"Flag: Faroe Islands": "Флаг: Фарерские О-Ва",
		"Flag: France": "Флаг: Франция",
		"Flag: Gabon": "Флаг: Габон",
		"Flag: United Kingdom": "Флаг: Великобритания",
		"Flag: Grenada": "Флаг: Гренада",
		"Flag: Georgia": "Флаг: Грузия",
		"Flag: French Guiana": "Флаг: Французская Гвиана",
		"Flag: Guernsey": "Флаг: Гернси",
		"Flag: Ghana": "Флаг: Гана",
		"Flag: Gibraltar": "Флаг: Гибралтар",
		"Flag: Greenland": "Флаг: Гренландия",
		"Flag: Gambia": "Флаг: Гамбия",
		"Flag: Guinea": "Флаг: Гвинея",
		"Flag: Guadeloupe": "Флаг: Гваделупа",
		"Flag: Equatorial Guinea": "Флаг: Экваториальная Гвинея",
		"Flag: Greece": "Флаг: Греция",
		"Flag: South Georgia and the South Sandwich Islands": "Флаг: Южная Георгия и Южные Сандвичевы О-Ва",
		"Flag: Guatemala": "Флаг: Гватемала",
		"Flag: Guam": "Флаг: Гуам",
		"Flag: Guinea-Bissau": "Флаг: Гвинея-Бисау",
		"Flag: Guyana": "Флаг: Гайана",
		"Flag: Hong Kong (SAR)": "Флаг: Гонконг (сар)",
		"Flag: Heard and McDonald Islands": "Флаг: О-Ва Херд и Макдональд",
		"Flag: Honduras": "Флаг: Гондурас",
		"Flag: Croatia": "Флаг: Хорватия",
		"Flag: Haiti": "Флаг: Гаити",
		"Flag: Hungary": "Флаг: Венгрия",
		"Flag: Canary Islands": "Флаг: Канарские О-Ва",
		"Flag: Indonesia": "Флаг: Индонезия",
		"Flag: Ireland": "Флаг: Ирландия",
		"Flag: Israel": "Флаг: Израиль",
		"Flag: Isle of Man": "Флаг: О-В Мэн",
		"Flag: India": "Флаг: Индия",
		"Flag: British Indian Ocean Territory": "Флаг: Британская Территория в Индийском Океане",
		"Flag: Iraq": "Флаг: Ирак",
		"Flag: Iran": "Флаг: Иран",
		"Flag: Iceland": "Флаг: Исландия",
		"Flag: Italy": "Флаг: Италия",
		"Flag: Jersey": "Флаг: Джерси",
		"Flag: Jamaica": "Флаг: Ямайка",
		"Flag: Jordan": "Флаг: Иордания",
		"Flag: Japan": "Флаг: Япония",
		"Flag: Kenya": "Флаг: Кения",
		"Flag: Kyrgyzstan": "Флаг: Киргизия",
		"Flag: Cambodia": "Флаг: Камбоджа",
		"Flag: Kiribati": "Флаг: Кирибати",
		"Flag: Comoros": "Флаг: Коморы",
		"Flag: Saint Kitts and Nevis": "Флаг: Сент-Китс и Невис",
		"Flag: North Korea": "Флаг: Кндр",
		"Flag: Republic of Korea": "Флаг: Республика Корея",
		"Flag: Kuwait": "Флаг: Кувейт",
		"Flag: Cayman Island": "Флаг: О-Ва Кайман",
		"Flag: Kazakhstan": "Флаг: Казахстан",
		"Flag: Laos": "Флаг: Лаос",
		"Flag: Lebanon": "Флаг: Ливан",
		"Flag: Saint Lucia": "Флаг: Сент-Люсия",
		"Flag: Liechtenstein": "Флаг: Лихтенштейн",
		"Flag: Sri Lanka": "Флаг: Шри-Ланка",
		"Flag: Liberia": "Флаг: Либерия",
		"Flag: Lesotho": "Флаг: Лесото",
		"Flag: Lithuania": "Флаг: Литва",
		"Flag: Luxembourg": "Флаг: Люксембург",
		"Flag: Latvia": "Флаг: Латвия",
		"Flag: Libya": "Флаг: Ливия",
		"Flag: Morocco": "Флаг: Марокко",
		"Flag: Monaco": "Флаг: Монако",
		"Flag: Moldova": "Флаг: Молдова",
		"Flag: Montenegro": "Флаг: Черногория",
		"Flag: Saint Martin": "Флаг: Сен-Мартен",
		"Flag: Madagascar": "Флаг: Мадагаскар",
		"Flag: Marshall Islands": "Флаг: Маршалловы О-Ва",
		"Flag: North Macedonia": "Флаг: Северная Македония",
		"Flag: Mali": "Флаг: Мали",
		"Flag: Myanmar (Burma)": "Флаг: Мьянма (Бирма)",
		"Flag: Mongolia": "Флаг: Монголия",
		"Flag: Macau (Sar)": "Флаг: Макао (Сар)",
		"Flag: Northern Mariana Islands": "Флаг: Северные Марианские О-Ва",
		"Flag: Martinique": "Флаг: Мартиника",
		"Flag: Mauritania": "Флаг: Мавритания",
		"Flag: Montserrat": "Флаг: Монтсеррат",
		"Flag: Malta": "Флаг: Мальта",
		"Flag: Mauritius": "Флаг: Маврикий",
		"Flag: Maldives": "Флаг: Мальдивы",
		"Flag: Malawi": "Флаг: Малави",
		"Flag: Mexico": "Флаг: Мексика",
		"Flag: Malaysia": "Флаг: Малайзия",
		"Flag: Mozambique": "Флаг: Мозамбик",
		"Flag: Namibia": "Флаг: Намибия",
		"Flag: New Caledonia": "Флаг: Новая Каледония",
		"Flag: Niger": "Флаг: Нигер",
		"Flag: Norfolk Island": "Флаг: О-В Норфолк",
		"Flag: Nigeria": "Флаг: Нигерия",
		"Flag: Nicaragua": "Флаг: Никарагуа",
		"Flag: Netherlands": "Флаг: Нидерланды",
		"Flag: Norway": "Флаг: Норвегия",
		"Flag: Nepal": "Флаг: Непал",
		"Flag: Nauru": "Флаг: Науру",
		"Flag: Niue": "Флаг: Ниуэ",
		"Flag: New Zealand": "Флаг: Новая Зеландия",
		"Flag: Oman": "Флаг: Оман",
		"Flag: Panama": "Флаг: Панама",
		"Flag: Peru": "Флаг: Перу",
		"Flag: French Polynesia": "Флаг: Французская Полинезия",
		"Flag: Papua New Guinea": "Флаг: Папуа — Новая Гвинея",
		"Flag: Philippines": "Флаг: Филиппины",
		"Flag: Pakistan": "Флаг: Пакистан",
		"Flag: Poland": "Флаг: Польша",
		"Flag: Saint Pierre and Miquelon": "Флаг: Сен-Пьер и Микелон",
		"Flag: Pitcairn Island": "Флаг: О-Ва Питкэрн",
		"Flag: Puerto Rico": "Флаг: Пуэрто-Рико",
		"Flag: Palestinian Territories": "Флаг: Палестинские Территории",
		"Flag: Portugal": "Флаг: Португалия",
		"Flag: Palau": "Флаг: Палау",
		"Flag: Paraguay": "Флаг: Парагвай",
		"Flag: Qatar": "Флаг: Катар",
		"Flag: Reunion": "Флаг: Реюньон",
		"Flag: Romania": "Флаг: Румыния",
		"Flag: Serbia": "Флаг: Сербия",
		"Flag: Russia": "Флаг: Россия",
		"Flag: Rwanda": "Флаг: Руанда",
		"Flag: Saudi Arabia": "Флаг: Саудовская Аравия",
		"Flag: Solomon Islands": "Флаг: Соломоновы О-Ва",
		"Flag: Seychelles": "Флаг: Сейшельские О-Ва",
		"Flag: Sudan": "Флаг: Судан",
		"Flag: Sweden": "Флаг: Швеция",
		"Flag: Singapore": "Флаг: Сингапур",
		"Flag: St. Helena Island": "Флаг: О-В Св. Елены",
		"Flag: Slovenia": "Флаг: Словения",
		"Flag: Svalbard and Jan Mayen": "Флаг: Шпицберген и Ян-Майен",
		"Flag: Slovakia": "Флаг: Словакия",
		"Flag: Sierra Leone": "Флаг: Сьерра-Леоне",
		"Flag: San Marino": "Флаг: Сан-Марино",
		"Flag: Senegal": "Флаг: Сенегал",
		"Flag: Somalia": "Флаг: Сомали",
		"Flag: Suriname": "Флаг: Суринам",
		"Flag: South Sudan": "Флаг: Южный Судан",
		"Flag: Sao Tome and Principe": "Флаг: Сан-Томе и Принсипи",
		"Flag: El Salvador": "Флаг: Сальвадор",
		"Flag: Sint Maarten": "Флаг: Синт-Мартен",
		"Flag: Syria": "Флаг: Сирия",
		"Flag: Eswatini": "Флаг: Эсватини",
		"Flag: Tristan Da Cunha": "Флаг: Тристан-Да-Кунья",
		"Flag: Turks and Caicos Islands": "Флаг: Тёркс и Кайкос",
		"Flag: Chad": "Флаг: Чад",
		"Flag: French Southern Territories": "Флаг: Французские Южные Территории",
		"Flag: Togo": "Флаг: Того",
		"Flag: Thailand": "Флаг: Таиланд",
		"Flag: Tajikistan": "Флаг: Таджикистан",
		"Flag: Tokelau": "Флаг: Токелау",
		"Flag: East Timor": "Флаг: Восточный Тимор",
		"Flag: Turkmenistan": "Флаг: Туркменистан",
		"Flag: Tunis": "Флаг: Тунис",
		"Flag: Tonga": "Флаг: Тонга",
		"Flag: Turkey": "Флаг: Турция",
		"Flag: Trinidad and Tobago": "Флаг: Тринидад и Тобаго",
		"Flag: Tuvalu": "Флаг: Тувалу",
		"Flag: Taiwan": "Флаг: Тайвань",
		"Flag: Tanzania": "Флаг: Танзания",
		"Flag: Ukraine": "Флаг: Украина",
		"Flag: Uganda": "Флаг: Уганда",
		"Flag: Outer Small Islands (USA)": "Флаг: Внешние Малые О-Ва (США)",
		"Flag: United Nations": "Флаг: Организация Объединенных Наций",
		"Flag: United States": "Флаг: Соединенные Штаты",
		"Flag: Uruguay": "Флаг: Уругвай",
		"Flag: Uzbekistan": "Флаг: Узбекистан",
		"Flag: Vatican City": "Флаг: Ватикан",
		"Flag: Saint Vincent and the Grenadines": "Флаг: Сент-Винсент и Гренадины",
		"Flag: Venezuela": "Флаг: Венесуэла",
		"Flag: Virgin Islands (Great Britain)": "Флаг: Виргинские О-Ва (Великобритания)",
		"Flag: Virgin Islands (USA)": "Флаг: Виргинские О-Ва (США)",
		"Flag: Vietnam": "Флаг: Вьетнам",
		"Flag: Vanuatu": "Флаг: Вануату",
		"Flag: Wallis and Futuna": "Флаг: Уоллис и Футуна",
		"Flag: Samoa": "Флаг: Самоа",
		"Flag: Kosovo": "Флаг: Косово",
		"Flag: Yemen": "Флаг: Йемен",
		"Flag: Mayotte": "Флаг: Майотта",
		"Flag: Republic of South Africa": "Флаг: Южно-Африканская Республика",
		"Flag: Zambia": "Флаг: Замбия",
		"Flag: Zimbabwe": "Флаг: Зимбабве",
		"Flag: England": "Флаг: Англия",
		"Flag: Scotland": "Флаг: Шотландия",
		"Flag: Wales": "Флаг: Уэльс",
	});
