/**
 * Локализация Германия
 */
tinymce.addI18n('de', {
	"Emoji": "Emoji (Emoji)",
	"Smiles": "Smileys",
	"Emotics": "Emotionen",
	"People": "Leute",
	"Animals": "Tiere",
	"Nature": "Die Natur",
	"Food and Drinks": "Essen und Trinken",
	"Places and Travels": "Orte und Reisen",
	"Events and Celebrations": "Veranstaltungen und Feiertage",
	"Objects and Things": "Objekte und Dinge",
	"Symbols": "Symbole",
	"Flags": "Flaggen",
	"Animals and Nature": "Tiere und Natur",
	"The grinning face": "Grinsendes Gesicht",
	"A smiling face with an open mouth": "Lächelndes Gesicht\nmit offenem Mund",
	"A smiling face with an open mouth and smiling eyes": "Lächelndes Gesicht\nmit offenem Mund\nund mit lächelnden Augen",
	"A grinning face with smiling eyes": "Grinsendes Gesicht\nmit lächelnden Augen",
	"A smiling face with an open mouth and tightly closed eyes": "Lächelndes Gesicht\nmit offenem Mund\nund mit dicht geschlossenen Augen",
	"A smiling face with an open mouth and cold sweat": "Lächelndes Gesicht\nmit offenem Mund\nund im kalten Schweiß",
	"Rolling on the floor laughing": "Ich fahre vor Lachen auf dem Boden",
	"A face with tears of joy": "Ein Gesicht mit Freudentränen",
	"A slightly smiling face": "Leicht lächelndes Gesicht",
	"The inverted face": "Umgedrehtes Gesicht",
	"The winking face": "Augenzwinkerndes Gesicht",
	"A smiling face with smiling eyes": "Lächelndes Gesicht\nmit lächelnden Augen",
	"A smiling face with a halo": "Lächelndes Gesicht\nmit einem Nimbus",
	"A smiling face with smiling eyes and three hearts": "Lächelndes Gesicht\nmit lächelnden Augen\nund drei Herzen",
	"A smiling face with heart-shaped eyes": "Lächelndes Gesicht\nmit herzförmigen Augen",
	"A grinning face with starry eyes": "Grinsendes Gesicht\nmit Sternenaugen",
	"The person sending the kiss": "Das Gesicht, das einen Kuss sendet",
	"The kissing face": "Küssendes Gesicht",
	"A white smiling face": "Weißes lächelndes Gesicht",
	"Kissing a face with closed eyes": "Küssendes Gesicht\nmit geschlossenen Augen",
	"A kissing face with smiling eyes": "Küssendes Gesicht\nmit lächelnden Augen",
	"A person enjoying a delicious meal": "Eine Person, die leckeres Essen genießt",
	"A face with a protruding tongue": "Gesicht mit ausgestreckter Zunge",
	"A face with a protruding tongue and a winking eye": "Gesicht mit ausgestreckter Zunge\nund mit einem Augenzwinkern",
	"A grinning face with one big and one small eye": "Grinsendes Gesicht\nmit einem großen\nund mit einem kleinen Auge",
	"A face with a protruding tongue and tightly closed eyes": "Gesicht mit ausgestreckter Zunge\nund mit dicht geschlossenen Augen",
	"The face with the money mouth": "Das Gesicht mit dem Geldmund",
	"The hugging face": "Umarmendes Gesicht",
	"A smiling face with smiling eyes and a hand covering his mouth": "Lächelndes Gesicht\nmit lächelnden Augen\nund mit der Hand, die den Mund schließt",
	"A face with closed lips, covered with a finger": "Gesicht mit geschlossenen Lippen,\nmit dem Finger bedeckt",
	"The thinking face": "Das denkende Gesicht",
	"A face with a zipper": "Gesicht mit Reißverschluss",
	"A face with a raised eyebrow": "Gesicht mit erhobener Augenbraue",
	"A neutral person": "Neutrales Gesicht",
	"A face without expression": "Gesicht ohne Ausdruck",
	"A face without a mouth": "Gesicht ohne Mund",
	"A sad face": "Unglückliches Gesicht",
	"A face with rolled eyes": "Gesicht mit verdrehten Augen",
	"The grimacing face": "Grimassierendes Gesicht",
	"A lying face": "Ein falsches Gesicht",
	"A relieved face": "Gesicht mit Erleichterung",
	"A thoughtful face": "Nachdenkliches Gesicht",
	"Sleepy face": "Verschlafenes Gesicht",
	"Slobbery face": "Sabberndes Gesicht",
	"The sleeping face": "Schlafendes Gesicht",
	"A face with a medical mask": "Gesicht mit medizinischer Maske",
	"A face with a thermometer": "Gesicht mit Thermometer",
	"A face with a headband": "Gesicht mit einem Verband auf dem Kopf",
	"Sickening face": "Ekelhaftes Gesicht",
	"Face with open mouth, vomiting": "Gesicht mit offenem Mund, Erbrechen",
	"Sneezing face": "Niesendes Gesicht",
	"Overheated face": "Überhitztes Gesicht",
	"The freezing face": "Gefrorenes Gesicht",
	"A face with uneven eyes and a wavy mouth": "Gesicht mit unebenen Augen\nund mit einem gewellten Mund",
	"The dizzying face": "Schwindelerregendes Gesicht",
	"A shocked face with an exploding head": "Schockiertes Gesicht\nmit explodierendem Kopf",
	"The face in the cowboy hat": "Gesicht im Cowboyhut",
	"A face with a festive horn and a festive hat": "Gesicht mit festlichem Horn\nund einen festlichen Hut",
	"Smiling face in sunglasses": "Lächelndes Gesicht\nmit Sonnenbrille",
	"Nerd's face": "Das Gesicht des Nerds",
	"Face with a monocle": "Gesicht mit Monokel",
	"A confused face": "Verwirrtes Gesicht",
	"A worried face": "Besorgte Person",
	"A slightly frowning face": "Leicht stirnrunzelndes Gesicht",
	"A frowning face": "Düsteres Gesicht",
	"A face with an open mouth": "Gesicht mit offenem Mund",
	"The silent face": "Schweigendes Gesicht",
	"The surprised face": "Überraschtes Gesicht",
	"Reddened face": "Gerötetes Gesicht",
	"A face with pleading eyes": "Gesicht mit bettelnden Augen",
	"A frowning face with an open mouth": "Stirnrunzelndes Gesicht mit offenem Mund",
	"The suffering face": "Das leidende Gesicht",
	"A scared face": "Verängstigtes Gesicht",
	"A face with an open mouth and cold sweat": "Gesicht mit offenem Mund und kaltem Schweiß",
	"A disappointed but relieved face": "Ein enttäuschtes, aber erleichtertes Gesicht",
	"The crying face": "Weinendes Gesicht",
	"A crying face": "Laut weinendes Gesicht",
	"The face screams with fear": "Das Gesicht schreit vor Angst",
	"An insistent face": "Hartnäckiges Gesicht",
	"The disappointed face": "Enttäuschtes Gesicht",
	"My face is covered in cold sweat": "Gesicht im kalten Schweiß",
	"Tired face": "Müdes Gesicht",
	"A face with an expression of triumph": "Ein Gesicht mit einem Ausdruck des Triumphes",
	"Pouty face": "Aufgeblähtes Gesicht",
	"Angry face": "Wütendes Gesicht",
	"A serious face with symbols covering its mouth": "Ernstes Gesicht mit Symbolen\nden Mund schließen",
	"A smiling face with horns": "Lächelndes Gesicht mit Hörnern",
	"The little devil": "kleiner Teufel",
	"Skull": "Der Schädel",
	"Skull and Crossbones": "Schädel und gekreuzte Knochen",
	"A bunch of poop": "Haufen Kacke",
	"The clown's face": "Das Gesicht des Clowns",
	"The Japanese Ogre": "Japanischer Oger",
	"The Japanese Goblin": "Japanischer Kobold",
	"Ghost": "Geist",
	"The extraterrestrial alien": "Außerirdischer Alien",
	"The alien monster": "Alien Monster",
	"The robot's face": "Das Gesicht des Roboters",
	"Smiling cat face with open mouth": "Lächelndes Katzengesicht\nmit offenem Mund",
	"The grinning face of a cat with smiling eyes": "Grinsende Katzenschnauze\nmit lächelnden Augen",
	"A cat's face with tears of joy": "Katzenschnauze\nmit tränen der Freude",
	"Smiling cat face with heart-shaped eyes": "Lächelndes Katzengesicht\nmit herzförmigen Augen",
	"A cat's face with a crooked smile": "Katzenschnauze\nmit einem krummen lächeln",
	"Kissing a cat's face with its eyes closed": "Das Gesicht einer Katze küssen\nmit geschlossenen Augen",
	"Tired cat face": "Müdes Katzengesicht",
	"The crying face of a cat": "Die weinende Schnauze einer Katze",
	"The pouting face of a cat": "Aufgeblasene Katzenschnauze",
	"The monkey who sees no evil": "Ein Affe, der das Böse nicht sieht",
	"The monkey who hears no evil": "Ein Affe, der das Böse nicht hört",
	"A monkey who doesn't speak evil": "Ein Affe, der nicht böse spricht",
	"A kiss": "Der Kuss",
	"A love letter": "Liebesbrief",
	"A heart with an arrow": "Herz mit Pfeil",
	"Heart with ribbon": "Herz mit Band",
	"The Sparkling Heart": "Funkelndes Herz",
	"The growing heart": "Wachsendes Herz",
	"A Beating Heart": "Ein schlagendes Herz",
	"Spinning Hearts": "Rotierende Herzen",
	"Two Hearts": "Zwei Herzen",
	"Heart-shaped decoration": "Herzförmige Dekoration",
	"A heart with an exclamation mark": "Ein Herz mit einem Ausrufezeichen",
	"A Broken Heart": "Gebrochenes Herz",
	"Heart": "Herz",
	"The Orange Heart": "Orangefarbenes Herz",
	"The Yellow Heart": "Gelbes Herz",
	"The Green Heart": "Grünes Herz",
	"The Blue Heart": "Blaues Herz",
	"Purple Heart": "Lila Herz",
	"The Black Heart": "Schwarzes Herz",
	"The symbol is 100 points": "Symbol 100 Punkte",
	"The symbol of anger": "Symbol des Zorns",
	"Collision symbol": "Kollisionssymbol",
	"The symbol of vertigo": "Symbol für Schwindel",
	"The sweat spray symbol": "Schweißspritzer-Symbol",
	"The Wind symbol": "Wind-Symbol",
	"Hole": "Loch",
	"Bomb": "Bombe",
	"A callout with a speech": "Sprechende Legende",
	"The left speech bubble": "Linke Sprechblase",
	"The right anger bubble": "Die richtige Wutblase",
	"The Thought ball": "Der Denkball",
	"The Sleeping Symbol": "Schlafendes Symbol",
	"Waving hand": "Winkende Hand",
	"The raised back of the hand": "Erhobener Handrücken",
	"A raised hand with outstretched fingers": "Erhobene Hand mit ausgestreckten Fingern",
	"Raised hand": "Sich melden",
	"A raised hand with a parting between the middle and ring fingers": "Erhobene Hand mit einem Abstand zwischen dem mittleren\nund mit den Ringfingern",
	"The \"OK\" hand sign": "Handzeichen \"OK»",
	"\"Victory\" hand sign": "Handzeichen »Sieg\"",
	"The hand with the index and middle fingers crossed": "Hand mit gekreuztem Zeigefinger\nund mit den Mittelfingern",
	"I love you hand gesture": "Ich liebe dich mit der Hand Geste",
	"The Sign of Horns": "Zeichen der Hörner",
	"Hand sign \"Call me\"": "Handzeichen «Ruf mich an»",
	"Back of the hand Index finger to the left": "Handrücken\nZeigefinger nach links",
	"Back of the hand Index finger to the right": "Handrücken\nZeigefinger nach rechts",
	"Back of the hand Index finger up": "Handrücken\nZeigefinger nach oben",
	"The back of the hand with the middle finger extended": "Handrücken\nmit ausgestrecktem Mittelfinger",
	"Back of the hand, index finger down": "Handrücken\nZeigefinger nach unten",
	"Index finger up": "Zeigefinger nach oben",
	"Thumbs up": "Daumen hoch",
	"Thumbs down": "Daumen nach unten",
	"Raised fist": "Erhobene Faust",
	"The sign of a clenched fist": "Zeichen der geballten Hand in die Faust",
	"Left-facing fist": "Faust nach links gerichtet",
	"Fist facing right": "Faust nach rechts gerichtet",
	"The sign of clapping hands": "Das Zeichen der klatschenden Hände",
	"A man who raised both hands in celebration": "Ein Mann, der beide Hände als Zeichen der Feier hob",
	"The \"Open Hands\" sign": "Zeichen \"Offene Hände»",
	"Palms up together": "Handflächen zusammen nach oben",
	"Handshake": "Händedruck",
	"A man with folded arms": "Mann mit gefalteten Händen",
	"The writing hand": "Schreibende Hand",
	"Manicure, Nail polish": "Maniküre, Nagellack",
	"Selfie": "Selfie",
	"Bent biceps": "Gebeugter Bizeps",
	"Leg": "Bein",
	"Foot": "Fuß",
	"Ear": "Ohr",
	"Nose": "Nase",
	"Brain": "Das Gehirn",
	"Tooth": "Zahn",
	"Bone": "Knochen",
	"Eyes": "Augen",
	"Eye": "Das Auge",
	"Tongue": "Sprache",
	"Mouth": "Mund",
	"Baby": "Kleinkind",
	"Child": "Kind",
	"Boy": "Der Junge",
	"Girl": "Das Mädchen",
	"Adult": "Erwachsen",
	"The man with the blond hair": "Mann mit blonden Haaren",
	"Man": "Ein Mann",
	"The Bearded Man": "Bärtiger Mann",
	"Woman": "Eine Frau",
	"An older adult": "Älterer Erwachsener",
	"An elderly man": "ein älterer Herr",
	"An elderly woman": "Ältere Frau",
	"The man frowns": "Der Mann runzelt die Stirn",
	"The man with the pouty face": "Mann mit aufgeblähtem Gesicht",
	"A face without a good gesture": "Ein Gesicht ohne eine gute Geste",
	"The face with the \"OK\" gesture": "Gesicht mit »OK\" -Geste",
	"Information Bureau employee": "Mitarbeiter des Informationsbüros",
	"The lucky man who raised one hand": "Ein glücklicher Mann, der eine Hand hob",
	"A man bowing low": "Ein Mann, der sich tief verbeugt",
	"Face Palm": "Gesicht Handfläche",
	"The shrug of the shoulders": "Achselzucken",
	"Policeman": "Polizist",
	"Detective or spy": "Detektiv oder Spion",
	"The Guardsman": "Gardist",
	"Construction worker": "Bauarbeiter",
	"Prince": "Prinz",
	"Princess": "Prinzessin",
	"The man in the turban": "Ein Mann im Turban",
	"The man with Gua Pi Mao": "Ein Mann mit Gua Pi Mao",
	"The man in the headscarf": "Der Mann im Kopftuch",
	"The man in the tuxedo": "Ein Mann im Smoking",
	"The bride with a veil": "Braut mit Schleier",
	"Pregnant Woman": "Schwangere Frau",
	"Breastfeeding": "Stillen",
	"Baby angel": "Baby-Engelchen",
	"Father Christmas": "Weihnachtsmann",
	"Mother Christmas": "Mutter Weihnachten",
	"The Super hero": "Super-Held",
	"The Super villain": "Super-Bösewicht",
	"The Magician": "Magier",
	"Fairy": "Feen",
	"A vampire": "Ein Vampir",
	"Merperson. Mermaid": "Merperson. Wassernixe",
	"Elf": "Elf",
	"Gin": "Gin",
	"Zombie": "Zombie",
	"Facial massage": "Gesichtsmassage",
	"A haircut": "Ein Haarschnitt",
	"Pedestrian": "Ein Fußgänger",
	"Runner": "Läufer",
	"Dancer": "Tänzer",
	"The man is dancing": "Ein Mann tanzt",
	"A man in a business suit levitates": "Ein Mann im Business-Anzug schwebt",
	"The woman with the rabbit ears": "Frau mit Hasenohren",
	"The man in the steam room": "Mann im Dampfbad",
	"The rising Man": "Ein Mann, der aufsteigt",
	"The Swordsman": "Fechter",
	"Horse racing": "Pferderennen",
	"Skier": "Skifahrer",
	"The snowboarder": "Snowboarder",
	"The golfer": "Golfspieler",
	"The Surfer": "Surfer",
	"Rowing boat": "Ruderboot",
	"Swimmer": "Schwimmer",
	"The man with the ball": "Der Mann mit dem Ball",
	"Weightlifter": "Gewichtheber",
	"Bicyclist": "Radfahrer",
	"Mountain biker": "Mountainbiker",
	"The man making the wheel": "Der Mann, der das Rad herstellt",
	"The wrestlers": "Ringer",
	"Water polo": "Wasserball",
	"Handball": "Handball",
	"Juggling": "Jonglieren",
	"The man in the lotus position": "Ein Mann in einer Lotus-Pose",
	"Bath": "Badewanne",
	"Accommodation in sleeping places": "Unterkunft in Schlafplätzen",
	"Two women holding hands": "Zwei Frauen halten sich an den Händen",
	"A man and a woman holding hands": "Mann und Frau halten sich an den Händen",
	"Two men holding hands": "Zwei Männer halten sich an den Händen",
	"Kisses": "Küssen",
	"A couple with a heart": "Paar mit Herz",
	"Family": "Die Familie",
	"Talking head in silhouette": "Sprechender Kopf in Silhouette",
	"Bust in silhouette": "Büste in Silhouette",
	"Monkey face": "Affengesicht",
	"A monkey": "Ein Affe",
	"Gorilla": "Gorilla",
	"The dog's face": "Das Gesicht des Hundes",
	"Dog": "Der Hund",
	"The poodle": "Pudel",
	"The face of the wolf": "Das Gesicht des Wolfes",
	"The fox's face": "Das Gesicht des Fuchses",
	"Raccoon's face": "Waschbärgesicht",
	"The cat's face": "Das Gesicht der Katze",
	"Cat": "Der Kater",
	"The Lion's Face": "Das Gesicht des Löwen",
	"Tiger's Face": "Gesicht des Tigers",
	"Tiger": "Tiger",
	"Leopard": "Leopard",
	"The horse's face": "Das Gesicht des Pferdes",
	"Horse": "Ein Pferd",
	"The Unicorn's Face": "Einhorn-Gesicht",
	"Zebra's face": "Das Gesicht des Zebras",
	"Deer": "Hirsch",
	"Cow's face": "Das Gesicht einer Kuh",
	"Bull": "Ochse",
	"Water buffalo": "Wasserbüffel",
	"Cow": "Eine Kuh",
	"Piglet's face": "Das Gesicht des Ferkels",
	"The piglet": "Ferkel",
	"The boar's face": "Das Gesicht eines Wildschweins",
	"Piglet's Nickel": "Ferkelferkel",
	"Ram": "Widder",
	"Sheep": "Schaf",
	"Goat": "Ziegenbock",
	"The one-humped camel": "Einhorbiges Kamel",
	"The double-humped camel": "Trampeltier",
	"Lama": "Lama",
	"Giraffe's face": "Gesicht der Giraffe",
	"Elephant": "Elefant",
	"Rhinoceros": "Nashorn",
	"Hippopotamus": "Hippo",
	"The mouse's face": "Gesicht der Maus",
	"Mouse": "Maus",
	"Rat": "Ratte",
	"Hamster's face": "Das Gesicht des Hamsters",
	"The face of the hare": "Gesicht des Hasen",
	"Hare": "Hase",
	"The Chipmunk": "Burunduk",
	"The Hedgehog": "Igel",
	"Bat": "Fledermaus",
	"The face of the bear": "Das Gesicht des Bären",
	"Koala's face": "Gesicht des Koalas",
	"Panda's Face": "Panda-Gesicht",
	"Kangaroo": "Känguru",
	"Badger": "Dachs",
	"Paw prints": "Pfotenabdrücke",
	"Turkey": "Truthuhn",
	"Chicken": "Küken",
	"Cock": "Hahn",
	"The hatching chick": "Schlüpfendes Huhn",
	"The chicken looking forward": "Ein Huhn, das nach vorne schaut",
	"Bird": "Der Vogel",
	"Penguin": "Pinguin",
	"The Dove of Peace": "Friedenstaube",
	"Eagle": "Adler",
	"Duck": "Ente",
	"Swan": "Der Schwan",
	"Owl": "Eule",
	"Peacock": "Pfau",
	"Parrot": "Der Papagei",
	"The frog's face": "Froschgesicht",
	"Crocodile": "Krokodil",
	"Turtle": "Schildkröte",
	"Lizard": "Eidechse",
	"Snake": "Die Schlange",
	"The Dragon's Face": "Das Gesicht des Drachen",
	"Dragon": "Der Drache",
	"Sauropod": "Sauropod",
	"T-Rex": "T-Rex",
	"The Splashing Whale": "Spritzender Wal",
	"Whale": "Wal",
	"Dolphin": "Delfin",
	"Fish": "Fische",
	"Tropical fish": "Tropischer Fisch",
	"Needle Fish": "Nadelfisch",
	"Shark": "Haifisch",
	"Octopus": "Oktopus",
	"Spiral Shell": "Spiralschale",
	"Snail": "Schnecke",
	"Butterfly": "Schmetterling",
	"Caterpillar": "Raupe",
	"Ant": "Ameise",
	"The honey bee": "Honigbiene",
	"Ladybug": "Marienkäfer",
	"The cricket": "Grillen",
	"Spider": "Spinne",
	"Web": "Spinngewebe",
	"Scorpio": "Skorpion",
	"Mosquito": "Mücke",
	"The microbe": "Mikrobe",
	"Bouquet": "Ein Blumenstrauß",
	"Cherry blossoms": "Blühende Kirsche",
	"The White Flower": "Weiße Blume",
	"Rosette of leaves": "Blatt-Rosette",
	"Rose": "Rose",
	"A faded flower": "Verwelkte Blume",
	"Hibiscus": "Hibiskus",
	"Sunflower": "Sonnenblume",
	"Tulip": "Tulpe",
	"Seedlings": "Setzlinge",
	"The evergreen tree": "Immergrüner Baum",
	"Deciduous tree": "Laubbaum",
	"Palm tree": "Palme",
	"Cactus": "Kaktus",
	"Rice": "Reis",
	"Grass": "Gras",
	"The Shamrock": "Kleeblatt",
	"Four-leaf clover": "Glücksklee",
	"Maple Leaf": "Ahornblatt",
	"The fallen leaf": "Gefallenes Blatt",
	"A leaf flutters in the wind": "Das Blatt flattert im Wind",
	"Grape": "Weintraube",
	"Melon": "Melone",
	"Watermelon": "Wassermelone",
	"Mandarin": "Mandarin",
	"Lemon": "Zitrone",
	"Banana": "Banane",
	"Pineapple": "Ananas",
	"Mango": "Mango",
	"Red Apple": "Roter Apfel",
	"The green Apple": "Grüner Apfel",
	"Pear": "Birne",
	"Peach": "Pfirsich",
	"Cherry": "Kirsche",
	"Strawberry": "Erdbeere",
	"Kiwi": "Kiwi",
	"Tomato": "Tomate",
	"Kakos": "Kakos",
	"Avocado": "Avocado",
	"Eggplant": "Aubergine",
	"Potato": "Kartoffel",
	"Markovka": "Markowka",
	"Corn": "Türkenkorn",
	"Hot pepper": "Scharfer Pfeffer",
	"Cucumber": "Gurke",
	"Leafy greens": "Blattgemüse",
	"Broccoli": "Brokkoli",
	"Fly agaric": "Fliegenpilz",
	"Peanut": "Erdnüsse",
	"Chestnut": "Kastanienbaum",
	"Bread": "Brot",
	"Croissant": "Croissant",
	"Baguette bread": "Baguette-Brot",
	"Pretzel": "Brezel",
	"Bagel": "Kringel",
	"Pancakes": "Pfannkuchen",
	"Cheese wedge": "Käsekeil",
	"Meat on the bone": "Knochenfleisch",
	"Bird's foot": "Bein des Vogels",
	"A piece of meat": "Fleischstück",
	"Bacon": "Speck",
	"Hamburger": "Hamburger",
	"French fries": "Pommes frites",
	"A slice of pizza": "Ein Stück Pizza",
	"Hot dog": "Hot dog",
	"Sandwich": "Sandwich",
	"Tacos": "Tacos",
	"Burrito": "Burritos",
	"Tortilla with filling": "Tortillas mit Füllung",
	"Egg": "Das Ei",
	"Scrambled eggs": "Rührei",
	"A shallow pot of food": "Flache Pfanne mit Essen",
	"A pot of food": "Topf mit Essen",
	"A bowl with a spoon": "Schüssel mit Löffel",
	"Green salad": "grüner Salat",
	"Popcorn": "Popcorn",
	"The salt shaker": "Salzstreuer",
	"Preserves": "Konserve",
	"Container": "Ein Behälter",
	"Rice Cracker": "Reis Cracker",
	"Rice ball": "Reisbällchen",
	"Boiled rice": "Gekochter Reis",
	"Curry and rice": "Curry und Reis",
	"Steaming bowl": "Schüssel zum gedämpften Kochen",
	"Spaghetti": "Spaghetti",
	"Fried sweet potatoes": "Gebratene Süßkartoffel",
	"Dressed": "Oden",
	"Sushi": "Sushi",
	"Fried shrimp": "Gebratene Garnelen",
	"Fish pie with curls": "Fischkuchen mit Locken",
	"Mooncake": "Mondkuchen",
	"Dango": "Dango",
	"Cheburek": "Pastete",
	"Fortune Cookies": "Kekse mit Vorhersage",
	"Takeaway Food Box": "Kiste zum Mitnehmen",
	"The crab": "Krabbe",
	"Lobster": "Hummer",
	"Shrimp": "Garnele",
	"Squid": "Kalmar",
	"Soft ice cream": "Softeis",
	"Planed ice": "Gehobeltes Eis",
	"Ice cream": "Eis",
	"Donut": "Donut",
	"Cookie": "Gebäck",
	"Birthday cake": "Geburtstagstorte",
	"Shortbread cookies": "Shortbread Cookies",
	"Cupcake": "Kuchen",
	"Pie": "Kuchen",
	"Chocolate bar": "eine Tafel Schokolade",
	"Candies": "Bonbons",
	"Candy": "Bonbon",
	"Custard cream": "Pudding",
	"Honey": "Honig",
	"Baby bottle": "Babyflasche",
	"A Glass of Milk": "Ein Glas Milch",
	"Hot drink": "Heißgetränk",
	"Cup without handle": "Tasse ohne Griff",
	"Sake bottle and cup": "Flasche und Tasse für Sake",
	"Champagne": "Champagne",
	"A glass of wine": "ein Becher Wein",
	"A glass of cocktail": "Ein Glas Cocktail",
	"Tropical drink": "Tropisches Getränk",
	"A mug of beer": "Maß",
	"The clink of beer mugs": "Das Klirren von Bierkrügen",
	"The clink of glasses": "Das Klingeln der Gläser",
	"Glass": "Ein Glas",
	"A cup with a straw": "Tasse mit Strohhalm",
	"Chopsticks": "Essstäbchen",
	"Fork and knife with plate": "Gabel und Messer mit Teller",
	"Fork and knife": "Gabel und Messer",
	"Spoon": "Ein Löffel",
	"Knife": "Messer",
	"The Amphora": "Amphore",
	"Globe Europe-Africa": "Globus Europa-Afrika",
	"The Globe of America": "Der Globus Amerika",
	"Globe Asia-Australia": "Globus Asien-Australien",
	"A globe with meridians": "Globus mit Meridianen",
	"World map": "Weltkarte",
	"Japanese Islands": "Japanische Inseln",
	"Compass": "Kompaß",
	"The snow-capped mountain": "Schneebedeckten Berg",
	"Mountain": "Der Berg",
	"Volcano": "Vulkan",
	"Mount Fuji": "Mount Fuji",
	"Camping": "Camping",
	"Beach with an umbrella": "Strand mit Sonnenschirm",
	"Desert": "Wüste",
	"An uninhabited island": "unbewohnte Insel",
	"National Park": "Nationalpark",
	"Stadium": "Stadion",
	"A classic building": "Klassisches Gebäude",
	"Building construction": "Bau von Gebäuden",
	"Bricks": "Ziegel",
	"Home buildings": "Hausbauten",
	"The abandoned building of the house": "Verlassenes Hausgebäude",
	"Building a house": "Hausbau",
	"House with garden": "Haus mit Garten",
	"Office building": "Bürohaus",
	"Japan Post": "Japan Post",
	"European Post": "Europäische Post",
	"Hospital": "Das Krankenhaus",
	"Bank": "Die Bank",
	"Hotel": "Das Hotel",
	"The Hotel of Love": "Hotel der Liebe",
	"Shop near the house": "Shop am Haus",
	"School": "Die Schule",
	"Department Store": "Kaufhaus",
	"Factory": "Die Fabrik",
	"Japanese Castle": "Japanisches Schloss",
	"European Castle": "Europäisches Schloss",
	"Registry office": "Standesamt",
	"Tokyo Tower": "Tokyo Tower",
	"statue of liberty": "Freiheitsstatue",
	"Church": "Die Kirche",
	"Mosque": "Die Moschee",
	"The Synagogue": "Synagoge",
	"Shinto Shrine": "Shinto-Schrein",
	"The Kaaba": "Kaaba",
	"Fountain": "Der Brunnen",
	"Tent": "Zelt",
	"Foggy": "Neblige",
	"A night with stars": "Eine Nacht mit Sternen",
	"Urban landscape": "Stadtbild",
	"Sunrise over the mountains": "Sonnenaufgang über den Bergen",
	"Sunrise over the water": "Sonnenaufgang über dem Wasser",
	"Urban landscape at dusk": "Stadtbild in der Dämmerung",
	"Sunset over buildings": "Sonnenuntergang über Gebäuden",
	"The bridge at night": "Brücke bei Nacht",
	"Hot springs": "Therme",
	"The Milky Way": "Milchstraße",
	"The Carousel Horse": "Karussellpferd",
	"Ferris wheel": "Riesenrad",
	"Roller Coaster": "Achterbahn",
	"Barbershop": "Friseursalon",
	"Circus tent": "Zirkuszelt",
	"Steam train": "Lokomotive",
	"Railway carriage": "Eisenbahnwaggon",
	"High-speed train": "Schnellzug",
	"Bullet-nosed Bullet Train": "Hochgeschwindigkeitszug mit kugelförmiger Nase",
	"Railway": "Eisenbahn",
	"Metro": "U-Bahn",
	"High-speed tram": "Schnellstraßenbahn",
	"Station": "Bahnhof",
	"Tram": "Straßenbahn",
	"Monorail": "Einschienenbahn",
	"Mountain Railway": "Bergbahn",
	"Tram car": "Straßenbahnwagen",
	"Bus": "Der Bus",
	"An approaching bus": "Herannahender Bus",
	"Trolleybus": "O-Bus",
	"Minibus": "Minibus",
	"Ambulance": "Rettungsdienst",
	"Fire truck": "Feuerwehrauto",
	"Police car": "Polizeifahrzeug",
	"An approaching police car": "Herannahendes Polizeiauto",
	"Taxi": "Taxi",
	"An approaching taxi": "Ein sich näherndes Taxi",
	"Car": "Ein Auto",
	"An approaching car": "Herannahendes Auto",
	"A recreational vehicle": "Auto zum Ausruhen",
	"Delivery Truck": "Lieferwagen",
	"Articulated truck": "Gelenk-LKW",
	"Tractor": "Traktor",
	"Racing car": "Rennwagen",
	"Racing Motorcycle": "Rennmaschine",
	"Scooter": "Roller",
	"Bicycle": "Fahrrad",
	"Skateboard": "Skateboard",
	"Bus stop": "Bushaltestelle",
	"Motorway": "Autobahn",
	"Railway track": "Gleis",
	"Oil barrel": "Ölfass",
	"Refill": "Auftankung",
	"Police Car Beacons": "Leuchtfeuer eines Polizeiautos",
	"Horizontal traffic light": "Horizontale Ampel",
	"Vertical traffic light": "Vertikale Ampel",
	"The octagonal sign": "Achteckiges Zeichen",
	"Building sign": "Bauschild",
	"Anchor": "Anker",
	"Sailboat": "Segelboot",
	"Kanoya": "Kanoya",
	"High-speed boat": "Schnellboot",
	"Passenger ship": "Fahrgastschiff",
	"Ferryboat": "Fährschiff",
	"Motor boat": "Motorboot",
	"Ship": "Das Schiff",
	"Airplane": "Das Flugzeug",
	"A small plane": "Kleines Flugzeug",
	"Flight departure": "Abflug des Flugzeugs",
	"Arrival of the plane": "Ankunft des Flugzeugs",
	"The seat": "Sitz",
	"Helicopter": "Hubschrauber",
	"Overhead railway": "Hängende Eisenbahn",
	"Mountain Cable Car": "Bergseilbahn",
	"Cable car": "Seilbahn",
	"Satellite": "Satellit",
	"Rocket": "Rakete",
	"Flying saucer": "Untertasse",
	"Call": "Anruf",
	"Luggage": "Gepäck",
	"The Hourglass": "Sanduhr",
	"Hourglass with loose sand": "Sanduhr mit losem Sand",
	"Watch": "Armbanduhr",
	"Alarm": "Wecker",
	"Stopwatch": "Stoppuhr",
	"Timer": "Timer",
	"The clock on the mantelpiece": "Uhr auf dem Kaminsims",
	"The dial is twelve o'clock": "Zifferblatt Zwölf Uhr",
	"The dial is half past one": "Zifferblatt Halb zwei",
	"The dial is One emergency": "Zifferblatt Eine Herzfrequenz",
	"The dial is two o'clock": "Zifferblatt Zwei Stunden",
	"The dial is half past two": "Zifferblatt Halb drei",
	"The dial is three o'clock": "Zifferblatt Drei Stunden",
	"The dial is half past three": "Zifferblatt Halb vier",
	"The dial is four o'clock": "Zifferblatt Vier Stunden",
	"The dial is half past four": "Zifferblatt Halb fünf",
	"The dial is five o'clock": "Zifferblatt Fünf Uhr",
	"The dial is half past five": "Zifferblatt Halb sechs",
	"The dial is six o'clock": "Sechs-Uhr-Zifferblatt",
	"The dial is half past six": "Zifferblatt Halb sieben",
	"The dial is Seven o'clock": "Zifferblatt Sieben Uhr",
	"The dial is half past seven": "Zifferblatt Halb Achtel",
	"The Dial Is Eight O'clock": "Zifferblatt Acht Uhr",
	"The dial is half past eight": "Zifferblatt Halb neun",
	"The dial is Nine o'clock": "Zifferblatt Neun Uhr",
	"The dial is half past nine": "Halbes zehntes Zifferblatt",
	"The dial is Ten o'clock": "Zifferblatt Zehn Uhr",
	"The dial is half past ten": "Zifferblatt Halbes Zwölftel",
	"The dial is eleven o'clock": "Elf-Uhr-Zifferblatt",
	"The symbol of the new moon": "Symbol des Neumondes",
	"The symbol of the growing crescent moon": "Das Symbol des wachsenden Halbmondes",
	"The symbol of the first quarter of the Moon": "Symbol des ersten Viertels des Mondes",
	"The symbol of the waxing Moon": "Das Symbol des wachsenden Mondes",
	"The Symbol of the Full Moon": "Vollmond-Symbol",
	"The symbol of the waning Moon": "Das Symbol des abnehmenden Mondes",
	"The symbol of the last quarter of the moon": "Symbol für das letzte Viertel des Mondes",
	"The symbol of the waning crescent": "Das Symbol des abnehmenden Halbmondes",
	"The Crescent Moon": "Halbmond",
	"A new moon with a face": "Neumond mit Gesicht",
	"The first quarter of the moon with a face": "Das erste Viertel des Mondes mit dem Gesicht",
	"The last quarter of the Moon with a face": "Das letzte Viertel des Mondes mit dem Gesicht",
	"Thermometer": "Thermometer",
	"The Sun With Rays": "Sonne Mit Strahlen",
	"Full Moon With A Face": "Vollmond Mit Gesicht",
	"The sun with a face": "Sonne mit Gesicht",
	"The white middle Star": "Weißer mittlerer Stern",
	"A Glowing Star": "Leuchtender Stern",
	"Shooting Star": "Sternschnuppe",
	"Cloud": "Die Wolke",
	"The sun behind the cloud": "Die Sonne hinter der Wolke",
	"Thundercloud and rain": "Gewitterwolke und Regen",
	"A White Sun with a Small Cloud": "Weiße Sonne mit einer kleinen Wolke",
	"White Sun Behind A Cloud": "Weiße Sonne Hinter Einer Wolke",
	"White sun behind a cloud with rain": "Weiße Sonne hinter einer Wolke mit Regen",
	"A cloud with rain": "Wolke mit Regen",
	"A cloud with snow": "Wolke mit Schnee",
	"A cloud with lightning": "Wolke mit Blitz",
	"Tornado cloud": "Wolke mit Tornado",
	"Fog": "Der Nebel",
	"A face blown by the wind": "Vom Wind geblasenes Gesicht",
	"Cyclone": "Zyklonanlage",
	"Rainbow": "Regenbogen",
	"Closed umbrella": "Geschlossener Regenschirm",
	"Umbrella": "Regenschirm",
	"Umbrella with raindrops": "Regenschirm mit Regentropfen",
	"An umbrella on the ground": "Regenschirm auf dem Boden",
	"The high voltage sign": "Hochspannungszeichen",
	"Snowflake": "Schneeflocke",
	"Snowman": "Schneemann",
	"A snowman without snow": "Schneemann ohne Schnee",
	"The Comet": "Komet",
	"Fire": "Das Feuer",
	"A drop": "Ein Tropfen",
	"Water wave": "Wasserwelle",
	"Jack-o'-lanterns": "Jack-Laterne",
	"Christmas tree": "Weihnachtsbaum",
	"Fireworks display": "Feuerwerk",
	"Bengal fire": "Wunderkerze",
	"Firecracker": "Feuerwerkskörper",
	"Sparks": "Funken",
	"Air balloon": "Luftballon",
	"A party cracker": "Party-Flapper",
	"A ball of confetti": "Konfetti-Ballon",
	"The Tanabata Tree": "Tanabat-Baum",
	"Pine ornaments": "Kiefernschmuck",
	"Japanese dolls": "Japanische Puppen",
	"Carp Streamer": "Karpfen-Streamer",
	"Wind Music": "Musik des Windes",
	"Moon Viewing Ceremony": "Die Zeremonie der Bewunderung des Mondes",
	"Red gift Envelope": "Roter Geschenkumschlag",
	"Tape": "Band",
	"A packaged gift": "Geschenk verpackt",
	"Reminder Feed": "Erinnerungsband",
	"Entrance fees": "Eintrittskarte",
	"Ticket": "Fahrkarte",
	"Military Medal": "Militärische Medaille",
	"Cup": "Becher",
	"Sports medal": "Sportmedaille",
	"Medal for the first place": "Medaille für den ersten Platz",
	"Medal for the second place": "Medaille für den zweiten Platz",
	"Medal for the third place": "Medaille für den dritten Platz",
	"football": "Fußball",
	"Baseball ball": "Baseball-Ball",
	"Softball ball": "Softball",
	"Basketball ball": "Basketball",
	"A volleyball ball": "Volleyball",
	"An American football ball": "American Football Ball",
	"A Rugby ball": "Rugby-Ball",
	"Tennis racket and ball": "Tenisschläger und Ball",
	"The Flying Disc": "Fliegende Scheibe",
	"Bowling": "Bowling",
	"Cricket bat and ball": "Cricket-Schläger und -Ball",
	"Field hockey stick and ball": "Hockeyschläger und Rasenball",
	"Hockey stick and puck": "Hockeyschläger und Puck",
	"A club and a lacrosse ball": "Putter und Lacrosse-Ball",
	"Table tennis racket and ball": "Schläger und Tischtennisball",
	"Badminton racket and shuttlecock": "Badminton Schläger und Federball",
	"Boxing glove": "Boxhandschuh",
	"Martial Arts Uniforms": "Kampfkunstuniformen",
	"Paved gates": "Hockeytor",
	"Golf Flags": "Flaggen im Golf",
	"Skates": "Schlittschuhe",
	"Fishing rod and fish": "Angelrute und Fisch",
	"Running T-shirt": "T-Shirt zum Laufen",
	"Skis and ski boots": "Ski und Skischuhe",
	"Sleigh": "Schlitten",
	"Stone for curling": "Curling-Stein",
	"Direct hit": "Volltreffer",
	"Billiard": "Billard",
	"The Crystal Ball": "Kristallkugel",
	"Nazar's Amulet": "Amulett von Nazar",
	"Video game": "Videospiel",
	"The joystick": "Joystick",
	"Slot machine": "Spielautomat",
	"The game cube": "Spielwürfel",
	"A piece of the puzzle": "Ein Stück Puzzle",
	"Teddy bear": "Teddybär",
	"The Suit of Spades": "Anzug Peaks",
	"Suit of Hearts": "Würmer-Anzug",
	"The Bubi Suit": "Bubi Anzug",
	"The suit of the Cross": "Taufe Anzug",
	"The Black pawn": "Schwarzer Bauer",
	"The Joker Playing card": "Joker Spielkarte",
	"Mahjong Tile Red Dragon": "Rote Drachen Mahjong Fliesen",
	"Floral Playing Cards": "Blumenspielkarten",
	"Theatrical masks": "Theatermasken",
	"Framed painting": "Gerahmtes Bild",
	"The artist's palette": "Die Palette des Künstlers",
	"A Spool of Thread": "Garnrolle",
	"A ball of yarn": "Gewirr aus Garn",
	"Uh-huh": "E-e",
	"Kite": "Drachen",
	"Skydiver": "Fallschirmspringer",
	"The Boomerang": "Bumerang",
	"The magic wand": "Zauberstab",
	"Pinata": "Pinata",
	"Matryoshka dolls": "Matrjoschkas",
	"Glasses": "Brille",
	"Black glasses": "Schwarze Brille",
	"Scuba Diver's Mask": "Tauchermaske",
	"Laboratory (doctor's) coat": "Laborkittel (Doktor)",
	"Tie": "Krawatte",
	"T-shirt": "T-Shirt",
	"Jeans": "Jeans",
	"Scarf": "Schal",
	"Gloves": "Handschuhe",
	"Coat": "Mantel",
	"Socks": "Socken",
	"Dress": "Kleid",
	"Kimano": "Kimano",
	"Bikini (swimsuit)": "Bikini (Badeanzug)",
	"Women's bathrobe": "Damen Bademantel",
	"Wallet": "Geldtasche",
	"Handbag": "Handtasche",
	"The pouch": "Säckchen",
	"Shopping Bags": "Einkaufspakete",
	"School backpack": "Schulrucksack",
	"Men's shoes": "Herrenschuhe",
	"Sports shoes": "Sportschuhe",
	"Hiking boots": "Wanderschuhe",
	"Women's Flat Shoes": "Damenschuhe\nflache Sohle",
	"High-heeled shoes": "Schuhe\nmit hohen Absätzen",
	"Women's Sandals": "Damen Sandalen",
	"Women's boots": "Damen Stiefel",
	"Crown": "Krone",
	"Women's Panama": "Panama der Frauen",
	"Top hat (male)": "Zylinder (männlich)",
	"Graduate's hat": "Die Kappe des Absolventen",
	"Baseball cap": "Baseballmütze",
	"Helmet with a white cross": "Helm mit weißem Kreuz",
	"Prayer beads": "Rosenkranz zum Beten",
	"Lipstick (sponge)": "Lippenstift (Lippenstift)",
	"Ring": "Der Ring",
	"A precious stone": "Edelstein",
	"Sound is prohibited": "Ton ist verboten",
	"The speaker is off": "Der Lautsprecher ist ausgeschaltet",
	"Speaker at minimum volume": "Lautsprecher bei minimaler Lautstärke",
	"Speaker at maximum volume": "Lautsprecher bei maximaler Lautstärke",
	"Speaker for notification": "Lautsprecher für Alarm",
	"Megafon": "Megaphon",
	"Postal Horn": "Posthorn",
	"Bell": "Glocke",
	"The bell is forbidden": "Die Glocke ist verboten",
	"Musical score": "Musikalische Partitur",
	"Musical note": "Musiknote",
	"Musical notes": "Musiknote",
	"Studio Microphone": "Studiomikrofon",
	"Slider control": "Schieberegler",
	"Control knobs": "Steuergriff",
	"Microphone": "Mikrofon",
	"Headphones": "Kopfhörer",
	"Radio": "Das Radio",
	"The saxophone": "Saxophon",
	"Guitar": "Die Gitarre",
	"Musical keyboard": "Musikalische Tastatur",
	"Musical Trumpet": "Musikalische Trompete",
	"Violin": "Violine",
	"A drum with drumsticks": "Trommel mit Trommelstäbchen",
	"Mobile phone": "Handy",
	"Mobile phone receiving a call": "Handy Empfang eines Anrufs",
	"Disk Phone Number": "Disk-Telefon",
	"The handset": "Hörer",
	"The pager": "Pager",
	"Fax number": "Fax",
	"Battery": "Batterie",
	"Electric plug": "Elektrischer Stecker",
	"A laptop": "Ein Laptop",
	"Computer": "Computer",
	"Printer": "Der Drucker",
	"Keyboard": "Die Tastatur",
	"Three-button mouse": "Maus mit drei Tasten",
	"Trackball": "Trackball",
	"Minidisc": "Minidisk",
	"3.5\" Floppy Disk 1.44Mb": "3.5\" Diskette 1,44MB",
	"Optical Disc CD": "Optische CD",
	"Optical Disc DVD": "Optische DVD",
	"Accounts": "Abakus",
	"Movie Camera": "Filmkamera",
	"The movie": "Filmstreifen",
	"Filmoscope (projector)": "Filmoskop (Projektor)",
	"The movie Cracker": "Kinobaumwolle",
	"TV": "Fernseher",
	"The camera": "Kamera",
	"Camera with flash light": "Kamera mit Blitzlicht",
	"Video camera": "Video Kamera",
	"Video tape": "Videokassette",
	"Healing glass with a stream on the left": "UV-Glas\nmit Bach links",
	"Healing glass with a stream on the right": "UV-Glas\nmit dem Bach rechts",
	"A Burning Candle": "Brennende Kerze",
	"Electric light bulb": "Glühbirne",
	"Electric flashlight": "Elektrische Taschenlampe",
	"The red lantern": "Rote Laterne",
	"A notebook with a decorative cover": "Notizblock mit dekorativem Cover",
	"The Closed book": "Geschlossenes Buch",
	"An open book": "Offenes Buch",
	"The Green Book": "Grünbuch",
	"The Blue Book": "Blaubuch",
	"The Orange Book": "Das orangefarbene Buch",
	"Books": "Die Bücher",
	"Notepad": "Notizbuch",
	"Accounting Book": "Geschäftsbuch",
	"The Curl page": "Curl-Seite",
	"A page with swirls at the top and bottom": "Seite mit Locken oben und unten",
	"The page is face up": "Seite nach oben verdeckt",
	"Newspaper": "Zeitung",
	"A rolled-up newspaper": "In eine Röhre gerollte Zeitung",
	"Bookmarks Tabs": "Lesezeichen Tabs",
	"Bookmark": "Lesezeichen",
	"Label": "Etikett",
	"The money Bag": "Geldsack",
	"A banknote with a yen sign": "Banknote mit Yen-Zeichen",
	"A banknote with a dollar sign": "Banknote mit Dollarzeichen",
	"Banknote with the euro sign": "Banknote mit Euro-Zeichen",
	"A banknote with a pound sign": "Banknote mit Pfundzeichen",
	"Money with wings": "Geld mit Flügeln",
	"Credit card": "Kreditkarte",
	"Receipt": "Die Quittung",
	"Chart with an uptrend and a yen sign": "Graph mit Aufwärtstrend und Yen-Zeichen",
	"Currency exchange": "Geldwechsel",
	"Heavy Dollar sign": "Schweres Dollarzeichen",
	"The envelope": "Briefumschlag",
	"The email symbol": "E-Mail-Symbol",
	"Incoming envelope": "Eingehender Umschlag",
	"An envelope with a downward arrow on top": "Umschlag mit Pfeil nach unten von oben",
	"Outgoing Mail tray": "Fach für ausgehende E-Mails",
	"Incoming Message tray": "Fach für eingehende Nachrichten",
	"Packaging": "Verpackung",
	"A closed mailbox with a raised flag": "Ein geschlossener Briefkasten mit gehobener Flagge",
	"A closed mailbox with a lowered flag": "Geschlossenes Postfach mit ausgelassener Flagge",
	"An open mailbox with a raised flag": "Offener Briefkasten mit gehobener Flagge",
	"An open mailbox with the flag down": "Offener Briefkasten mit ausgelassener Flagge",
	"Mailbox": "Briefkasten",
	"The ballot box": "Wahlurne mit Stimmzettel",
	"Pencil": "Ein Bleistift",
	"Fountain Pen": "Füllfederhalter",
	"Lower left fountain pen": "Füllfederhalter unten links",
	"Lower left ballpoint pen": "Kugelschreiber unten links",
	"Lower left hand": "Pinsel unten links",
	"Lower left pencil": "Bleistift unten links",
	"The memo": "Merkblatt",
	"Briefcase": "Schultasche",
	"Folder with files": "Ordner mit Dateien",
	"An open folder with files": "Ordner mit Dateien öffnen",
	"File dividers": "Trennzeichen für Aktenschränke",
	"Calendar": "Der Kalender",
	"Tear-off calendar": "Abreißkalender",
	"Spiral Notebook": "Notizbuch mit Spirale",
	"Notepad calendar with spiral": "Notizbuch-Kalender mit Spirale",
	"File cabinet": "Kartothek",
	"An uptrend chart": "Aufwärtstrenddiagramm",
	"A chart with a downtrend": "Abwärtstrenddiagramm",
	"Bar chart": "Säulendiagramm",
	"Clipboard": "Zwischenablage",
	"Button": "Knopf",
	"Round button": "Runder Knopf",
	"Paper clip": "Büroklammer",
	"Bound Paper Clips": "Verbundene Büroklammern",
	"Ruler": "Lineal",
	"Triangular ruler": "Dreieckiges Lineal",
	"Scissors": "Schere",
	"The filing cabinet box": "Aktenschachtel",
	"File Cabinet": "Aktenschrank",
	"The wastebasket": "Mülleimer",
	"Castle": "Schloß",
	"An open castle": "Offenes Schloss",
	"Lock with ink pen": "Schloss mit Tintenstift",
	"A closed lock with a key": "Geschlossenes Schloss mit Schlüssel",
	"Key": "Der Schlüssel",
	"The old key": "Alter Schlüssel",
	"A hammer": "Ein Hammer",
	"Pickaxe": "Spitzhacke",
	"Hammer and pickaxe": "Hammer und Spitzhacke",
	"Hammer and wrench": "Hammer und Schraubenschlüssel",
	"Dagger-knife": "Dolch-Messer",
	"Crossed swords": "Gekreuzte Schwerter",
	"Gun": "Pistole",
	"Bow and arrows": "Pfeil und Bogen",
	"Shield": "Schild",
	"Wrench": "Schraubenschlüssel",
	"A bolt with a spike": "Ringschraube",
	"Mechanism": "Mechanismus",
	"Compression": "Kompression",
	"Scales": "Waage",
	"The link symbol": "Link-Symbol",
	"Chains": "Kette",
	"The toolbox": "Werkzeug-Box",
	"Magnet": "Magnet",
	"The alembic": "Destillationswürfel",
	"Test tube": "Reagenzglas",
	"Petri Dish": "Petrischale",
	"The double helix of DNA": "DNA-Doppelhelix",
	"The microscope": "Mikroskop",
	"The telescope": "Teleskop",
	"Satellite dish": "Satellitenantenne",
	"Syringe": "Spritze",
	"The pill": "bittere Pille",
	"Door": "Die Tür",
	"Bed": "Bett",
	"Sofa and lamp": "Sofa und Lampe",
	"Toilet": "Die Toilette",
	"Shower": "Dusche",
	"A bottle of lotion": "Lotion Flasche",
	"Safety Pin": "Sicherheitsnadel",
	"Broomstick": "Besen",
	"Basket": "Korb",
	"A roll of paper": "Papierrolle",
	"A bar of soap": "ein Stück Seife",
	"Sponge": "Schwamm",
	"Fire extinguisher": "Feuerlöscher",
	"Shopping cart": "Einkaufswagen",
	"The symbol of smoking": "Symbol des Rauchens",
	"Coffin": "Der Sarg",
	"Funeral urn": "Bestattungsurne",
	"Moyai statue": "Meine Und",
	"ATM machine": "Geldautomat",
	"Remove the trash": "Entfernen Sie den Müll",
	"Drinking water": "Trinkwasser",
	"Wheelchair": "Rollstuhl",
	"Symbol: Male": "Symbol: Männlich",
	"Symbol: A woman": "Symbol: Frau",
	"Symbol: Child": "Symbol: Kind",
	"The lavatory": "Wasserklosett",
	"Passport control": "Paßkontrolle",
	"Customs": "Zollamt",
	"Baggage claim": "Gepäckausgabe",
	"Luggage storage": "Gepäckaufbewahrung",
	"The warning sign": "Warnzeichen",
	"Children's crossing": "Kinder Übergang",
	"The forbidding sign": "Verbotszeichen",
	"No entry sign": "Schild \"Kein Zutritt»",
	"Bicycles are prohibited": "Fahrräder sind verboten",
	"Smoking is prohibited": "Rauchen ist verboten",
	"Don't litter": "Kein Müll",
	"Non-potable water": "Nicht trinkendes Wasser",
	"Pedestrian traffic is prohibited": "Fußgängerverkehr ist verboten",
	"No cell phones": "Keine Handys",
	"Prohibited Under the age of eighteen": "Unter 18 Jahren verboten",
	"Radiation hazard": "Strahlungsgefahr",
	"Biological hazards": "Biologische Gefahr",
	"Black Arrow Up": "Schwarzer Pfeil nach oben",
	"Northeast Arrow": "Nordost-Pfeil",
	"Black arrow to the right": "Schwarzer Pfeil nach rechts",
	"Southeastern Arrow": "Südost-Pfeil",
	"The black arrow is down": "Schwarzer Pfeil nach unten",
	"Southwest Arrow": "Südwestpfeil",
	"Black arrow to the left": "Schwarzer Pfeil nach links",
	"North-Western Arrow": "Nordwestpfeil",
	"Up-down arrow": "Pfeil nach oben/unten",
	"Left-right arrow": "Pfeil nach links-rechts",
	"Left arrow with hook": "Pfeil nach links mit Haken",
	"Right arrow with hook": "Pfeil nach rechts mit Haken",
	"An arrow pointing to the right, then curving upward": "Nach rechts gerichteter Pfeil,\ndann nach oben biegen",
	"An arrow pointing to the right, then curving downwards": "Nach rechts gerichteter Pfeil,\ndann nach unten biegen",
	"Open circular arrows pointing up and down clockwise": "Offene kreisförmige Pfeile,\nnach oben und unten gerichtet\nim Uhrzeigersinn",
	"Open circular arrows pointing up and down counterclockwise": "Offene kreisförmige Pfeile,\nnach oben und unten gerichtet\ngegen den Uhrzeigersinn",
	"Back with the left arrow on top": "Zurück mit dem Pfeil nach links oben",
	"Finish with the left arrow on top": "Mit dem Pfeil nach links oben beenden",
	"With an exclamation mark and a left-right arrow on top": "Mit einem Ausrufezeichen\nund mit dem Pfeil nach links nach rechts oben",
	"Soon with the arrow to the right at the top": "Bald\nmit dem Pfeil nach rechts oben",
	"Up with the up arrow at the top": "Nach oben\nmit dem Pfeil nach oben oben",
	"A place of worship": "Ein Ort der Anbetung",
	"The symbol of the Atom": "Atom-Symbol",
	"The Om symbol": "Om-Symbol",
	"The Star of David": "Judenstern",
	"The Wheel of Dharma": "Das Dharma-Rad",
	"Yin Yang": "Yin Yang",
	"The Latin Cross": "Lateinisches Kreuz",
	"The Orthodox Cross": "Orthodoxes Kreuz",
	"The star and the crescent moon": "Stern und Halbmond",
	"A symbol of peace": "Symbol des Friedens",
	"Menorah with nine branches": "Menora mit neun Zweigen",
	"A six-pointed star with a dot in the middle": "Sechszackiger Stern mit einem Punkt in der Mitte",
	"Aries": "Widder",
	"Taurus": "Stier",
	"Twins": "Zwillinge",
	"Cancer": "Krebs",
	"Leo": "Ein Löwe",
	"Maid": "Jungfrau",
	"Sagittarius": "Schütze",
	"Capricorn": "Steinbock",
	"Aquarius": "Wassermann",
	"The Ophiuchus": "Ophiuchus",
	"Twisted arrows pointing to the right": "Verdrehte Pfeile,\nnach rechts gerichtet",
	"Round arrows pointing clockwise to the right and left": "Runde Pfeile,\nnach rechts und links im Uhrzeigersinn gerichtet",
	"Round arrows pointing clockwise to the right and left, with a unit superimposed in a circle": "Runde Pfeile,\nim Uhrzeigersinn nach rechts und links gerichtet,\nmit der Überlagerung einer Einheit in einem Becher",
	"A triangle pointing to the right": "Das Dreieck,\nnach rechts gerichtet",
	"A double triangle pointing to the right": "Doppeltes Dreieck,\nnach rechts gerichtet",
	"A double triangle pointing to the right, with a vertical line": "Doppeltes Dreieck,\nnach rechts gerichtet,\nmit einem vertikalen Strich",
	"A triangle pointing to the right with a double vertical line": "Das Dreieck,\nnach rechts gerichtet,\nmit doppelter vertikaler Linie",
	"A triangle pointing to the left": "Das Dreieck,\nnach links gerichtet",
	"A double triangle pointing to the left": "Doppeltes Dreieck,\nnach links gerichtet",
	"A double triangle pointing to the left, with a vertical line": "Doppeltes Dreieck,\nnach links gerichtet,\nmit einem vertikalen Strich",
	"The triangle is upside down": "Dreieck oben nach unten",
	"Double triangle with the top facing up": "Doppeltes Dreieck nach oben",
	"Double triangle with the top facing down": "Doppeltes Dreieck oben nach unten",
	"Double vertical stripe": "Doppelter vertikaler Streifen",
	"The stop square": "Stopp-Quadrat",
	"The recording circle": "Rekord-Kreis",
	"Extraction symbol": "Extraktionssymbol",
	"Movie": "Kino",
	"Low brightness symbol": "Symbol für niedrige Helligkeit",
	"High brightness symbol": "Symbol für hohe Helligkeit",
	"Antenna with a grid": "Antenne mit Gitter",
	"Vibration mode": "Vibrationsmodus",
	"The mobile phone is turned off": "Handy ausgeschaltet",
	"Female sign": "Weibliches Zeichen",
	"The male sign": "Männliches Zeichen",
	"The staff of Aesculapius": "Stab des Esculaps",
	"Permanent paper sign": "Permanentes Papierzeichen",
	"Symbol of recycling": "Recycling-Symbol",
	"Lily Flower": "Lilienblume",
	"The Trident Emblem": "Dreizack-Emblem",
	"Name badge": "Namensschild",
	"Japanese symbol for beginners": "Japanisches Symbol für Anfänger",
	"Heavy big circle": "Schwerer großer Kreis",
	"White bold checkmark": "Weiße, fettige Häkchen",
	"Ballot box with verification": "Wahlurne mit Überprüfung",
	"Heavy check mark": "Schweres Häkchen",
	"Heavy X multiplication": "Schwere X-Multiplikation",
	"Mark the Cross": "Kreuz-Mark",
	"Negative square cross": "Negatives quadratisches Kreuz",
	"Heavy plus sign": "Schweres Pluszeichen",
	"Heavy minus sign": "Schweres Minuszeichen",
	"The sign of heavy division": "Zeichen der schweren Teilung",
	"The Winding Loop": "Lockige Schleife",
	"Double Curly loop": "Doppelte lockige Schleife",
	"The sign of alternating parts": "Zeichen des Teilwechsels",
	"The eight-pointed star": "Achtzackiges Sternchen",
	"Eight-pointed black star": "Achtzackiger schwarzer Stern",
	"Spark": "Funken",
	"Double exclamation mark": "Doppeltes Ausrufezeichen",
	"The exclamation mark of the question": "Fragezeichen ausrufen",
	"Black question mark": "Schwarzes Fragezeichen",
	"A white question mark": "Weißes Fragezeichen",
	"White exclamation mark": "Weißes Ausrufezeichen",
	"The bold exclamation mark symbol": "Symbol für ein fettes Ausrufezeichen",
	"The wavy line": "Wellige Linie",
	"Copyright mark": "Copyright-Zeichen",
	"Registered mark": "Eingetragenes Zeichen",
	"Trademark": "Warenzeichen",
	"The grid sign": "Gitter-Zeichen",
	"The footnote": "Fußnote",
	"The zero sign": "Null-Zeichen",
	"The unity sign": "Zeichen der Einheit",
	"The deuce sign": "Zwei Zeichen",
	"The troika sign": "Zeichen Dreier",
	"The four sign": "Vier-Zeichen",
	"The five sign": "Fünf-Zeichen",
	"The sign of the six": "Sechs Zeichen",
	"The sign of the seven": "Zeichen Sieben",
	"The figure eight sign": "Zeichen Acht",
	"The sign of the nine": "Zeichen neun",
	"The sign of the ten": "Zehn-Zeichen",
	"The ABCD sign": "ABCD-Zeichen",
	"The abcd sign": "ABCD-Zeichen",
	"Sign 1234": "Zeichen 1234",
	"Character input symbol": "Zeichen eingeben",
	"The letter input symbol": "Buchstabeneingabesymbol",
	"Latin capital letter A in a negative square": "Lateinischer Großbuchstabe A\nim negativen Quadrat",
	"Negative square Ab": "Negatives Ab-Quadrat",
	"Latin capital letter B in a negative square": "Lateinischer Großbuchstabe B\nim negativen Quadrat",
	"Square Cl": "Quadratischer Cl",
	"Square Cool": "Quadratisch steil",
	"Squared for free": "Platz frei",
	"Information Symbol": "Informationssymbol",
	"Square ID": "Quadratische ID",
	"Latin capital letter M in a circle": "Lateinischer Großbuchstabe M\nim Kreis",
	"Square New": "Quadratisch Neu",
	"Square NG": "Quadratisches NG",
	"Negative square Latin capital letter O": "Negativ quadratisch\nlateinischer Großbuchstabe O",
	"Square OK": "Quadrat OK",
	"Negative square Latin capital letter P": "Negativ quadratisch\nlateinischer Großbuchstabe P",
	"SOS squared": "SOS im Quadrat",
	"Squared Up with an exclamation mark": "Im Quadrat Nach oben\nmit einem Ausrufezeichen",
	"Squared VS": "Im VS-Quadrat",
	"Coco's Square Katakana": "Coco quadratische Katakana",
	"Square Katakana Sa": "Quadratische Katakana Sa",
	"Square Cjk Unified Ideograph-6708": "Quadratischer Cjk\neinheitlicher Ideograph-6708",
	"Square Cjk Unified Ideograph-6709": "Quadratischer Cjk\neinheitlicher Ideograph-6709",
	"Square Cjk Unified Ideograph-6307": "Quadratischer Cjk\neinheitlicher Ideograph-6307",
	"The advantage of an ideogram in a circle": "Der Vorteil eines Ideogramms im Kreis",
	"Square Cjk Unified Ideograph-5272": "Quadratischer Cjk\neinheitlicher Ideograph-5272",
	"Square Cjk Unified Ideograph-7121": "Quadratischer Cjk\neinheitlicher Ideograph-7121",
	"Square Cjk Unified Ideograph-7981": "Quadratischer Cjk\neinheitlicher Ideograph-7981",
	"A round ideogram To accept": "Rundes Ideogramm annehmen",
	"Square Cjk Unified Ideograph-7533": "Quadratischer Cjk\neinheitlicher Ideograph-7533",
	"Square Cjk Unified Ideograph-6408": "Quadratischer Cjk\neinheitlicher Ideograph-6408",
	"Square Cjk Unified Ideograph-7A7A": "Quadratischer Cjk\neinheitlicher Ideograph-7A7A",
	"Round ideogram Congratulations": "Runde Ideogramm Glückwunsch",
	"The round ideogram is a secret": "Das runde Ideogramm ist das Geheimnis",
	"Square Cjk Unified Ideograph-55B6": "Quadratischer Cjk\neinheitlicher Ideograph-55B6",
	"Square Cjk Unified Ideograph-6E80": "Quadratischer Cjk\neinheitlicher Ideograph-6E80",
	"The big red circle": "Großer roter Kreis",
	"The big blue circle": "Großer blauer Kreis",
	"The middle white circle": "Mittlerer weißer Kreis",
	"The middle black circle": "Mittlerer schwarzer Kreis",
	"A large white square": "Weißes großes Quadrat",
	"A large black square": "Schwarzes großes Quadrat",
	"The black middle square": "Schwarzes mittleres Quadrat",
	"The white middle square": "Weißes mittleres Quadrat",
	"White Medium Small Square": "Weißes mittleres kleines Quadrat",
	"Black Medium Small Square": "Schwarzes mittleres kleines Quadrat",
	"A small white square": "Weißes kleines Quadrat",
	"A small black square": "Schwarzes kleines Quadrat",
	"A large orange diamond": "Großer orange Diamant",
	"The big blue diamond": "Großer blauer Diamant",
	"A small orange diamond": "Kleiner orangefarbener Diamant",
	"A small blue diamond": "Kleiner blauer Diamant",
	"The red triangle is upside down": "Rotes Dreieck oben nach unten",
	"The shape of a diamond with a dot inside": "Rautenform mit Punkt innen",
	"Radio Button": "Radio-Taste",
	"Black square button": "Schwarzer quadratischer Knopf",
	"White square button": "Weißer quadratischer Knopf",
	"The Checkered Flag": "Karierte Flagge",
	"Triangular flag": "Dreieckige Flagge",
	"Crossed flags": "Gekreuzte Fahnen",
	"The Black Flag": "die schwarze Fahne",
	"The White flag": "die weiße Fahne",
	"Rainbow Flag": "Regenbogenfahne",
	"The Flag of the Transgender Community": "Flagge der Transgender-Gemeinschaft",
	"The Pirate Flag": "Piratenflagge",
	"Flag: Ascension Island": "Flagge: An Himmelfahrt",
	"Flag: Andorra": "Flagge: Andorra",
	"Flag: UAE": "Flagge: Vae",
	"Flag: Afghanistan": "Flagge: Afghanistan",
	"Flag: Antigua and Barbuda": "Flagge: Antigua und Barbuda",
	"Flag: Anguilla": "Flagge: Anguilla",
	"Flag: Albania": "Flagge: Albanien",
	"Flag: Armenia": "Flagge: Armenien",
	"Flag: Angola": "Flagge: Angola",
	"Flag: Antarctica": "Flagge: Antarktis",
	"Flag: Argentina": "Flagge: Argentinien",
	"Flag: American Samoa": "Flagge: Amerikanisches Samoa",
	"Flag: Austria": "Flagge: Österreich",
	"Flag: Australia": "Flagge: Australien",
	"Flag: Aruba": "Flagge: Aruba",
	"Flag: Aland Islands": "Flagge: Åland Inseln",
	"Flag: Azerbaijan": "Flagge: Aserbaidschan",
	"Flag: Bosnia and Herzegovina": "Flagge: Bosnien und Herzegowina",
	"Flag: Barbados": "Flagge: Barbados",
	"Flag: Bangladesh": "Flagge: Bangladesch",
	"Flag: Belgium": "Flagge: Belgien",
	"Flag: Burkina Faso": "Flagge: Burkina Faso",
	"Flag: Bulgaria": "Flagge: Bulgarien",
	"Flag: Bahrain": "Flagge: Bahrain",
	"Flag: Burundi": "Flagge: Burundi",
	"Flag: Benin": "Flagge: Benin",
	"Flag: Saint Barthélémy": "Flagge: Saint-Barthélemy",
	"Flag: Bermuda": "Flagge: Bermuda-Inseln",
	"Flag: Brunei": "Flagge: Brunei",
	"Flag: Bolivia": "Flagge: Bolivien",
	"Flag: Bonaire, Sint Eustatius and Saba": "Flagge: Bonaire, Sint-Estatius und Saba",
	"Flag: Brazil": "Flagge: Brasilien",
	"Flag: Bahamas": "Flagge: Bahamas",
	"Flag: Bhutan": "Flagge: Bhutan",
	"Flag: O-In Bouvet": "Flagge: Oh-Im Bouvet",
	"Flag: Botswana": "Flagge: Botswana",
	"Flag: Belarus": "Flagge: Belarus",
	"Flag: Belize": "Flagge: Belize",
	"Flag: Canada": "Flagge: Kanada",
	"Flag: Coconut Islands": "Flagge: Kokosnuss-Inseln",
	"Flag: Congo - Kinshasa": "Flagge: Kongo - Kinshasa",
	"Flag: Central African Republic": "Flagge: Zentralafrikanische Republik",
	"Flag: Congo - Brazzaville": "Flagge: Kongo - Brazzaville",
	"Flag: Switzerland": "Flagge: Schweiz",
	"Flag: Ivory Coast": "Flagge: Elfenbeinküste",
	"Flag: Cook Island": "Flagge: O-Wa Cook",
	"Flag: Chile": "Flagge: Chile",
	"Flag: Cameroon": "Flagge: Kamerun",
	"Flag: China": "Flagge: China",
	"Flag: Colombia-": "Flagge: Kolumbien-",
	"Flag: Clipperton Island": "Flagge: O-In Clipperton",
	"Flag: Costa Rica": "Flagge: Costa Rica",
	"Flag: Cuba": "Flagge: Kuba",
	"Flag: Cape Verde": "Flagge: Kap Verde",
	"Flag: Curacao": "Flagge: Curacao",
	"Flag: Christmas Island": "Flagge: Über Weihnachten",
	"Flag: Cyprus": "Flagge: Zypern",
	"Flag: Czech Republic": "Flagge: Tschechien",
	"Flag: Germany": "Flagge: Deutschland",
	"Flag: Diego Garcia": "Flagge: Diego-Garcia",
	"Flag: Djibouti": "Flagge: Dschibuti",
	"Flag: Denmark": "Flagge: Dänemark",
	"Flag: Dominica": "Flagge: Dominica",
	"Flag: Dominican Republic": "Flagge: Dominikanische Republik",
	"Flag: Algeria": "Flagge: Algerien",
	"Flag: Ceuta and Melilla": "Flagge: Ceuta und Melilla",
	"Flag: Ecuador": "Flagge: Ecuador",
	"Flag: Estonia": "Flagge: Estland",
	"Flag: Egypt": "Flagge: Ägypten",
	"Flag: Western Sahara": "Flagge: Westliche Sahara",
	"Flag: Eritrea": "Flagge: Eritrea",
	"Flag: Spain": "Flagge: Spanien",
	"Flag: Ethiopia": "Flagge: Äthiopien",
	"Flag: European Union": "Flagge: Europäische Union",
	"Flag: Finland": "Flagge: Finnland",
	"Flag: Fiji": "Flagge: Fidschi",
	"Flag: Falkland Islands": "Flagge: Falklandinseln",
	"Flag: Federated States of Micronesia": "Flagge: Föderierte Staaten von Mikronesien",
	"Flag: Faroe Islands": "Flagge: Färöer-Inseln",
	"Flag: France": "Flagge: Frankreich",
	"Flag: Gabon": "Flagge: Gabun",
	"Flag: United Kingdom": "Flagge: Vereinigtes Königreich",
	"Flag: Grenada": "Flagge: Grenada",
	"Flag: Georgia": "Flagge: Georgien",
	"Flag: French Guiana": "Flagge: Französisch-Guayana",
	"Flag: Guernsey": "Flagge: Guernsey",
	"Flag: Ghana": "Flagge: Ghana",
	"Flag: Gibraltar": "Flagge: Gibraltar",
	"Flag: Greenland": "Flagge: Grönland",
	"Flag: Gambia": "Flagge: Gambia",
	"Flag: Guinea": "Flagge: Guinea",
	"Flag: Guadeloupe": "Flagge: Guadeloupe",
	"Flag: Equatorial Guinea": "Flagge: Äquatorialguinea",
	"Flag: Greece": "Flagge: Griechenland",
	"Flag: South Georgia and the South Sandwich Islands": "Flagge: Südgeorgien und südliche Sandwiches",
	"Flag: Guatemala": "Flagge: Guatemala",
	"Flag: Guam": "Flagge: Guam",
	"Flag: Guinea-Bissau": "Flagge: Guinea-Bissau",
	"Flag: Guyana": "Flagge: Guyana",
	"Flag: Hong Kong (SAR)": "Flagge: Hongkong (SAR)",
	"Flag: Heard and McDonald Islands": "Flagge: Oh Heard und McDonald",
	"Flag: Honduras": "Flagge: Honduras",
	"Flag: Croatia": "Flagge: Kroatien",
	"Flag: Haiti": "Flagge: Haiti",
	"Flag: Hungary": "Flagge: Ungarn",
	"Flag: Canary Islands": "Flagge: Kanarische Inseln",
	"Flag: Indonesia": "Flagge: Indonesien",
	"Flag: Ireland": "Flagge: Irland",
	"Flag: Israel": "Flagge: Israel",
	"Flag: Isle of Man": "Flagge: O-In Maine",
	"Flag: India": "Flagge: Indien",
	"Flag: British Indian Ocean Territory": "Flagge: Britisches Territorium im Indischen Ozean",
	"Flag: Iraq": "Flagge: Irak",
	"Flag: Iran": "Flagge: Iran",
	"Flag: Iceland": "Flagge: Island",
	"Flag: Italy": "Flagge: Italien",
	"Flag: Jersey": "Flagge: Jersey",
	"Flag: Jamaica": "Flagge: Jamaika",
	"Flag: Jordan": "Flagge: Jordanien",
	"Flag: Japan": "Flagge: Japan",
	"Flag: Kenya": "Flagge: Kenia",
	"Flag: Kyrgyzstan": "Flagge: Kirgisistan",
	"Flag: Cambodia": "Flagge: Kambodscha",
	"Flag: Kiribati": "Flagge: Kiribati",
	"Flag: Comoros": "Flagge: Komoren",
	"Flag: Saint Kitts and Nevis": "Flagge: St. Kitts und Nevis",
	"Flag: North Korea": "Flagge: DVRK",
	"Flag: Republic of Korea": "Flagge: Republik Korea",
	"Flag: Kuwait": "Flagge: Kuwait",
	"Flag: Cayman Island": "Flagge: Kaiman",
	"Flag: Kazakhstan": "Flagge: Kasachstan",
	"Flag: Laos": "Flagge: Laos",
	"Flag: Lebanon": "Flagge: Libanon",
	"Flag: Saint Lucia": "Flagge: St. Lucia",
	"Flag: Liechtenstein": "Flagge: Liechtenstein",
	"Flag: Sri Lanka": "Flagge: Sri Lanka",
	"Flag: Liberia": "Flagge: Liberia",
	"Flag: Lesotho": "Flagge: Lesotho",
	"Flag: Lithuania": "Flagge: Litauen",
	"Flag: Luxembourg": "Flagge: Luxemburg",
	"Flag: Latvia": "Flagge: Lettland",
	"Flag: Libya": "Flagge: Libyen",
	"Flag: Morocco": "Flagge: Marokko",
	"Flag: Monaco": "Flagge: Monaco",
	"Flag: Moldova": "Flagge: Moldawien",
	"Flag: Montenegro": "Flagge: Montenegro",
	"Flag: Saint Martin": "Flagge: Saint-Martin",
	"Flag: Madagascar": "Flagge: Madagaskar",
	"Flag: Marshall Islands": "Flagge: Marshall-Inseln",
	"Flag: North Macedonia": "Flagge: Nord-Mazedonien",
	"Flag: Mali": "Flagge: Mali",
	"Flag: Myanmar (Burma)": "Flagge: Myanmar (Burma)",
	"Flag: Mongolia": "Flagge: Mongolei",
	"Flag: Macau (Sar)": "Flagge: Macao (Sar)",
	"Flag: Northern Mariana Islands": "Flagge: Nördliche Marianische Inseln",
	"Flag: Martinique": "Flagge: Martinique",
	"Flag: Mauritania": "Flagge: Mauretanien",
	"Flag: Montserrat": "Flagge: Montserrat",
	"Flag: Malta": "Flagge: Malta",
	"Flag: Mauritius": "Flagge: Mauritius",
	"Flag: Maldives": "Flagge: Malediven",
	"Flag: Malawi": "Flagge: Malawi",
	"Flag: Mexico": "Flagge: Mexiko",
	"Flag: Malaysia": "Flagge: Malaysia",
	"Flag: Mozambique": "Flagge: Mosambik",
	"Flag: Namibia": "Flagge: Namibia",
	"Flag: New Caledonia": "Flagge: Neukaledonien",
	"Flag: Niger": "Flagge: Niger",
	"Flag: Norfolk Island": "Flagge: O-In Norfolk",
	"Flag: Nigeria": "Flagge: Nigeria",
	"Flag: Nicaragua": "Flagge: Nicaragua",
	"Flag: Netherlands": "Flagge: Niederlande",
	"Flag: Norway": "Flagge: Norwegen",
	"Flag: Nepal": "Flagge: Nepal",
	"Flag: Nauru": "Flagge: Nauru",
	"Flag: Niue": "Flagge: Niue",
	"Flag: New Zealand": "Flagge: Neuseeland",
	"Flag: Oman": "Flagge: Oman",
	"Flag: Panama": "Flagge: Panama",
	"Flag: Peru": "Flagge: Peru",
	"Flag: French Polynesia": "Flagge: Französisch-Polynesien",
	"Flag: Papua New Guinea": "Flagge: Papua-Neuguinea",
	"Flag: Philippines": "Flagge: Philippinen",
	"Flag: Pakistan": "Flagge: Pakistan",
	"Flag: Poland": "Flagge: Polen",
	"Flag: Saint Pierre and Miquelon": "Flagge: Saint-Pierre und Miquelon",
	"Flag: Pitcairn Island": "Flagge: O-Wa Pitcairn",
	"Flag: Puerto Rico": "Flagge: Puerto Rico",
	"Flag: Palestinian Territories": "Flagge: Palästinensische Gebiete",
	"Flag: Portugal": "Flagge: Portugal",
	"Flag: Palau": "Flagge: Palau",
	"Flag: Paraguay": "Flagge: Paraguay",
	"Flag: Qatar": "Flagge: Katar",
	"Flag: Reunion": "Flagge: Reunion",
	"Flag: Romania": "Flagge: Rumänien",
	"Flag: Serbia": "Flagge: Serbien",
	"Flag: Russia": "Flagge: Russland",
	"Flag: Rwanda": "Flagge: Ruanda",
	"Flag: Saudi Arabia": "Flagge: Saudi-Arabien",
	"Flag: Solomon Islands": "Flagge: Salomonen",
	"Flag: Seychelles": "Flagge: Seychellen",
	"Flag: Sudan": "Flagge: Sudan",
	"Flag: Sweden": "Flagge: Schweden",
	"Flag: Singapore": "Flagge: Singapur",
	"Flag: St. Helena Island": "Flagge: O-In St. Helena",
	"Flag: Slovenia": "Flagge: Slowenien",
	"Flag: Svalbard and Jan Mayen": "Flagge: Svalbard und Jan Mayen",
	"Flag: Slovakia": "Flagge: Slowakei",
	"Flag: Sierra Leone": "Flagge: Sierra Leone",
	"Flag: San Marino": "Flagge: San Marino",
	"Flag: Senegal": "Flagge: Senegal",
	"Flag: Somalia": "Flagge: Somalia",
	"Flag: Suriname": "Flagge: Suriname",
	"Flag: South Sudan": "Flagge: Südsudan",
	"Flag: Sao Tome and Principe": "Flagge: São Tomé und Príncipe",
	"Flag: El Salvador": "Flagge: El Salvador",
	"Flag: Sint Maarten": "Flagge: Sint-Martin",
	"Flag: Syria": "Flagge: Syrien",
	"Flag: Eswatini": "Flagge: Eswatini",
	"Flag: Tristan Da Cunha": "Flagge: Tristan Da Cunha",
	"Flag: Turks and Caicos Islands": "Flagge: Turks und Caicos",
	"Flag: Chad": "Flagge: Tschad",
	"Flag: French Southern Territories": "Flagge: Französische Südgebiete",
	"Flag: Togo": "Flagge: Togo",
	"Flag: Thailand": "Flagge: Thailand",
	"Flag: Tajikistan": "Flagge: Tadschikistan",
	"Flag: Tokelau": "Flagge: Tokelau",
	"Flag: East Timor": "Flagge: Osttimor",
	"Flag: Turkmenistan": "Flagge: Turkmenistan",
	"Flag: Tunis": "Flagge: Tunesien",
	"Flag: Tonga": "Flagge: Tonga",
	"Flag: Turkey": "Flagge: Türkei",
	"Flag: Trinidad and Tobago": "Flagge: Trinidad und Tobago",
	"Flag: Tuvalu": "Flagge: Tuvalu",
	"Flag: Taiwan": "Flagge: Taiwan",
	"Flag: Tanzania": "Flagge: Tansania",
	"Flag: Ukraine": "Flagge: Ukraine",
	"Flag: Uganda": "Flagge: Uganda",
	"Flag: Outer Small Islands (USA)": "Flagge: Äußere Kleine Inseln (USA)",
	"Flag: United Nations": "Flagge: Vereinten Nationen",
	"Flag: United States": "Flagge: Vereinigte Staaten",
	"Flag: Uruguay": "Flagge: Uruguay",
	"Flag: Uzbekistan": "Flagge: Usbekistan",
	"Flag: Vatican City": "Flagge: Vatikan",
	"Flag: Saint Vincent and the Grenadines": "Flagge: St. Vincent und die Grenadinen",
	"Flag: Venezuela": "Flagge: Venezuela",
	"Flag: Virgin Islands (Great Britain)": "Flagge: Virgin Islands (Vereinigtes Königreich)",
	"Flag: Virgin Islands (USA)": "Flagge: Virgin Islands (USA)",
	"Flag: Vietnam": "Flagge: Vietnam",
	"Flag: Vanuatu": "Flagge: Vanuatu",
	"Flag: Wallis and Futuna": "Flagge: Wallis und Futuna",
	"Flag: Samoa": "Flagge: Samoa",
	"Flag: Kosovo": "Flagge: Kosovo",
	"Flag: Yemen": "Flagge: Jemen",
	"Flag: Mayotte": "Flagge: Mayotte",
	"Flag: Republic of South Africa": "Flagge: Südafrika",
	"Flag: Zambia": "Flagge: Sambia",
	"Flag: Zimbabwe": "Flagge: Simbabwe",
	"Flag: England": "Flagge: England",
	"Flag: Scotland": "Flagge: Schottland",
	"Flag: Wales": "Flagge: Wales"
});
