/**
 * Локализация Украина
 */
tinymce.addI18n('uk', {
	"emoji": "Емодзі (Emoji)",
	"smiles": "Смайлики",
	"emotics": "Емоція",
	"people": "Люди",
	"animals": "Тварина",
	"nature": "Природа",
	"food": "Їжа та Напої",
	"places": "Місця та Подорожі",
	"events": "Події та Свята",
	"objects": "Об'єкти та Речі",
	"symbols": "Символ",
	"flags": "Прапор",
	"The grinning face": "Усміхнене обличчя",
	"A smiling face with an open mouth": "Усміхнене обличчя\nз відкритим ротом",
	"A smiling face with an open mouth and smiling eyes": "Усміхнене обличчя\nз відкритим ротом\nі усміхненими очима",
	"A grinning face with smiling eyes": "Усміхнене обличчя\nз усміхненими очима",
	"A smiling face with an open mouth and tightly closed eyes": "Усміхнене обличчя\nз відкритим ротом\nі щільно закритими очима",
	"A smiling face with an open mouth and cold sweat": "Усміхнене обличчя\nз відкритим ротом\nі холодним потім",
	"Rolling on the floor laughing": "Катаюся по підлозі від сміху",
	"A face with tears of joy": "Обличчя зі сльозами радості",
	"A slightly smiling face": "Злегка усміхнене обличчя",
	"The inverted face": "Перевернуте обличчя",
	"The winking face": "Підморгуюче обличчя",
	"A smiling face with smiling eyes": "Усміхнене обличчя\nз усміхненими очима",
	"A smiling face with a halo": "Усміхнене обличчя\nз німбом",
	"A smiling face with smiling eyes and three hearts": "Усміхнене обличчя\nз усміхненими очима\nі трьома серцями",
	"A smiling face with heart-shaped eyes": "Усміхнене обличчя\nз очима у формі сердечок",
	"A grinning face with starry eyes": "Усміхнене обличчя\nіз зоряними очима",
	"The person sending the kiss": "Обличчя, що посилає поцілунок",
	"The kissing face": "Цілуюче обличчя",
	"A white smiling face": "Біле усміхнене обличчя",
	"Kissing a face with closed eyes": "Цілуюче обличчя\nіз закритими очима",
	"A kissing face with smiling eyes": "Цілуюче обличчя\nз усміхненими очима",
	"A person enjoying a delicious meal": "Обличчя, яке насолоджується смачною їжею",
	"A face with a protruding tongue": "Обличчя з висунутим язиком",
	"A face with a protruding tongue and a winking eye": "Обличчя з висунутим язиком\nі підморгуючим оком",
	"A grinning face with one big and one small eye": "Усміхнене обличчя\nз одним великим\nі одним маленьким оком",
	"A face with a protruding tongue and tightly closed eyes": "Обличчя з висунутим язиком\nі щільно закритими очима",
	"The face with the money mouth": "Обличчя з грошовим ротом",
	"The hugging face": "Обіймаюче обличчя",
	"A smiling face with smiling eyes and a hand covering his mouth": "Усміхнене обличчя\nз усміхненими очима\nі рукою, що закриває рот",
	"A face with closed lips, covered with a finger": "Обличчя з закритими губами,\nприкритими пальцем",
	"The thinking face": "Думаюче обличчя",
	"A face with a zipper": "Обличчя із застібкою-блискавкою",
	"A face with a raised eyebrow": "Обличчя з піднятою бровою",
	"A neutral person": "Нейтральне обличчя",
	"A face without expression": "Обличчя без вираження",
	"A face without a mouth": "Обличчя без рота",
	"A sad face": "Невеселе обличчя",
	"A face with rolled eyes": "Обличчя з закоченими очима",
	"The grimacing face": "Гримасне обличчя",
	"A lying face": "Брехливе обличчя",
	"A relieved face": "Обличчя з полегшенням",
	"A thoughtful face": "Задумливе обличчя",
	"Sleepy face": "Сонне обличчя",
	"Slobbery face": "Слиняве обличчя",
	"The sleeping face": "Спляче обличчя",
	"A face with a medical mask": "Обличчя з медичною маскою",
	"A face with a thermometer": "Обличчя з термометром",
	"A face with a headband": "Обличчя з пов'язкою на голові",
	"Sickening face": "Нудотне обличчя",
	"Face with open mouth, vomiting": "Обличчя з відкритим ротом, блювота",
	"Sneezing face": "Чхання обличчя",
	"Overheated face": "Перегріте обличчя",
	"The freezing face": "Заморожування обличчя",
	"A face with uneven eyes and a wavy mouth": "Обличчя з нерівними очима\nі хвилястим ротом",
	"The dizzying face": "Запаморочливе обличчя",
	"A shocked face with an exploding head": "Шоковане обличчя\nз вибухаючою головою",
	"The face in the cowboy hat": "Обличчя в ковбойському капелюсі",
	"A face with a festive horn and a festive hat": "Обличчя зі святковим ріжком\nі святковим капелюхом",
	"Smiling face in sunglasses": "Усміхнене обличчя\nв сонцезахисних окулярах",
	"Nerd's face": "Обличчя задрота",
	"Face with a monocle": "Обличчя з моноклем",
	"A confused face": "Збентежене обличчя",
	"A worried face": "Стурбована особа",
	"A slightly frowning face": "Злегка насуплене обличчя",
	"A frowning face": "Похмуре обличчя",
	"A face with an open mouth": "Обличчя з відкритим ротом",
	"The silent face": "Мовчазне обличчя",
	"The surprised face": "Здивоване обличчя",
	"Reddened face": "Почервоніле обличчя",
	"A face with pleading eyes": "Обличчя з благаючими очима",
	"A frowning face with an open mouth": "Нахмурене обличчя з відкритим ротом",
	"The suffering face": "Страждаюче обличчя",
	"A scared face": "Перелякане обличчя",
	"A face with an open mouth and cold sweat": "Обличчя з відкритим ротом і холодним потом",
	"A disappointed but relieved face": "Розчароване, але полегшене обличчя",
	"The crying face": "Плаче обличчя",
	"A crying face": "Голосно плаче обличчя",
	"The face screams with fear": "Обличчя кричить від страху",
	"An insistent face": "Наполегливе обличчя",
	"The disappointed face": "Розчароване обличчя",
	"My face is covered in cold sweat": "Обличчя в холодному поту",
	"Tired face": "Втомлене обличчя",
	"A face with an expression of triumph": "Обличчя з виразом тріумфу",
	"Pouty face": "Надуте обличчя",
	"Angry face": "Сердите обличчя",
	"A serious face with symbols covering its mouth": "Серйозне обличчя з символами\nзакривають рот",
	"A smiling face with horns": "Усміхнене обличчя з рогами",
	"The little devil": "Чортеня",
	"Skull": "Череп",
	"Skull and Crossbones": "Череп і схрещені кістки",
	"A bunch of poop": "Купа какашок",
	"The clown's face": "Обличчя клоуна",
	"The Japanese Ogre": "Японський огр",
	"The Japanese Goblin": "Японський Гоблін",
	"Ghost": "Привид",
	"The extraterrestrial alien": "Позаземний прибулець",
	"The alien monster": "Чужий монстр",
	"The robot's face": "Обличчя робота",
	"Smiling cat face with open mouth": "Усміхнене Котяче обличчя\nз відкритим ротом",
	"The grinning face of a cat with smiling eyes": "Усміхнена морда кота\nз усміхненими очима",
	"A cat's face with tears of joy": "Котяча морда\nзі сльозами радості",
	"Smiling cat face with heart-shaped eyes": "Усміхнена мордочка кота\nз очима у формі сердечок",
	"A cat's face with a crooked smile": "Котяча морда\nз кривою посмішкою",
	"Kissing a cat's face with its eyes closed": "Цілуюча мордочка кішки\nіз закритими очима",
	"Tired cat face": "Втомлене Котяче обличчя",
	"The crying face of a cat": "Плаче морда кота",
	"The pouting face of a cat": "Надута морда кота",
	"The monkey who sees no evil": "Мавпа, яка не бачить зла",
	"The monkey who hears no evil": "Мавпа, яка не чує зла",
	"A monkey who doesn't speak evil": "Мавпа, яка не говорить зла",
	"A kiss": "Поцілунок",
	"A love letter": "Любовний лист",
	"A heart with an arrow": "Серце зі стрілою",
	"Heart with ribbon": "Серце зі стрічкою",
	"The Sparkling Heart": "Блискуче Серце",
	"The growing heart": "Зростаюче серце",
	"A Beating Heart": "Б'ється Серце",
	"Spinning Hearts": "Обертові серця",
	"Two Hearts": "Два Серця",
	"Heart-shaped decoration": "Прикраса у вигляді серця",
	"A heart with an exclamation mark": "Серце зі знаком оклику",
	"A Broken Heart": "Розбите Серце",
	"Heart": "Серце",
	"The Orange Heart": "Помаранчеве Серце",
	"The Yellow Heart": "Жовте Серце",
	"The Green Heart": "Зелене Серце",
	"The Blue Heart": "Синє Серце",
	"Purple Heart": "Фіолетове Серце",
	"The Black Heart": "Чорне Серце",
	"The symbol is 100 points": "Символ 100 очок",
	"The symbol of anger": "Символ гніву",
	"Collision symbol": "Символ зіткнення",
	"The symbol of vertigo": "Символ запаморочення",
	"The sweat spray symbol": "Символ бризок поту",
	"The Wind symbol": "Символ Вітер",
	"Hole": "Діра",
	"Bomb": "Бомба",
	"A callout with a speech": "Виноска з промовою",
	"The left speech bubble": "Лівий Мовний міхур",
	"The right anger bubble": "Правильний міхур гніву",
	"The Thought ball": "Мисляча куля",
	"The Sleeping Symbol": "Сплячий Символ",
	"Waving hand": "Махаюча рука",
	"The raised back of the hand": "Піднята тильна сторона руки",
	"A raised hand with outstretched fingers": "Піднята рука з розчепіреними пальцями",
	"Raised hand": "Піднята рука",
	"A raised hand with a parting between the middle and ring fingers": "Піднята рука з проділом між середнім\nі безіменним пальцями",
	"The \"OK\" hand sign": "Знак рукою»ОК\"",
	"\"Victory\" hand sign": "Знак рукою»Перемога\"",
	"The hand with the index and middle fingers crossed": "Рука зі схрещеними вказівним\nі середнім пальцями",
	"I love you hand gesture": "Я люблю тебе жест рукою",
	"The Sign of Horns": "Знак Рогів",
	"Hand sign \"Call me\"": "Знак рукою \" Подзвони мені»",
	"Back of the hand Index finger to the left": "Тильна сторона руки\nВказівний палець вліво",
	"Back of the hand Index finger to the right": "Тильна сторона руки\nВказівний палець вправо",
	"Back of the hand Index finger up": "Тильна сторона руки\nВказівний палець вгору",
	"The back of the hand with the middle finger extended": "Тильна сторона руки\nз витягнутим середнім пальцем",
	"Back of the hand, index finger down": "Тильна сторона руки\nВказівний палець вниз",
	"Index finger up": "Вказівний палець вгору",
	"Thumbs up": "Великий палець вгору",
	"Thumbs down": "Великий палець вниз",
	"Raised fist": "Піднятий кулак",
	"The sign of a clenched fist": "Знак стислій в кулак руки",
	"Left-facing fist": "Кулак, звернений вліво",
	"Fist facing right": "Кулак, звернений вправо",
	"The sign of clapping hands": "Знак плескаючих рук",
	"A man who raised both hands in celebration": "Людина, яка підняла обидві руки на знак святкування",
	"The \"Open Hands\" sign": "Знак \" відкриті руки»",
	"Palms up together": "Долоні вгору разом",
	"Handshake": "Рукостискання",
	"A man with folded arms": "Людина зі складеними руками",
	"The writing hand": "Пишуча рука",
	"Manicure, Nail polish": "Манікюр, Лак для нігтів",
	"Selfie": "Селфі",
	"Bent biceps": "Зігнуті біцепси",
	"Leg": "Нога",
	"Foot": "Ступня",
	"Ear": "Вухо",
	"Nose": "Носа",
	"Brain": "Мозок",
	"Tooth": "Зуб",
	"Bone": "Кістка",
	"Eyes": "Око",
	"Eye": "Око",
	"Tongue": "Мова",
	"Mouth": "Рот",
	"Baby": "Немовля",
	"Child": "Дитина",
	"Boy": "Хлопчик",
	"Girl": "Дівчатко",
	"Adult": "Дорослий",
	"The man with the blond hair": "Людина зі світлим волоссям",
	"Man": "Чоловік",
	"The Bearded Man": "Бородатий Чоловік",
	"Woman": "Жінка",
	"An older adult": "Старший дорослий",
	"An elderly man": "Літній чоловік",
	"An elderly woman": "Літня жінка",
	"The man frowns": "Людина хмуриться",
	"The man with the pouty face": "Людина з надутим обличчям",
	"A face without a good gesture": "Обличчя без хорошого жесту",
	"The face with the \"OK\" gesture": "Обличчя з жестом»ОК\"",
	"Information Bureau employee": "Співробітник інформаційного бюро",
	"The lucky man who raised one hand": "Щаслива людина, яка підняла одну руку",
	"A man bowing low": "Людина, що низько кланяється",
	"Face Palm": "Обличчя Долоню",
	"The shrug of the shoulders": "Знизування плечима",
	"Policeman": "Поліцейський",
	"Detective or spy": "Детектив або шпигун",
	"The Guardsman": "Гвардієць",
	"Construction worker": "Будівельник",
	"Prince": "Принц",
	"Princess": "Принцеса",
	"The man in the turban": "Чоловік у тюрбані",
	"The man with Gua Pi Mao": "Чоловік з Гуа Пі Мао",
	"The man in the headscarf": "Людина в хустці",
	"The man in the tuxedo": "Чоловік у смокінгу",
	"The bride with a veil": "Наречена з вуаллю",
	"Pregnant Woman": "вагітна жінка",
	"Breastfeeding": "Годування грудьми",
	"Baby angel": "Малюк-янголятко",
	"Father Christmas": "дід-Мороз",
	"Mother Christmas": "Мати Різдво",
	"The Super hero": "Супер-герой",
	"The Super villain": "Супер-лиходій",
	"The Magician": "Маг",
	"Fairy": "Фея",
	"A vampire": "Вампір",
	"Merperson. Mermaid": "Мерперсон. Русалка",
	"Elf": "Ельф",
	"Gin": "Джин",
	"Zombie": "Зомбі",
	"Facial massage": "Масаж обличчя",
	"A haircut": "Стрижка",
	"Pedestrian": "Пішохід",
	"Runner": "Бігун",
	"Dancer": "Танцюрист",
	"The man is dancing": "Чоловік танцює",
	"A man in a business suit levitates": "Чоловік у діловому костюмі левітує",
	"The woman with the rabbit ears": "Жінка з кролячими вушками",
	"The man in the steam room": "Людина в парній",
	"The rising Man": "Людина піднімається",
	"The Swordsman": "Фехтувальник",
	"Horse racing": "Перегони",
	"Skier": "Лижник",
	"The snowboarder": "Сноубордист",
	"The golfer": "Гравець у гольф",
	"The Surfer": "Серфер",
	"Rowing boat": "Весловий човен",
	"Swimmer": "Плавець",
	"The man with the ball": "Людина з м'ячем",
	"Weightlifter": "Важкоатлет",
	"Bicyclist": "Велосипедист",
	"Mountain biker": "Гірський велосипедист",
	"The man making the wheel": "Людина, що робить колесо",
	"The wrestlers": "Борець",
	"Water polo": "Водне поло",
	"Handball": "Гандбол",
	"Juggling": "Жонглювання",
	"The man in the lotus position": "Людина в позі лотоса",
	"Bath": "Ванна",
	"Accommodation in sleeping places": "Розміщення в спальних місцях",
	"Two women holding hands": "Дві жінки тримаються за руки",
	"A man and a woman holding hands": "Чоловік і жінка тримаються за руки",
	"Two men holding hands": "Двоє чоловіків тримаються за руки",
	"Kisses": "Цілування",
	"A couple with a heart": "Пара з серцем",
	"Family": "Сім'я",
	"Talking head in silhouette": "Говоряча голова в силуеті",
	"Bust in silhouette": "Бюст в силуеті",
	"Monkey face": "Мавпяче обличчя",
	"A monkey": "Мавпа",
	"Gorilla": "Горила",
	"The dog's face": "Обличчя собаки",
	"Dog": "Пес",
	"The poodle": "Пудель",
	"The face of the wolf": "Обличчя вовка",
	"The fox's face": "Обличчя лисиці",
	"Raccoon's face": "Обличчя єнота",
	"The cat's face": "Обличчя кота",
	"Cat": "Кіт",
	"The Lion's Face": "Обличчя лева",
	"Tiger's Face": "Обличчя тигра",
	"Tiger": "Тигр",
	"Leopard": "Леопард",
	"The horse's face": "Обличчя коня",
	"Horse": "Коня",
	"The Unicorn's Face": "Обличчя єдинорога",
	"Zebra's face": "Обличчя зебри",
	"Deer": "Олень",
	"Cow's face": "Обличчя корови",
	"Bull": "Бик",
	"Water buffalo": "Водяний буйвол",
	"Cow": "Корова",
	"Piglet's face": "Обличчя порося",
	"The piglet": "Порося",
	"The boar's face": "Обличчя кабана",
	"Piglet's Nickel": "П'ятак порося",
	"Ram": "Баран",
	"Sheep": "Вівця",
	"Goat": "Козел",
	"The one-humped camel": "Одногорбний верблюд",
	"The double-humped camel": "Двогорбий верблюд",
	"Lama": "Лама",
	"Giraffe's face": "Обличчя жирафа",
	"Elephant": "Слон",
	"Rhinoceros": "Носоріг",
	"Hippopotamus": "Бегемот",
	"The mouse's face": "Обличчя миші",
	"Mouse": "Миша",
	"Rat": "Щур",
	"Hamster's face": "Обличчя хом'яка",
	"The face of the hare": "Обличчя зайця",
	"Hare": "Зайця",
	"The Chipmunk": "Бурундук",
	"The Hedgehog": "Їжак",
	"Bat": "Кажан",
	"The face of the bear": "Обличчя ведмедя",
	"Koala's face": "Обличчя коали",
	"Panda's Face": "Обличчя панди",
	"Kangaroo": "Кенгуру",
	"Badger": "Борсук",
	"Paw prints": "Відбитки лап",
	"Turkey": "Індичка",
	"Chicken": "Курча",
	"Cock": "Півень",
	"The hatching chick": "Вилуплюється курча",
	"The chicken looking forward": "Курка, що дивиться вперед",
	"Bird": "Птах",
	"Penguin": "Пінгвін",
	"The Dove of Peace": "Голуб миру",
	"Eagle": "Орел",
	"Duck": "Качка",
	"Swan": "Лебідь",
	"Owl": "Сова",
	"Peacock": "Павич",
	"Parrot": "Папуга",
	"The frog's face": "Обличчя жаби",
	"Crocodile": "Крокодил",
	"Turtle": "Черепаха",
	"Lizard": "Ящірка",
	"Snake": "Змія",
	"The Dragon's Face": "Обличчя дракона",
	"Dragon": "Дракон",
	"Sauropod": "Завропод",
	"T-Rex": "Ті-Рекс",
	"The Splashing Whale": "Бризкаючий кит",
	"Whale": "Кит",
	"Dolphin": "Дельфін",
	"Fish": "Риб",
	"Tropical fish": "Тропічна риба",
	"Needle Fish": "Голчаста риба",
	"Shark": "Акула",
	"Octopus": "Восьминіг",
	"Spiral Shell": "Спіральна оболонка",
	"Snail": "Равлик",
	"Butterfly": "Метелик",
	"Caterpillar": "Гусениця",
	"Ant": "Мураха",
	"The honey bee": "Медоносна бджола",
	"Ladybug": "Божа корівка",
	"The cricket": "Цвіркун",
	"Spider": "Павук",
	"Web": "Павутина",
	"Scorpio": "Скорпіон",
	"Mosquito": "Комар",
	"The microbe": "Мікроб",
	"Bouquet": "Букет",
	"Cherry blossoms": "Квітуча вишня",
	"The White Flower": "Біла Квітка",
	"Rosette of leaves": "Розетка листя",
	"Rose": "Троянда",
	"A faded flower": "Зів'яла квітка",
	"Hibiscus": "Гібіскус",
	"Sunflower": "Подсолнечник",
	"Tulip": "Тюльпан",
	"Seedlings": "Розсада",
	"The evergreen tree": "Вічнозелене дерево",
	"Deciduous tree": "Листяні дерева",
	"Palm tree": "Пальма",
	"Cactus": "Кактус",
	"Rice": "Рис",
	"Grass": "Трав",
	"The Shamrock": "Трилисник",
	"Four-leaf clover": "Чотирилистий конюшина",
	"Maple Leaf": "Кленовий лист",
	"The fallen leaf": "Опалий лист",
	"A leaf flutters in the wind": "Лист тремтить на вітрі",
	"Grape": "Виноград",
	"Melon": "Диня",
	"Watermelon": "Кавун",
	"Mandarin": "Мандарин",
	"Lemon": "Лимон",
	"Banana": "Банан",
	"Pineapple": "Ананас",
	"Mango": "Манго",
	"Red Apple": "Червоне яблуко",
	"The green Apple": "Зелене яблуко",
	"Pear": "Груша",
	"Peach": "Персик",
	"Cherry": "Вишня",
	"Strawberry": "Полуниця",
	"Kiwi": "Ківі",
	"Tomato": "Помідор",
	"Kakos": "Какос",
	"Avocado": "Авокадо",
	"Eggplant": "Баклажан",
	"Potato": "Картопля",
	"Markovka": "Марківка",
	"Corn": "Кукурудза",
	"Hot pepper": "Гострий перець",
	"Cucumber": "Огірок",
	"Leafy greens": "Листова зелень",
	"Broccoli": "Броколі",
	"Fly agaric": "Мухомор",
	"Peanut": "Арахіс",
	"Chestnut": "Каштан",
	"Bread": "Хліб",
	"Croissant": "Круасан",
	"Baguette bread": "Багетний хліб",
	"Pretzel": "Крендель",
	"Bagel": "Бублик",
	"Pancakes": "Млинець",
	"Cheese wedge": "Сирний клин",
	"Meat on the bone": "М'ясо на кістці",
	"Bird's foot": "Ніжка птиці",
	"A piece of meat": "Шматок м'яса",
	"Bacon": "Бекон",
	"Hamburger": "Гамбургер",
	"French fries": "Картопля фрі",
	"A slice of pizza": "Шматок піци",
	"Hot dog": "Хот-дог",
	"Sandwich": "Сендвіч",
	"Tacos": "Тако",
	"Burrito": "Буріто",
	"Tortilla with filling": "Коржик з начинкою",
	"Egg": "Яйце",
	"Scrambled eggs": "Яішниця",
	"A shallow pot of food": "Неглибока Каструля з їжею",
	"A pot of food": "Горщик з їжею",
	"A bowl with a spoon": "Миска з ложкою",
	"Green salad": "Зелений салат",
	"Popcorn": "Попкорн",
	"The salt shaker": "Сільничка",
	"Preserves": "Консерви",
	"Container": "Контейнер",
	"Rice Cracker": "Рисовий крекер",
	"Rice ball": "Рисова кулька",
	"Boiled rice": "Варений рис",
	"Curry and rice": "Каррі та рис",
	"Steaming bowl": "Миска для варіння на пару",
	"Spaghetti": "Спаґеті",
	"Fried sweet potatoes": "Смажений батат",
	"Dressed": "Оден",
	"Sushi": "Суш",
	"Fried shrimp": "Смажені креветки",
	"Fish pie with curls": "Рибний пиріг З завитками",
	"Mooncake": "Місячний пиріг",
	"Dango": "Данго",
	"Cheburek": "Чебурек",
	"Fortune Cookies": "Печиво з передбаченням",
	"Takeaway Food Box": "Коробка для їжі на винос",
	"The crab": "Краб",
	"Lobster": "Лобстер",
	"Shrimp": "Креветка",
	"Squid": "Кальмар",
	"Soft ice cream": "М'яке морозиво",
	"Planed ice": "Струганий лід",
	"Ice cream": "Морозиво",
	"Donut": "Пончик",
	"Cookie": "Печиво",
	"Birthday cake": "Торт на день народження",
	"Shortbread cookies": "Пісочне печиво",
	"Cupcake": "Кекс",
	"Pie": "Пиріг",
	"Chocolate bar": "Плитка шоколаду",
	"Candies": "Цукерка",
	"Candy": "Льодяник",
	"Custard cream": "Заварний крем",
	"Honey": "Мед",
	"Baby bottle": "Дитяча пляшечка",
	"A Glass of Milk": "Стакан Молока",
	"Hot drink": "Гарячий напій",
	"Cup without handle": "Чашка без ручки",
	"Sake bottle and cup": "Пляшка і чашка для саке",
	"Champagne": "Шампанське",
	"A glass of wine": "Келих вина",
	"A glass of cocktail": "Келих коктейлю",
	"Tropical drink": "Тропічний напій",
	"A mug of beer": "Кухоль пива",
	"The clink of beer mugs": "Дзвін пивних кухлів",
	"The clink of glasses": "Дзвін келихів",
	"Glass": "Склянка",
	"A cup with a straw": "Чашка з соломинкою",
	"Chopsticks": "Палички для їжі",
	"Fork and knife with plate": "Вилка і ніж з тарілкою",
	"Fork and knife": "Вилка і ніж",
	"Spoon": "Ложка",
	"Knife": "Ножа",
	"The Amphora": "Амфора",
	"Globe Europe-Africa": "Земля Європа-Африка",
	"The Globe of America": "Земля Америка",
	"Globe Asia-Australia": "Земля Азія-Австралія",
	"A globe with meridians": "Глобус з меридіанами",
	"World map": "Карта світу",
	"Japanese Islands": "Японські острови",
	"Compass": "Компас",
	"The snow-capped mountain": "Засніжена гора",
	"Mountain": "Гора",
	"Volcano": "Вулкан",
	"Mount Fuji": "Гора Фудзі",
	"Camping": "Кемпінг",
	"Beach with an umbrella": "Пляж з парасолькою",
	"Desert": "Пустеля",
	"An uninhabited island": "Незаселений острів",
	"National Park": "Національний парк",
	"Stadium": "Стадіон",
	"A classic building": "Класична будівля",
	"Building construction": "БУДІВНИЦТВО БУДІВЕЛЬ",
	"Bricks": "Цегла",
	"Home buildings": "Домашні будівлі",
	"The abandoned building of the house": "Покинута будівля будинку",
	"Building a house": "Будівництво будинку",
	"House with garden": "Будинок з садом",
	"Office building": "Офісна будівля",
	"Japan Post": "Пошта Японії",
	"European Post": "Європейська пошта",
	"Hospital": "Лікарня",
	"Bank": "Банк",
	"Hotel": "Готель",
	"The Hotel of Love": "Готель Любові",
	"Shop near the house": "Магазин біля будинку",
	"School": "Школа",
	"Department Store": "Універмаг",
	"Factory": "Фабрика",
	"Japanese Castle": "Японський замок",
	"European Castle": "Європейський замок",
	"Registry office": "Загс",
	"Tokyo Tower": "Токійська вежа",
	"statue of liberty": "Статуя Свободи",
	"Church": "Церква",
	"Mosque": "Мечеть",
	"The Synagogue": "Синагога",
	"Shinto Shrine": "Синтоїстське святилище",
	"The Kaaba": "Кааба",
	"Fountain": "Фонтан",
	"Tent": "Намет",
	"Foggy": "Туманно",
	"A night with stars": "Ніч із зірками",
	"Urban landscape": "Міський пейзаж",
	"Sunrise over the mountains": "Схід Сонця над горами",
	"Sunrise over the water": "Схід Сонця над водою",
	"Urban landscape at dusk": "Міський пейзаж у сутінках",
	"Sunset over buildings": "Захід сонця над будівлями",
	"The bridge at night": "Міст вночі",
	"Hot springs": "Гарячі джерела",
	"The Milky Way": "Чумацький Шлях",
	"The Carousel Horse": "Карусельний Кінь",
	"Ferris wheel": "Колесо огляду",
	"Roller Coaster": "американські гірки",
	"Barbershop": "Перукарня",
	"Circus tent": "Цирковий намет",
	"Steam train": "Паровоз",
	"Railway carriage": "Залізничний вагон",
	"High-speed train": "Швидкісний поїзд",
	"Bullet-nosed Bullet Train": "Швидкісний поїзд з кулеподібним носом",
	"Railway": "Залізниця",
	"Metro": "Метро",
	"High-speed tram": "Швидкісний трамвай",
	"Station": "Станція",
	"Tram": "Трамвай",
	"Monorail": "Монорейка",
	"Mountain Railway": "Гірська залізниця",
	"Tram car": "Трамвайний вагон",
	"Bus": "Автобус",
	"An approaching bus": "Наближається автобус",
	"Trolleybus": "Тролейбус",
	"Minibus": "Мікроавтобус",
	"Ambulance": "Швидка допомога",
	"Fire truck": "Пожежна машина",
	"Police car": "Поліцейська машина",
	"An approaching police car": "Наближається поліцейська машина",
	"Taxi": "Таксі",
	"An approaching taxi": "Наближається таксі",
	"Car": "Автомобіль",
	"An approaching car": "Наближається автомобіль",
	"A recreational vehicle": "Автомобіль для відпочинку",
	"Delivery Truck": "Вантажівка для доставки",
	"Articulated truck": "Зчленована вантажівка",
	"Tractor": "Трактор",
	"Racing car": "Перегонний автомобіль",
	"Racing Motorcycle": "Гоночний мотоцикл",
	"Scooter": "Самокат",
	"Bicycle": "Велосипед",
	"Skateboard": "Скейтборд",
	"Bus stop": "Автобусна зупинка",
	"Motorway": "Автомагістраль",
	"Railway track": "Залізнична колія",
	"Oil barrel": "Бочка для масла",
	"Refill": "Заправка",
	"Police Car Beacons": "Маячок поліцейської машини",
	"Horizontal traffic light": "Горизонтальний світлофор",
	"Vertical traffic light": "Вертикальний світлофор",
	"The octagonal sign": "Восьмикутний знак",
	"Building sign": "Будівельний знак",
	"Anchor": "Якоря",
	"Sailboat": "Вітрильник",
	"Kanoya": "Каноя",
	"High-speed boat": "Швидкохідний катер",
	"Passenger ship": "Пасажирське судно",
	"Ferryboat": "Пором",
	"Motor boat": "Моторний човен",
	"Ship": "Корабель",
	"Airplane": "Літак",
	"A small plane": "Маленький літак",
	"Flight departure": "Виліт літака",
	"Arrival of the plane": "Прибуття літака",
	"The seat": "Сидіння",
	"Helicopter": "Вертоліт",
	"Overhead railway": "Підвісна залізниця",
	"Mountain Cable Car": "Гірська Канатна дорога",
	"Cable car": "Линвова дорога",
	"Satellite": "Супутник",
	"Rocket": "Ракета",
	"Flying saucer": "Літальна тарілка",
	"Call": "Дзвінок",
	"Luggage": "Багаж",
	"The Hourglass": "Пісковий годинник",
	"Hourglass with loose sand": "Пісочний годинник з сипучим піском",
	"Watch": "Наручний годинник",
	"Alarm": "Будильник",
	"Stopwatch": "Секундомір",
	"Timer": "Таймер",
	"The clock on the mantelpiece": "Годинник на камінній полиці",
	"The dial is twelve o'clock": "Циферблат дванадцять годин",
	"The dial is half past one": "Циферблат Половина другого",
	"The dial is One emergency": "Циферблат один НС",
	"The dial is two o'clock": "Циферблат дві години",
	"The dial is half past two": "Циферблат Половина третього",
	"The dial is three o'clock": "Циферблат Три години",
	"The dial is half past three": "Циферблат Половина четвертого",
	"The dial is four o'clock": "Циферблат чотири години",
	"The dial is half past four": "Циферблат Половина п'ятого",
	"The dial is five o'clock": "Циферблат П'ять годин",
	"The dial is half past five": "Циферблат Половина шостого",
	"The dial is six o'clock": "Циферблат шість годин",
	"The dial is half past six": "Циферблат Половина сьомого",
	"The dial is Seven o'clock": "Циферблат сім годин",
	"The dial is half past seven": "Циферблат Половина восьмого",
	"The Dial Is Eight O'clock": "Циферблат Вісім Годин",
	"The dial is half past eight": "Циферблат Половина дев'ятого",
	"The dial is Nine o'clock": "Циферблат Дев'ять годин",
	"The dial is half past nine": "Циферблат Половина десятого",
	"The dial is Ten o'clock": "Циферблат Десять годин",
	"The dial is half past ten": "Циферблат Половина дванадцятого",
	"The dial is eleven o'clock": "Циферблат одинадцять годин",
	"The symbol of the new moon": "Символ молодика",
	"The symbol of the growing crescent moon": "Символ зростаючої півмісяця",
	"The symbol of the first quarter of the Moon": "Символ першої чверті Місяця",
	"The symbol of the waxing Moon": "Символ зростаючого Місяця",
	"The Symbol of the Full Moon": "Символ Повного Місяця",
	"The symbol of the waning Moon": "Символ спадної місяця",
	"The symbol of the last quarter of the moon": "Символ останньої чверті Місяця",
	"The symbol of the waning crescent": "Символ спадної півмісяця",
	"The Crescent Moon": "Півмісяць",
	"A new moon with a face": "Молодик з обличчям",
	"The first quarter of the moon with a face": "Перша чверть місяця з обличчям",
	"The last quarter of the Moon with a face": "Остання чверть місяця з обличчям",
	"Thermometer": "Термометр",
	"The Sun With Rays": "Сонце З Променями",
	"Full Moon With A Face": "Повний Місяць З Обличчям",
	"The sun with a face": "Сонце з обличчям",
	"The white middle Star": "Біла Середня зірка",
	"A Glowing Star": "Світиться Зірка",
	"Shooting Star": "Падаюча зірка",
	"Cloud": "Хмара",
	"The sun behind the cloud": "Сонце за хмарою",
	"Thundercloud and rain": "Грозова хмара і дощ",
	"A White Sun with a Small Cloud": "Біле сонце з маленькою хмарою",
	"White Sun Behind A Cloud": "Біле Сонце За Хмарою",
	"White sun behind a cloud with rain": "Біле сонце за хмарою з дощем",
	"A cloud with rain": "Хмара з дощем",
	"A cloud with snow": "Хмара зі снігом",
	"A cloud with lightning": "Хмара з блискавкою",
	"Tornado cloud": "Хмара з торнадо",
	"Fog": "Туман",
	"A face blown by the wind": "Обличчя, що обдувається вітром",
	"Cyclone": "Циклон",
	"Rainbow": "Веселка",
	"Closed umbrella": "Закритий парасольку",
	"Umbrella": "Зонтик",
	"Umbrella with raindrops": "Парасолька з краплями дощу",
	"An umbrella on the ground": "Парасолька на землі",
	"The high voltage sign": "Знак високої напруги",
	"Snowflake": "Сніжинка",
	"Snowman": "Сніговик",
	"A snowman without snow": "Сніговик без снігу",
	"The Comet": "Комета",
	"Fire": "Вогонь",
	"A drop": "Крапля",
	"Water wave": "Водяна хвиля",
	"Jack-o'-lanterns": "Джек-ліхтар",
	"Christmas tree": "Новорічна ялинка",
	"Fireworks display": "Феєрверк",
	"Bengal fire": "Бенгальський вогонь",
	"Firecracker": "Петарда",
	"Sparks": "Іскра",
	"Air balloon": "Повітряна куля",
	"A party cracker": "Хлопавка для вечірок",
	"A ball of confetti": "Куля конфетті",
	"The Tanabata Tree": "Дерево Танабата",
	"Pine ornaments": "Соснові прикраси",
	"Japanese dolls": "Японські ляльки",
	"Carp Streamer": "Короповий стример",
	"Wind Music": "Музика Вітру",
	"Moon Viewing Ceremony": "Церемонія милування місяцем",
	"Red gift Envelope": "Червоний подарунковий конверт",
	"Tape": "Стрічка",
	"A packaged gift": "Упакований подарунок",
	"Reminder Feed": "Стрічка нагадувань",
	"Entrance fees": "Вхідний квиток",
	"Ticket": "Квиток",
	"Military Medal": "Військова медаль",
	"Cup": "Кубок",
	"Sports medal": "Спортивна медаль",
	"Medal for the first place": "Медаль за перше місце",
	"Medal for the second place": "Медаль за друге місце",
	"Medal for the third place": "Медаль за третє місце",
	"football": "Футбольний М'яч",
	"Baseball ball": "Бейсбольний м'яч",
	"Softball ball": "Софтбольний м'яч",
	"Basketball ball": "Баскетбольний м'яч",
	"A volleyball ball": "Волейбольний м'яч",
	"An American football ball": "М'яч для американського футболу",
	"A Rugby ball": "М'яч для регбі",
	"Tennis racket and ball": "Тенісна ракетка і м'яч",
	"The Flying Disc": "Літаючий Диск",
	"Bowling": "Боулінг",
	"Cricket bat and ball": "Бита і м'яч для крикету",
	"Field hockey stick and ball": "Ключка і м'яч для хокею на траві",
	"Hockey stick and puck": "Хокейна ключка і шайба",
	"A club and a lacrosse ball": "Ключка і м'яч для лакросу",
	"Table tennis racket and ball": "Ракетка і м'яч для настільного тенісу",
	"Badminton racket and shuttlecock": "Бадмінтонна ракетка і волан",
	"Boxing glove": "Боксерська Рукавичка",
	"Martial Arts Uniforms": "Уніформа для бойових мистецтв",
	"Paved gates": "Хокейні ворота",
	"Golf Flags": "Флажек в гольфі",
	"Skates": "Ковзан",
	"Fishing rod and fish": "Вудка і риба",
	"Running T-shirt": "Футболка для бігу",
	"Skis and ski boots": "Лижі та лижні черевики",
	"Sleigh": "Сани",
	"Stone for curling": "Камінь для керлінгу",
	"Direct hit": "Пряме влучання",
	"Billiard": "Більярд",
	"The Crystal Ball": "Кришталева куля",
	"Nazar's Amulet": "Амулет Назара",
	"Video game": "Відеогра",
	"The joystick": "Джойстик",
	"Slot machine": "Ігровий автомат",
	"The game cube": "Ігровий кубик",
	"A piece of the puzzle": "Шматочок пазла",
	"Teddy bear": "Плюшевий ведмедик",
	"The Suit of Spades": "Масть Піки",
	"Suit of Hearts": "Масть Черви",
	"The Bubi Suit": "Масть Бубі",
	"The suit of the Cross": "Масть Хрести",
	"The Black pawn": "Чорний пішак",
	"The Joker Playing card": "Гральна карта Джокер",
	"Mahjong Tile Red Dragon": "Плитка маджонг Червоний дракон",
	"Floral Playing Cards": "Квіткові гральні карти",
	"Theatrical masks": "Театральні маски",
	"Framed painting": "Картина в рамці",
	"The artist's palette": "Палітра художника",
	"A Spool of Thread": "Котушка Ниток",
	"A ball of yarn": "Клубок пряжі",
	"Uh-huh": "Е-е",
	"Kite": "Повітряний змій",
	"Skydiver": "Парашутист",
	"The Boomerang": "Бумеранг",
	"The magic wand": "Чарівна паличка",
	"Pinata": "Піньята",
	"Matryoshka dolls": "Матрьошка",
	"Glasses": "Окуляри",
	"Black glasses": "Чорні окуляри",
	"Scuba Diver's Mask": "Маска аквалангіста",
	"Laboratory (doctor's) coat": "Лабораторний (докторський) халат",
	"Tie": "Краватка",
	"T-shirt": "Футболка",
	"Jeans": "Джинси",
	"Scarf": "Шарф",
	"Gloves": "Рукавичка",
	"Coat": "Пальто",
	"Socks": "Шкарпетки",
	"Dress": "Плаття",
	"Kimano": "Кімано",
	"Bikini (swimsuit)": "Бікіні (купальник)",
	"Women's bathrobe": "Жіночий халат",
	"Wallet": "Гаманець",
	"Handbag": "Торбинка",
	"The pouch": "Мішечок",
	"Shopping Bags": "Пакети для покупок",
	"School backpack": "Шкільний рюкзак",
	"Men's shoes": "Чоловіче взуття",
	"Sports shoes": "Спортивне взуття",
	"Hiking boots": "Туристичні черевики",
	"Women's Flat Shoes": "Жіноче взуття\nна плоскій підошві",
	"High-heeled shoes": "Мешти\nна високих підборах",
	"Women's Sandals": "Жіночі сандалі",
	"Women's boots": "Жіночі чоботи",
	"Crown": "Корона",
	"Women's Panama": "Жіноча панама",
	"Top hat (male)": "Циліндр (чоловічий)",
	"Graduate's hat": "Шапочка випускника",
	"Baseball cap": "Бейсболка",
	"Helmet with a white cross": "Шолом з білим хрестом",
	"Prayer beads": "Чотки для молитви",
	"Lipstick (sponge)": "Помада (губнушка)",
	"Ring": "Кільце",
	"A precious stone": "Дорогоцінний камінь",
	"Sound is prohibited": "Звук заборонений",
	"The speaker is off": "Динамік вимкнено",
	"Speaker at minimum volume": "Динамік на мінімальній гучності",
	"Speaker at maximum volume": "Динамік на максимальній гучності",
	"Speaker for notification": "Гучномовець для оповіщення",
	"Megafon": "Мегафон",
	"Postal Horn": "Поштовий Ріг",
	"Bell": "Дзвін",
	"The bell is forbidden": "Дзвін заборонений",
	"Musical score": "Музична партитура",
	"Musical note": "Музична нота",
	"Musical notes": "Музичні ноти",
	"Studio Microphone": "Студійний мікрофон",
	"Slider control": "Регулятор слайдер",
	"Control knobs": "Ручки управління",
	"Microphone": "Мікрофон",
	"Headphones": "Навушники",
	"Radio": "Радіо",
	"The saxophone": "Саксафон",
	"Guitar": "Гітара",
	"Musical keyboard": "Музична клавіатура",
	"Musical Trumpet": "Музична Труба",
	"Violin": "Скрипка",
	"A drum with drumsticks": "Барабан з барабанними паличками",
	"Mobile phone": "Мобільний телефон",
	"Mobile phone receiving a call": "Мобільний телефон прийом дзвінка",
	"Disk Phone Number": "Дисковий Телефон",
	"The handset": "Телефонна трубка",
	"The pager": "Пейджер",
	"Fax number": "Факс",
	"Battery": "Батарейка",
	"Electric plug": "Електрична вилка",
	"A laptop": "Ноутбук",
	"Computer": "Комп'ютер",
	"Printer": "Принтер",
	"Keyboard": "Клавіатура",
	"Three-button mouse": "Трикнопкова миша",
	"Trackball": "Трекбол",
	"Minidisc": "Мінідиск",
	"3.5\" Floppy Disk 1.44Mb": "Дискета 3.5 \" 1,44 Мб",
	"Optical Disc CD": "Оптичний Диск CD",
	"Optical Disc DVD": "Оптичний Диск DVD",
	"Accounts": "Рахівниця",
	"Movie Camera": "Кінокамера",
	"The movie": "Кінострічка",
	"Filmoscope (projector)": "Фільмоскоп (проектор)",
	"The movie Cracker": "Кінохлопушка",
	"TV": "Телевізор",
	"The camera": "Фотокамера",
	"Camera with flash light": "Фотокамера з фотоспалахом",
	"Video camera": "Відео камера",
	"Video tape": "Відеокасета",
	"Healing glass with a stream on the left": "Увелечительное скло\nз струмеой зліва",
	"Healing glass with a stream on the right": "Увелечительное скло\nз струмеой праворуч",
	"A Burning Candle": "Палаюча Свічка",
	"Electric light bulb": "Електрична лампочка",
	"Electric flashlight": "Електричний ліхтарик",
	"The red lantern": "Червоний ліхтар",
	"A notebook with a decorative cover": "Блокнот з декоративною обкладинкою",
	"The Closed book": "Згорнути книгу",
	"An open book": "Відкрита книга",
	"The Green Book": "Зелена Книга",
	"The Blue Book": "Синя книга",
	"The Orange Book": "Помаранчева книга",
	"Books": "Книга",
	"Notepad": "Блокнот",
	"Accounting Book": "Бухгалтерська книга",
	"The Curl page": "Сторінка з завитком",
	"A page with swirls at the top and bottom": "Сторінка З завитками зверху і знизу",
	"The page is face up": "Сторінка лицьовою стороною вгору",
	"Newspaper": "Газета",
	"A rolled-up newspaper": "Згорнута в трубочку газета",
	"Bookmarks Tabs": "Закладки Вкладки",
	"Bookmark": "Закладка",
	"Label": "Етикетка",
	"The money Bag": "Грошовий мішок",
	"A banknote with a yen sign": "Банкнота зі знаком ієни",
	"A banknote with a dollar sign": "Банкнота зі знаком долара",
	"Banknote with the euro sign": "Банкнота зі знаком Євро",
	"A banknote with a pound sign": "Банкнота зі знаком фунта",
	"Money with wings": "Гроші з крилами",
	"Credit card": "Кредитна картка",
	"Receipt": "Квитанція",
	"Chart with an uptrend and a yen sign": "Графік з висхідним трендом і знаком ієни",
	"Currency exchange": "Обмін валюти",
	"Heavy Dollar sign": "Важкий знак долара",
	"The envelope": "Конверт",
	"The email symbol": "Символ Електронної Пошти",
	"Incoming envelope": "Вхідний конверт",
	"An envelope with a downward arrow on top": "Конверт зі стрілкою вниз зверху",
	"Outgoing Mail tray": "Лоток для вихідних листів",
	"Incoming Message tray": "Лоток для вхідних повідомлень",
	"Packaging": "Упаковка",
	"A closed mailbox with a raised flag": "Закрита Поштова скринька з піднятим прапором",
	"A closed mailbox with a lowered flag": "Закрита Поштова скринька з опущеним прапором",
	"An open mailbox with a raised flag": "Відкрита Поштова скринька з піднятим прапором",
	"An open mailbox with the flag down": "Відкрита Поштова скринька з опущеним прапором",
	"Mailbox": "Поштова скринька",
	"The ballot box": "Урна для голосування з бюлетенем",
	"Pencil": "Олівець",
	"Fountain Pen": "Пір'яна ручка",
	"Lower left fountain pen": "Нижня ліва пір'яна ручка",
	"Lower left ballpoint pen": "Нижня ліва кулькова ручка",
	"Lower left hand": "Нижня ліва кисть",
	"Lower left pencil": "Нижній лівий олівець",
	"The memo": "Пам'ятка",
	"Briefcase": "Портфель",
	"Folder with files": "Папка з файлами",
	"An open folder with files": "Відкрита Папка з файлами",
	"File dividers": "Роздільники для картотеки",
	"Calendar": "Календар",
	"Tear-off calendar": "Відривний календар",
	"Spiral Notebook": "Блокнот зі спіраллю",
	"Notepad calendar with spiral": "Блокнот-календар зі спіраллю",
	"File cabinet": "Картотека",
	"An uptrend chart": "Графік з висхідним трендом",
	"A chart with a downtrend": "Графік з низхідним трендом",
	"Bar chart": "Стовпчаста діаграма",
	"Clipboard": "Буфер обміну",
	"Button": "Кнопка",
	"Round button": "Кругла кнопка",
	"Paper clip": "Скріпка для паперів",
	"Bound Paper Clips": "Пов'язані скріпки",
	"Ruler": "Лінійка",
	"Triangular ruler": "Трикутна лінійка",
	"Scissors": "Ножиці",
	"The filing cabinet box": "Коробка для картотеки",
	"File Cabinet": "Файловий шафа",
	"The wastebasket": "Кошик для сміття",
	"Castle": "Замок",
	"An open castle": "Відкритий замок",
	"Lock with ink pen": "Замок з чорнильною ручкою",
	"A closed lock with a key": "Закритий замок з ключем",
	"Key": "Ключ",
	"The old key": "Старий ключ",
	"A hammer": "Молоток",
	"Pickaxe": "Кирка",
	"Hammer and pickaxe": "Молоток і кирка",
	"Hammer and wrench": "Молоток і гайковий ключ",
	"Dagger-knife": "Кинджал-ніж",
	"Crossed swords": "Схрещені мечі",
	"Gun": "Пістолет",
	"Bow and arrows": "Лук і стріли",
	"Shield": "Щит",
	"Wrench": "Гайковий ключ",
	"A bolt with a spike": "Болт з кайкою",
	"Mechanism": "Механізм",
	"Compression": "Стиснення",
	"Scales": "Терези",
	"The link symbol": "Символ посилання",
	"Chains": "Ланцюг",
	"The toolbox": "Ящик для інструментів",
	"Magnet": "Магніт",
	"The alembic": "Перегінний куб",
	"Test tube": "Пробірка",
	"Petri Dish": "Чашка Петрі",
	"The double helix of DNA": "Подвійна спіраль ДНК",
	"The microscope": "Мікроскоп",
	"The telescope": "Телескоп",
	"Satellite dish": "Супутникова антена",
	"Syringe": "Шприц",
	"The pill": "Пілюля",
	"Door": "Двері",
	"Bed": "Ліжко",
	"Sofa and lamp": "Диван і лампа",
	"Toilet": "Туалет",
	"Shower": "Душ",
	"A bottle of lotion": "Флакон лосьйону",
	"Safety Pin": "Англійська шпилька",
	"Broomstick": "Мітла",
	"Basket": "Кошик",
	"A roll of paper": "Рулон паперу",
	"A bar of soap": "Шматок мила",
	"Sponge": "Губка",
	"Fire extinguisher": "Вогнегасник",
	"Shopping cart": "Візок для покупок",
	"The symbol of smoking": "Символ куріння",
	"Coffin": "Труна",
	"Funeral urn": "Похоронна урна",
	"Moyai statue": "Мояї",
	"ATM machine": "Банкомат",
	"Remove the trash": "Приберіть сміття",
	"Drinking water": "Питна вода",
	"Wheelchair": "Інвалідний візок",
	"Symbol: Male": "Символ: Чоловік",
	"Symbol: A woman": "Символ: Жінка",
	"Symbol: Child": "Символ: Дитина",
	"The lavatory": "Вбиральня",
	"Passport control": "Паспортний контроль",
	"Customs": "Митниця",
	"Baggage claim": "Видача багажу",
	"Luggage storage": "Камера зберігання багажу",
	"The warning sign": "Попереджувальний знак",
	"Children's crossing": "Дитячий перехід",
	"The forbidding sign": "Заборонний знак",
	"No entry sign": "Знак»вхід заборонено\"",
	"Bicycles are prohibited": "Велосипеди заборонені",
	"Smoking is prohibited": "Палити заборонено",
	"Don't litter": "Не смітити",
	"Non-potable water": "Непитна вода",
	"Pedestrian traffic is prohibited": "Рух пішоходів заборонено",
	"No cell phones": "Ніяких мобільних телефонів",
	"Prohibited Under the age of eighteen": "Заборонено молодше вісімнадцяти",
	"Radiation hazard": "Радіаційна опастность",
	"Biological hazards": "Біологічевкая опастность",
	"Black Arrow Up": "Чорна Стрілка Вгору",
	"Northeast Arrow": "Північно-Східна Стрілка",
	"Black arrow to the right": "Чорна стрілка вправо",
	"Southeastern Arrow": "Південно-Східна Стрілка",
	"The black arrow is down": "Чорна стрілка вниз",
	"Southwest Arrow": "Південно-Західна Стрілка",
	"Black arrow to the left": "Чорна стрілка вліво",
	"North-Western Arrow": "Північно-Західна Стрілка",
	"Up-down arrow": "Стрілка вгору-вниз",
	"Left-right arrow": "Стрілка вліво-вправо",
	"Left arrow with hook": "Стрілка вліво з гачком",
	"Right arrow with hook": "Стрілка вправо з гачком",
	"An arrow pointing to the right, then curving upward": "Стрілка, спрямована вправо,\nпотім згинається вгору",
	"An arrow pointing to the right, then curving downwards": "Стрілка, спрямована вправо,\nпотім згинається вниз",
	"Open circular arrows pointing up and down clockwise": "Відкриті кругові стрілки,\nспрямовані вгору і вниз\nза годинниковою стрілкою",
	"Open circular arrows pointing up and down counterclockwise": "Відкриті кругові стрілки,\nспрямовані вгору і вниз\nпроти годинникової стрілки",
	"Back with the left arrow on top": "Назад зі стрілкою вліво зверху",
	"Finish with the left arrow on top": "Завершити зі стрілкою вліво зверху",
	"With an exclamation mark and a left-right arrow on top": "Зі знаком оклику\nі стрілкою вліво-вправо зверху",
	"Soon with the arrow to the right at the top": "Швидкий\nзі стрілкою вправо вгорі",
	"Up with the up arrow at the top": "Догори\nзі стрілкою вгору вгорі",
	"A place of worship": "Місце поклоніння",
	"The symbol of the Atom": "Символ Атома",
	"The Om symbol": "Символ Ом",
	"The Star of David": "Зірка Давида",
	"The Wheel of Dharma": "Колесо Дхарми",
	"Yin Yang": "Інь Ян",
	"The Latin Cross": "Латинський хрест",
	"The Orthodox Cross": "Православний хрест",
	"The star and the crescent moon": "Зірка і півмісяць",
	"A symbol of peace": "Символ миру",
	"Menorah with nine branches": "Менора з дев'ятьма гілками",
	"A six-pointed star with a dot in the middle": "Шестикутна зірка з точкою посередині",
	"Aries": "Овен",
	"Taurus": "Бик",
	"Twins": "Близнюки",
	"Cancer": "Рак",
	"Leo": "Лев",
	"Maid": "Діва",
	"Sagittarius": "Стрілець",
	"Capricorn": "Козоріг",
	"Aquarius": "Водолій",
	"The Ophiuchus": "Змієносець",
	"Twisted arrows pointing to the right": "Скручені стрілки,\nспрямовані вправо",
	"Round arrows pointing clockwise to the right and left": "Круглі стрілки,\nспрямовані вправо і вліво за годинниковою стрілкою",
	"Round arrows pointing clockwise to the right and left, with a unit superimposed in a circle": "Круглі стрілки,\nспрямовані за годинниковою стрілкою вправо і вліво,\nз накладенням одиниці в гуртку",
	"A triangle pointing to the right": "Трикутник,\nспрямований вправо",
	"A double triangle pointing to the right": "Подвійний трикутник,\nспрямований вправо",
	"A double triangle pointing to the right, with a vertical line": "Подвійний трикутник,\nспрямований вправо,\nз вертикальною лінією",
	"A triangle pointing to the right with a double vertical line": "Трикутник,\nспрямований вправо,\nз подвійною вертикальною рискою",
	"A triangle pointing to the left": "Трикутник,\nспрямований вліво",
	"A double triangle pointing to the left": "Подвійний трикутник,\nспрямований вліво",
	"A double triangle pointing to the left, with a vertical line": "Подвійний трикутник,\nспрямований вліво,\nз вертикальною лінією",
	"The triangle is upside down": "Трикутник вершиною вниз",
	"Double triangle with the top facing up": "Подвійний трикутник вершиною вгору",
	"Double triangle with the top facing down": "Подвійний трикутник вершиною вниз",
	"Double vertical stripe": "Подвійна вертикальна смуга",
	"The stop square": "Квадрат зупинки",
	"The recording circle": "Коло запису",
	"Extraction symbol": "Символ вилучення",
	"Movie": "Кіно",
	"Low brightness symbol": "Символ низької яскравості",
	"High brightness symbol": "Символ високої яскравості",
	"Antenna with a grid": "Антена з гратами",
	"Vibration mode": "Режим вібрації",
	"The mobile phone is turned off": "Мобільний телефон вимкнено",
	"Female sign": "Жіночий знак",
	"The male sign": "Чоловічий знак",
	"The staff of Aesculapius": "Посох Ескулапа",
	"Permanent paper sign": "Постійний паперовий знак",
	"Symbol of recycling": "Символ переробки",
	"Lily Flower": "Квітка лілії",
	"The Trident Emblem": "Емблема тризуба",
	"Name badge": "Бейдж з ім'ям",
	"Japanese symbol for beginners": "Японський символ для початківців",
	"Heavy big circle": "Важке велике коло",
	"White bold checkmark": "Біла жирна галочка",
	"Ballot box with verification": "Урна для голосування з перевіркою",
	"Heavy check mark": "Важка галочка",
	"Heavy X multiplication": "Важке множення X",
	"Mark the Cross": "Хрест Марк",
	"Negative square cross": "Негативний квадратний хрестик",
	"Heavy plus sign": "Важкий знак плюса",
	"Heavy minus sign": "Важкий знак мінус",
	"The sign of heavy division": "Знак важкого поділу",
	"The Winding Loop": "Кучерява петля",
	"Double Curly loop": "Подвійна кучерява петля",
	"The sign of alternating parts": "Знак чергування частин",
	"The eight-pointed star": "Восьмикутна Зірочка",
	"Eight-pointed black star": "Восьмикутна Чорна зірка",
	"Spark": "Іскра",
	"Double exclamation mark": "Подвійний знак оклику",
	"The exclamation mark of the question": "Знак оклику питання",
	"Black question mark": "Чорний знак питання",
	"A white question mark": "Білий знак питання",
	"White exclamation mark": "Білий знак оклику",
	"The bold exclamation mark symbol": "Символ жирного знаку оклику",
	"The wavy line": "Хвиляста риса",
	"Copyright mark": "Знак авторського права",
	"Registered mark": "Зареєстрований знак",
	"Trademark": "Товарний знак",
	"The grid sign": "Знак решітки",
	"The footnote": "Виноска",
	"The zero sign": "Нульовий знак",
	"The unity sign": "Знак одиниця",
	"The deuce sign": "Знак двійка",
	"The troika sign": "Знак Трійка",
	"The four sign": "Знак четвірка",
	"The five sign": "Знак п'ятірка",
	"The sign of the six": "Знак шістка",
	"The sign of the seven": "Знак сімка",
	"The figure eight sign": "Знак вісімка",
	"The sign of the nine": "Знак дев'ятка",
	"The sign of the ten": "Знак десятка",
	"The ABCD sign": "Знак ABCD",
	"The abcd sign": "Знак abcd",
	"Sign 1234": "Знак 1234",
	"Character input symbol": "Символ введення символів",
	"The letter input symbol": "Символ введення букв",
	"Latin capital letter A in a negative square": "Латинська велика літера A\nу негативному квадраті",
	"Negative square Ab": "Негативний квадрат Ab",
	"Latin capital letter B in a negative square": "Латинська велика буква B\nу негативному квадраті",
	"Square Cl": "Квадратний Cl",
	"Square Cool": "Квадратний Крутий",
	"Squared for free": "У квадраті безкоштовно",
	"Information Symbol": "Символ Інформації",
	"Square ID": "Квадратний ID",
	"Latin capital letter M in a circle": "Латинська велика літера M\nу колі",
	"Square New": "Квадратний Новий",
	"Square NG": "Квадратний NG",
	"Negative square Latin capital letter O": "Негативна квадратна\nлатинська велика літера O",
	"Square OK": "Квадратний OK",
	"Negative square Latin capital letter P": "Негативна квадратна\nлатинська велика літера P",
	"SOS squared": "SOS в квадраті",
	"Squared Up with an exclamation mark": "У квадраті вгору\nзі знаком оклику",
	"Squared VS": "У квадраті VS",
	"Coco's Square Katakana": "Квадратна катакана Коко",
	"Square Katakana Sa": "Квадратна катакана Sa",
	"Square Cjk Unified Ideograph-6708": "Квадратний Cjk\nуніфікований ідеограф-6708",
	"Square Cjk Unified Ideograph-6709": "Квадратний Cjk\nуніфікований ідеограф-6709",
	"Square Cjk Unified Ideograph-6307": "Квадратний Cjk\nуніфікований ідеограф-6307",
	"The advantage of an ideogram in a circle": "Перевага ідеограми в колі",
	"Square Cjk Unified Ideograph-5272": "Квадратний Cjk\nуніфікований ідеограф-5272",
	"Square Cjk Unified Ideograph-7121": "Квадратний Cjk\nуніфікований ідеограф-7121",
	"Square Cjk Unified Ideograph-7981": "Квадратний Cjk\nуніфікований ідеограф-7981",
	"A round ideogram To accept": "Кругла ідеограма прийняти",
	"Square Cjk Unified Ideograph-7533": "Квадратний Cjk\nуніфікований ідеограф-7533",
	"Square Cjk Unified Ideograph-6408": "Квадратний Cjk\nуніфікований ідеограф-6408",
	"Square Cjk Unified Ideograph-7A7A": "Квадратний Cjk\nуніфікований ідеограф-7A7A",
	"Round ideogram Congratulations": "Кругла ідеограма привітання",
	"The round ideogram is a secret": "Кругла ідеограма Секрет",
	"Square Cjk Unified Ideograph-55B6": "Квадратний Cjk\nуніфікований ідеограф-55B6",
	"Square Cjk Unified Ideograph-6E80": "Квадратний Cjk\nуніфікований ідеограф-6E80",
	"The big red circle": "Велике червоне коло",
	"The big blue circle": "Велике синє коло",
	"The middle white circle": "Середній білий круг",
	"The middle black circle": "Середній чорний круг",
	"A large white square": "Білий великий квадрат",
	"A large black square": "Чорний великий квадрат",
	"The black middle square": "Чорний середній квадрат",
	"The white middle square": "Білий середній квадрат",
	"White Medium Small Square": "Білий Середній Маленький Квадрат",
	"Black Medium Small Square": "Чорний Середній Маленький Квадрат",
	"A small white square": "Білий маленький квадрат",
	"A small black square": "Чорний маленький квадрат",
	"A large orange diamond": "Великий помаранчевий діамант",
	"The big blue diamond": "Великий блакитний діамант",
	"A small orange diamond": "Маленький Помаранчевий діамант",
	"A small blue diamond": "Маленький блакитний діамант",
	"The red triangle is upside down": "Червоний трикутник вершиною вниз",
	"The shape of a diamond with a dot inside": "Форма ромба з точкою всередині",
	"Radio Button": "Радіокнопка",
	"Black square button": "Чорна квадратна кнопка",
	"White square button": "Біла квадратна кнопка",
	"The Checkered Flag": "Картатий прапор",
	"Triangular flag": "Трикутний прапор",
	"Crossed flags": "Схрещені прапори",
	"The Black Flag": "Чорний прапор",
	"The White flag": "Білий прапор",
	"Rainbow Flag": "Веселковий прапор",
	"The Flag of the Transgender Community": "Прапор Трансгендерної Спільноти",
	"The Pirate Flag": "Піратський прапор",
	"Flag: Ascension Island": "Прапор: О-В Вознесіння",
	"Flag: Andorra": "Прапор: Андорра",
	"Flag: UAE": "Прапор: ОАЕ",
	"Flag: Afghanistan": "Прапор: Афганістан",
	"Flag: Antigua and Barbuda": "Прапор: Антигуа і Барбуда",
	"Flag: Anguilla": "Прапор: Ангілья",
	"Flag: Albania": "Прапор: Албанія",
	"Flag: Armenia": "Прапор: Вірменія",
	"Flag: Angola": "Прапор: Ангола",
	"Flag: Antarctica": "Прапор: Антарктида",
	"Flag: Argentina": "Прапор: Аргентина",
	"Flag: American Samoa": "Прапор: Американське Самоа",
	"Flag: Austria": "Прапор: Австрія",
	"Flag: Australia": "Прапор: Австралія",
	"Flag: Aruba": "Прапор: Аруба",
	"Flag: Aland Islands": "Прапор: Аландські О-Ви",
	"Flag: Azerbaijan": "Прапор: Азербайджан",
	"Flag: Bosnia and Herzegovina": "Прапор: Боснія і Герцеговина",
	"Flag: Barbados": "Прапор: Барбадос",
	"Flag: Bangladesh": "Прапор: Бангладеш",
	"Flag: Belgium": "Прапор: Бельгія",
	"Flag: Burkina Faso": "Прапор: Буркіна-Фасо",
	"Flag: Bulgaria": "Прапор: Болгарія",
	"Flag: Bahrain": "Прапор: Бахрейн",
	"Flag: Burundi": "Прапор: Бурунді",
	"Flag: Benin": "Прапор: Бенін",
	"Flag: Saint Barthélémy": "Прапор: Сен-Бартелемі",
	"Flag: Bermuda": "Прапор: Бермудські О-Ви",
	"Flag: Brunei": "Прапор: Бруней",
	"Flag: Bolivia": "Прапор: Болівія",
	"Flag: Bonaire, Sint Eustatius and Saba": "Прапор: Бонейр, Сінт-Естатіус і Саба",
	"Flag: Brazil": "Прапор: Бразилія",
	"Flag: Bahamas": "Прапор: Багами",
	"Flag: Bhutan": "Прапор: Бутан",
	"Flag: O-In Bouvet": "Прапор: О - В Буві",
	"Flag: Botswana": "Прапор: Ботсвана",
	"Flag: Belarus": "Прапор: Білорусь",
	"Flag: Belize": "Прапор: Беліз",
	"Flag: Canada": "Прапор: Канада",
	"Flag: Coconut Islands": "Прапор: Кокосові О-Ва",
	"Flag: Congo - Kinshasa": "Прапор: Конго-Кіншаса",
	"Flag: Central African Republic": "Прапор: Центрально-Африканська Республіка",
	"Flag: Congo - Brazzaville": "Прапор: Конго-Браззавіль",
	"Flag: Switzerland": "Прапор: Швейцарія",
	"Flag: Ivory Coast": "Прапор: Кот-Д'івуар",
	"Flag: Cook Island": "Прапор: О-Ва Кука",
	"Flag: Chile": "Прапор: Чилі",
	"Flag: Cameroon": "Прапор: Камерун",
	"Flag: China": "Прапор: Китай",
	"Flag: Colombia-": "Прапор: Колумбія-",
	"Flag: Clipperton Island": "Прапор: О-В Кліппертон",
	"Flag: Costa Rica": "Прапор: Коста-Ріка",
	"Flag: Cuba": "Прапор: Куба",
	"Flag: Cape Verde": "Прапор: Кабо-Верде",
	"Flag: Curacao": "Прапор: Кюрасао",
	"Flag: Christmas Island": "Прапор: О-В Різдва",
	"Flag: Cyprus": "Прапор: Кіпр",
	"Flag: Czech Republic": "Прапор: Чехія",
	"Flag: Germany": "Прапор: Німеччина",
	"Flag: Diego Garcia": "Прапор: Дієго-Гарсія",
	"Flag: Djibouti": "Прапор: Джибуті",
	"Flag: Denmark": "Прапор: Данія",
	"Flag: Dominica": "Прапор: Домініка",
	"Flag: Dominican Republic": "Прапор: Домініканська Республіка",
	"Flag: Algeria": "Прапор: Алжир",
	"Flag: Ceuta and Melilla": "Прапор: Сеута і Мелілья",
	"Flag: Ecuador": "Прапор: Еквадор",
	"Flag: Estonia": "Прапор: Естонія",
	"Flag: Egypt": "Прапор: Єгипет",
	"Flag: Western Sahara": "Прапор: Західна Цукру",
	"Flag: Eritrea": "Прапор: Еритрея",
	"Flag: Spain": "Прапор: Іспанія",
	"Flag: Ethiopia": "Прапор: Ефіопія",
	"Flag: European Union": "Прапор: Європейський Союз",
	"Flag: Finland": "Прапор: Фінляндія",
	"Flag: Fiji": "Прапор: Фіджі",
	"Flag: Falkland Islands": "Прапор: Фолклендські О-Ви",
	"Flag: Federated States of Micronesia": "Прапор: Федеративні Штати Мікронезії",
	"Flag: Faroe Islands": "Прапор: Фарерські О-Ви",
	"Flag: France": "Прапор: Франція",
	"Flag: Gabon": "Прапор: Габон",
	"Flag: United Kingdom": "Прапор: Великобританія",
	"Flag: Grenada": "Прапор: Гренада",
	"Flag: Georgia": "Прапор: Грузія",
	"Flag: French Guiana": "Прапор: Французька Гвіана",
	"Flag: Guernsey": "Прапор: Гернсі",
	"Flag: Ghana": "Прапор: Гана",
	"Flag: Gibraltar": "Прапор: Гібралтар",
	"Flag: Greenland": "Прапор: Гренландія",
	"Flag: Gambia": "Прапор: Гамбія",
	"Flag: Guinea": "Прапор: Гвінея",
	"Flag: Guadeloupe": "Прапор: Гваделупа",
	"Flag: Equatorial Guinea": "Прапор: Екваторіальна Гвінея",
	"Flag: Greece": "Прапор: Греція",
	"Flag: South Georgia and the South Sandwich Islands": "Прапор: Південна Георгія і Південні Сандвічеві О-ви",
	"Flag: Guatemala": "Прапор: Гватемала",
	"Flag: Guam": "Прапор: Гуам",
	"Flag: Guinea-Bissau": "Прапор: Гвінея-Бісау",
	"Flag: Guyana": "Прапор: Гайана",
	"Flag: Hong Kong (SAR)": "Прапор: Гонконг (сар)",
	"Flag: Heard and McDonald Islands": "Прапор: о-ва Херд і Макдональд",
	"Flag: Honduras": "Прапор: Гондурас",
	"Flag: Croatia": "Прапор: Хорватія",
	"Flag: Haiti": "Прапор: Гаїті",
	"Flag: Hungary": "Прапор: Угорщина",
	"Flag: Canary Islands": "Прапор: Канарські О-Ви",
	"Flag: Indonesia": "Прапор: Індонезія",
	"Flag: Ireland": "Прапор: Ірландія",
	"Flag: Israel": "Прапор: Ізраїль",
	"Flag: Isle of Man": "Прапор: О-В Мен",
	"Flag: India": "Прапор: Індія",
	"Flag: British Indian Ocean Territory": "Прапор: Британська територія в Індійському океані",
	"Flag: Iraq": "Прапор: Ірак",
	"Flag: Iran": "Прапор: Іран",
	"Flag: Iceland": "Прапор: Ісландія",
	"Flag: Italy": "Прапор: Італія",
	"Flag: Jersey": "Прапор: Джерсі",
	"Flag: Jamaica": "Прапор: Ямайка",
	"Flag: Jordan": "Прапор: Йорданія",
	"Flag: Japan": "Прапор: Японія",
	"Flag: Kenya": "Прапор: Кенія",
	"Flag: Kyrgyzstan": "Прапор: Киргизія",
	"Flag: Cambodia": "Прапор: Камбоджа",
	"Flag: Kiribati": "Прапор: Кірібаті",
	"Flag: Comoros": "Прапор: Комори",
	"Flag: Saint Kitts and Nevis": "Прапор: Сент-Кітс і Невіс",
	"Flag: North Korea": "Прапор: Кндр",
	"Flag: Republic of Korea": "Прапор: Республіка Корея",
	"Flag: Kuwait": "Прапор: Кувейт",
	"Flag: Cayman Island": "Прапор: О-Ва Кайман",
	"Flag: Kazakhstan": "Прапор: Казахстан",
	"Flag: Laos": "Прапор: Лаос",
	"Flag: Lebanon": "Прапор: Ліван",
	"Flag: Saint Lucia": "Прапор: Сент-Люсія",
	"Flag: Liechtenstein": "Прапор: Ліхтенштейн",
	"Flag: Sri Lanka": "Прапор: Шрі-Ланка",
	"Flag: Liberia": "Прапор: Ліберія",
	"Flag: Lesotho": "Прапор: Лесото",
	"Flag: Lithuania": "Прапор: Литва",
	"Flag: Luxembourg": "Прапор: Люксембург",
	"Flag: Latvia": "Прапор: Латвія",
	"Flag: Libya": "Прапор: Лівія",
	"Flag: Morocco": "Прапор: Марокко",
	"Flag: Monaco": "Прапор: Монако",
	"Flag: Moldova": "Прапор: Молдова",
	"Flag: Montenegro": "Прапор: Чорногорія",
	"Flag: Saint Martin": "Прапор: Сен-Мартен",
	"Flag: Madagascar": "Прапор: Мадагаскар",
	"Flag: Marshall Islands": "Прапор: Маршаллові О-Ви",
	"Flag: North Macedonia": "Прапор: Північна Македонія",
	"Flag: Mali": "Прапор: Малі",
	"Flag: Myanmar (Burma)": "Прапор: М'янма (Бірма)",
	"Flag: Mongolia": "Прапор: Монголія",
	"Flag: Macau (Sar)": "Прапор: Макао (Сар)",
	"Flag: Northern Mariana Islands": "Прапор: Північні Маріанські О-Ви",
	"Flag: Martinique": "Прапор: Мартініка",
	"Flag: Mauritania": "Прапор: Мавританія",
	"Flag: Montserrat": "Прапор: Монтсеррат",
	"Flag: Malta": "Прапор: Мальта",
	"Flag: Mauritius": "Прапор: Маврикій",
	"Flag: Maldives": "Прапор: Мальдіви",
	"Flag: Malawi": "Прапор: Малаві",
	"Flag: Mexico": "Прапор: Мексика",
	"Flag: Malaysia": "Прапор: Малайзія",
	"Flag: Mozambique": "Прапор: Мозамбік",
	"Flag: Namibia": "Прапор: Намібія",
	"Flag: New Caledonia": "Прапор: Нова Каледонія",
	"Flag: Niger": "Прапор: Нігер",
	"Flag: Norfolk Island": "Прапор: О-В Норфолк",
	"Flag: Nigeria": "Прапор: Нігерія",
	"Flag: Nicaragua": "Прапор: Нікарагуа",
	"Flag: Netherlands": "Прапор: Нідерланди",
	"Flag: Norway": "Прапор: Норвегія",
	"Flag: Nepal": "Прапор: Непал",
	"Flag: Nauru": "Прапор: Науру",
	"Flag: Niue": "Прапор: Ніуе",
	"Flag: New Zealand": "Прапор: Нова Зеландія",
	"Flag: Oman": "Прапор: Оман",
	"Flag: Panama": "Прапор: Панама",
	"Flag: Peru": "Прапор: Перу",
	"Flag: French Polynesia": "Прапор: Французька Полінезія",
	"Flag: Papua New Guinea": "Прапор: Папуа-Нова Гвінея",
	"Flag: Philippines": "Прапор: Філіппіни",
	"Flag: Pakistan": "Прапор: Пакистан",
	"Flag: Poland": "Прапор: Польща",
	"Flag: Saint Pierre and Miquelon": "Прапор: Сен-П'єр і Мікелон",
	"Flag: Pitcairn Island": "Прапор: О-Ва Піткерн",
	"Flag: Puerto Rico": "Прапор: Пуерто-Рико",
	"Flag: Palestinian Territories": "Прапор: Палестинські Території",
	"Flag: Portugal": "Прапор: Португалія",
	"Flag: Palau": "Прапор: Палау",
	"Flag: Paraguay": "Прапор: Парагвай",
	"Flag: Qatar": "Прапор: Катар",
	"Flag: Reunion": "Прапор: Реюньйон",
	"Flag: Romania": "Прапор: Румунія",
	"Flag: Serbia": "Прапор: Сербія",
	"Flag: Russia": "Прапор: Росія",
	"Flag: Rwanda": "Прапор: Руанда",
	"Flag: Saudi Arabia": "Прапор: Саудівська Аравія",
	"Flag: Solomon Islands": "Прапор: Соломонові О-Ви",
	"Flag: Seychelles": "Прапор: Сейшельські О-Ви",
	"Flag: Sudan": "Прапор: Судан",
	"Flag: Sweden": "Прапор: Швеція",
	"Flag: Singapore": "Прапор: Сінгапур",
	"Flag: St. Helena Island": "Прапор: О-В Св. Олени",
	"Flag: Slovenia": "Прапор: Словенія",
	"Flag: Svalbard and Jan Mayen": "Прапор: Шпіцберген і Ян-Майен",
	"Flag: Slovakia": "Прапор: Словаччина",
	"Flag: Sierra Leone": "Прапор: Сьєрра-Леоне",
	"Flag: San Marino": "Прапор: Сан-Марино",
	"Flag: Senegal": "Прапор: Сенегал",
	"Flag: Somalia": "Прапор: Сомалі",
	"Flag: Suriname": "Прапор: Суринам",
	"Flag: South Sudan": "Прапор: Південний Судан",
	"Flag: Sao Tome and Principe": "Прапор: Сан-Томе і Принсіпі",
	"Flag: El Salvador": "Прапор: Сальвадор",
	"Flag: Sint Maarten": "Прапор: Сінт-Мартен",
	"Flag: Syria": "Прапор: Сирія",
	"Flag: Eswatini": "Прапор: Есватіні",
	"Flag: Tristan Da Cunha": "Прапор: Трістан-Да-Кунья",
	"Flag: Turks and Caicos Islands": "Прапор: Теркс і Кайкос",
	"Flag: Chad": "Прапор: Чад",
	"Flag: French Southern Territories": "Прапор: Французькі Південні Території",
	"Flag: Togo": "Прапор: Того",
	"Flag: Thailand": "Прапор: Таїланд",
	"Flag: Tajikistan": "Прапор: Таджикистан",
	"Flag: Tokelau": "Прапор: Токелау",
	"Flag: East Timor": "Прапор: Східний Тимор",
	"Flag: Turkmenistan": "Прапор: Туркменістан",
	"Flag: Tunis": "Прапор: Туніс",
	"Flag: Tonga": "Прапор: Тонга",
	"Flag: Turkey": "Прапор: Туреччина",
	"Flag: Trinidad and Tobago": "Прапор: Тринідад і Тобаго",
	"Flag: Tuvalu": "Прапор: Тувалу",
	"Flag: Taiwan": "Прапор: Тайвань",
	"Flag: Tanzania": "Прапор: Танзанія",
	"Flag: Ukraine": "Прапор: Україна",
	"Flag: Uganda": "Прапор: Уганда",
	"Flag: Outer Small Islands (USA)": "Прапор: Зовнішні малі О-ви (США)",
	"Flag: United Nations": "Прапор: Організація Об'єднаних Націй",
	"Flag: United States": "Прапор: США",
	"Flag: Uruguay": "Прапор: Уругвай",
	"Flag: Uzbekistan": "Прапор: Узбекистан",
	"Flag: Vatican City": "Прапор: Ватикан",
	"Flag: Saint Vincent and the Grenadines": "Прапор: Сент-Вінсент і Гренадини",
	"Flag: Venezuela": "Прапор: Венесуела",
	"Flag: Virgin Islands (Great Britain)": "Прапор: Віргінські О-Ви (Великобританія)",
	"Flag: Virgin Islands (USA)": "Прапор: Віргінські О-ви (США)",
	"Flag: Vietnam": "Прапор: В'єтнам",
	"Flag: Vanuatu": "Прапор: Вануату",
	"Flag: Wallis and Futuna": "Прапор: Уолліс і Футуна",
	"Flag: Samoa": "Прапор: Самоа",
	"Flag: Kosovo": "Прапор: Косово",
	"Flag: Yemen": "Прапор: Ємен",
	"Flag: Mayotte": "Прапор: Майотта",
	"Flag: Republic of South Africa": "Прапор: Південно-Африканська Республіка",
	"Flag: Zambia": "Прапор: Замбія",
	"Flag: Zimbabwe": "Прапор: Зімбабве",
	"Flag: England": "Прапор: Англія",
	"Flag: Scotland": "Прапор: Шотландія",
	"Flag: Wales": "Прапор: Уельс"
});